#-------------#
# Import Vars #
#-------------#
Import('*')

#---------#
# Sources #
#---------#
src = ["about.txt",
       "track.txt",
       "surfaces.txt",
       "trackshot.png",
       "roads.trk"]

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)
env.Distribute (bin_dir, src)

#--------------------#
# Install data files #
#--------------------#
install = env.Install(Dir(env.subst('$data_directory/tracks/neurburgring_nordschleife')), src)
env.Alias('install', install)

#----------------#
# Subdirectories #
#----------------#
Export(['env', 'src_dir', 'bin_dir'])

SConscript('objects/SConscript')
