return {
  byId = {
    [0] = {
      args = {},
      handler = "ScrCmd_nop",
      name = "nop",
      size = 1,
    },
    [1] = {
      args = {},
      handler = "ScrCmd_nop1",
      name = "nop1",
      size = 1,
    },
    [2] = {
      args = {},
      handler = "ScrCmd_end",
      name = "end",
      size = 1,
    },
    [3] = {
      args = {},
      handler = "ScrCmd_return",
      name = "return",
      size = 1,
    },
    [4] = {
      args = {
        { kind = "word", name = "destination" },
      },
      handler = "ScrCmd_call",
      name = "call",
      size = 5,
    },
    [5] = {
      args = {
        { kind = "word", name = "destination" },
      },
      handler = "ScrCmd_goto",
      name = "goto",
      size = 5,
    },
    [6] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "word", name = "destination" },
      },
      handler = "ScrCmd_goto_if",
      name = "goto_if",
      size = 6,
    },
    [7] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "word", name = "destination" },
      },
      handler = "ScrCmd_call_if",
      name = "call_if",
      size = 6,
    },
    [8] = {
      args = {
        { kind = "byte", name = "function" },
      },
      handler = "ScrCmd_gotostd",
      name = "gotostd",
      size = 2,
    },
    [9] = {
      args = {
        { kind = "byte", name = "function" },
      },
      handler = "ScrCmd_callstd",
      name = "callstd",
      size = 2,
    },
    [10] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "byte", name = "function" },
      },
      handler = "ScrCmd_gotostd_if",
      name = "gotostd_if",
      size = 3,
    },
    [11] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "byte", name = "function" },
      },
      handler = "ScrCmd_callstd_if",
      name = "callstd_if",
      size = 3,
    },
    [12] = {
      args = {},
      handler = "ScrCmd_gotoram",
      name = "gotoram",
      size = 1,
    },
    [13] = {
      args = {},
      handler = "ScrCmd_killscript",
      name = "killscript",
      size = 1,
    },
    [14] = {
      args = {
        { kind = "byte", name = "value" },
      },
      handler = "ScrCmd_setmysteryeventstatus",
      name = "setmysteryeventstatus",
      size = 2,
    },
    [15] = {
      args = {
        { kind = "byte", name = "destination" },
        { kind = "word", name = "value" },
      },
      handler = "ScrCmd_loadword",
      name = "loadword",
      size = 6,
    },
    [16] = {
      args = {
        { kind = "byte", name = "destination" },
        { kind = "byte", name = "value" },
      },
      handler = "ScrCmd_loadbyte",
      name = "loadbyte",
      size = 3,
    },
    [17] = {
      args = {
        { kind = "byte", name = "value" },
        { kind = "word", name = "offset" },
      },
      handler = "ScrCmd_writebytetoaddr",
      name = "writebytetoaddr",
      size = 6,
    },
    [18] = {
      args = {
        { kind = "byte", name = "destination" },
        { kind = "word", name = "source" },
      },
      handler = "ScrCmd_loadbytefromaddr",
      name = "loadbytefromaddr",
      size = 6,
    },
    [19] = {
      args = {
        { kind = "byte", name = "source" },
        { kind = "word", name = "destination" },
      },
      handler = "ScrCmd_setptrbyte",
      name = "setptrbyte",
      size = 6,
    },
    [20] = {
      args = {
        { kind = "byte", name = "destination" },
        { kind = "byte", name = "source" },
      },
      handler = "ScrCmd_copylocal",
      name = "copylocal",
      size = 3,
    },
    [21] = {
      args = {
        { kind = "word", name = "destination" },
        { kind = "word", name = "source" },
      },
      handler = "ScrCmd_copybyte",
      name = "copybyte",
      size = 9,
    },
    [22] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "value" },
      },
      handler = "ScrCmd_setvar",
      name = "setvar",
      size = 5,
    },
    [23] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "value" },
      },
      handler = "ScrCmd_addvar",
      name = "addvar",
      size = 5,
    },
    [24] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "value" },
      },
      handler = "ScrCmd_subvar",
      name = "subvar",
      size = 5,
    },
    [25] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "source" },
      },
      handler = "ScrCmd_copyvar",
      name = "copyvar",
      size = 5,
    },
    [26] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "source" },
      },
      handler = "ScrCmd_setorcopyvar",
      name = "setorcopyvar",
      size = 5,
    },
    [27] = {
      args = {
        { kind = "byte", name = "byte1" },
        { kind = "byte", name = "byte2" },
      },
      handler = "ScrCmd_compare_local_to_local",
      name = "compare_local_to_local",
      size = 3,
    },
    [28] = {
      args = {
        { kind = "byte", name = "a" },
        { kind = "byte", name = "b" },
      },
      handler = "ScrCmd_compare_local_to_value",
      name = "compare_local_to_value",
      size = 3,
    },
    [29] = {
      args = {
        { kind = "byte", name = "a" },
        { kind = "word", name = "b" },
      },
      handler = "ScrCmd_compare_local_to_addr",
      name = "compare_local_to_addr",
      size = 6,
    },
    [30] = {
      args = {
        { kind = "word", name = "a" },
        { kind = "byte", name = "b" },
      },
      handler = "ScrCmd_compare_addr_to_local",
      name = "compare_addr_to_local",
      size = 6,
    },
    [31] = {
      args = {
        { kind = "word", name = "a" },
        { kind = "byte", name = "b" },
      },
      handler = "ScrCmd_compare_addr_to_value",
      name = "compare_addr_to_value",
      size = 6,
    },
    [32] = {
      args = {
        { kind = "word", name = "a" },
        { kind = "word", name = "b" },
      },
      handler = "ScrCmd_compare_addr_to_addr",
      name = "compare_addr_to_addr",
      size = 9,
    },
    [33] = {
      args = {
        { kind = "half", name = "var" },
        { kind = "half", name = "value" },
      },
      handler = "ScrCmd_compare_var_to_value",
      name = "compare_var_to_value",
      size = 5,
    },
    [34] = {
      args = {
        { kind = "half", name = "var1" },
        { kind = "half", name = "var2" },
      },
      handler = "ScrCmd_compare_var_to_var",
      name = "compare_var_to_var",
      size = 5,
    },
    [35] = {
      args = {
        { kind = "word", name = "func" },
      },
      handler = "ScrCmd_callnative",
      name = "callnative",
      size = 5,
    },
    [36] = {
      args = {
        { kind = "word", name = "func" },
      },
      handler = "ScrCmd_gotonative",
      name = "gotonative",
      size = 5,
    },
    [37] = {
      args = {
        { kind = "half", name = "SPECIAL_\\function" },
      },
      handler = "ScrCmd_special",
      name = "special",
      size = 3,
    },
    [38] = {
      args = {
        { kind = "half", name = "output" },
        { kind = "half", name = "SPECIAL_\\function" },
      },
      handler = "ScrCmd_specialvar",
      name = "specialvar",
      size = 5,
    },
    [39] = {
      args = {},
      handler = "ScrCmd_waitstate",
      name = "waitstate",
      size = 1,
    },
    [40] = {
      args = {
        { kind = "half", name = "time" },
      },
      handler = "ScrCmd_delay",
      name = "delay",
      size = 3,
    },
    [41] = {
      args = {
        { kind = "half", name = "a" },
      },
      handler = "ScrCmd_setflag",
      name = "setflag",
      size = 3,
    },
    [42] = {
      args = {
        { kind = "half", name = "a" },
      },
      handler = "ScrCmd_clearflag",
      name = "clearflag",
      size = 3,
    },
    [43] = {
      args = {
        { kind = "half", name = "a" },
      },
      handler = "ScrCmd_checkflag",
      name = "checkflag",
      size = 3,
    },
    [44] = {
      args = {
        { kind = "half", name = "hour" },
        { kind = "half", name = "minute" },
      },
      handler = "ScrCmd_initclock",
      name = "initclock",
      size = 5,
    },
    [45] = {
      args = {},
      handler = "ScrCmd_dotimebasedevents",
      name = "dotimebasedevents",
      size = 1,
    },
    [46] = {
      args = {},
      handler = "ScrCmd_gettime",
      name = "gettime",
      size = 1,
    },
    [47] = {
      args = {
        { kind = "half", name = "sound_number" },
      },
      handler = "ScrCmd_playse",
      name = "playse",
      size = 3,
    },
    [48] = {
      args = {},
      handler = "ScrCmd_waitse",
      name = "waitse",
      size = 1,
    },
    [49] = {
      args = {
        { kind = "half", name = "fanfare_number" },
      },
      handler = "ScrCmd_playfanfare",
      name = "playfanfare",
      size = 3,
    },
    [50] = {
      args = {},
      handler = "ScrCmd_waitfanfare",
      name = "waitfanfare",
      size = 1,
    },
    [51] = {
      args = {
        { kind = "half", name = "song_number" },
        { kind = "byte", name = "unknown" },
      },
      handler = "ScrCmd_playbgm",
      name = "playbgm",
      size = 4,
    },
    [52] = {
      args = {
        { kind = "half", name = "song_number" },
      },
      handler = "ScrCmd_savebgm",
      name = "savebgm",
      size = 3,
    },
    [53] = {
      args = {},
      handler = "ScrCmd_fadedefaultbgm",
      name = "fadedefaultbgm",
      size = 1,
    },
    [54] = {
      args = {
        { kind = "half", name = "song_number" },
      },
      handler = "ScrCmd_fadenewbgm",
      name = "fadenewbgm",
      size = 3,
    },
    [55] = {
      args = {
        { kind = "byte", name = "speed" },
      },
      handler = "ScrCmd_fadeoutbgm",
      name = "fadeoutbgm",
      size = 2,
    },
    [56] = {
      args = {
        { kind = "byte", name = "speed" },
      },
      handler = "ScrCmd_fadeinbgm",
      name = "fadeinbgm",
      size = 2,
    },
    [57] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_warp",
      name = "warp",
      size = 8,
    },
    [58] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_warpsilent",
      name = "warpsilent",
      size = 8,
    },
    [59] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_warpdoor",
      name = "warpdoor",
      size = 8,
    },
    [60] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_warphole",
      name = "warphole",
      size = 3,
    },
    [61] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_warpteleport",
      name = "warpteleport",
      size = 8,
    },
    [62] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_setwarp",
      name = "setwarp",
      size = 8,
    },
    [63] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_setdynamicwarp",
      name = "setdynamicwarp",
      size = 8,
    },
    [64] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_setdivewarp",
      name = "setdivewarp",
      size = 8,
    },
    [65] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_setholewarp",
      name = "setholewarp",
      size = 8,
    },
    [66] = {
      args = {
        { kind = "half", name = "X" },
        { kind = "half", name = "Y" },
      },
      handler = "ScrCmd_getplayerxy",
      name = "getplayerxy",
      size = 5,
    },
    [67] = {
      args = {},
      handler = "ScrCmd_getpartysize",
      name = "getpartysize",
      size = 1,
    },
    [68] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "quantity" },
      },
      handler = "ScrCmd_additem",
      name = "additem",
      size = 5,
    },
    [69] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "quantity" },
      },
      handler = "ScrCmd_removeitem",
      name = "removeitem",
      size = 5,
    },
    [70] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "quantity" },
      },
      handler = "ScrCmd_checkitemspace",
      name = "checkitemspace",
      size = 5,
    },
    [71] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "quantity" },
      },
      handler = "ScrCmd_checkitem",
      name = "checkitem",
      size = 5,
    },
    [72] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_checkitemtype",
      name = "checkitemtype",
      size = 3,
    },
    [73] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "quantity" },
      },
      handler = "ScrCmd_addpcitem",
      name = "addpcitem",
      size = 5,
    },
    [74] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "quantity" },
      },
      handler = "ScrCmd_checkpcitem",
      name = "checkpcitem",
      size = 5,
    },
    [75] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      handler = "ScrCmd_adddecoration",
      name = "adddecoration",
      size = 3,
    },
    [76] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      handler = "ScrCmd_removedecoration",
      name = "removedecoration",
      size = 3,
    },
    [77] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      handler = "ScrCmd_checkdecor",
      name = "checkdecor",
      size = 3,
    },
    [78] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      handler = "ScrCmd_checkdecorspace",
      name = "checkdecorspace",
      size = 3,
    },
    [79] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "word", name = "movements" },
      },
      handler = "ScrCmd_applymovement",
      name = "applymovement",
      size = 7,
    },
    [80] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "word", name = "movements" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_applymovement_at",
      macro = "applymovement",
      name = "applymovement_at",
      size = 9,
    },
    [81] = {
      args = {
        { kind = "half", name = "localId" },
      },
      handler = "ScrCmd_waitmovement",
      name = "waitmovement",
      size = 3,
    },
    [82] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_waitmovement_at",
      macro = "waitmovement",
      name = "waitmovement_at",
      size = 5,
    },
    [83] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_removeobject",
      name = "removeobject",
      size = 3,
    },
    [84] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_removeobject_at",
      macro = "removeobject",
      name = "removeobject_at",
      size = 5,
    },
    [85] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_addobject",
      name = "addobject",
      size = 3,
    },
    [86] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_addobject_at",
      macro = "addobject",
      name = "addobject_at",
      size = 5,
    },
    [87] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_setobjectxy",
      name = "setobjectxy",
      size = 7,
    },
    [88] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_showobjectat",
      name = "showobjectat",
      size = 5,
    },
    [89] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_hideobjectat",
      name = "hideobjectat",
      size = 5,
    },
    [90] = {
      args = {},
      handler = "ScrCmd_faceplayer",
      name = "faceplayer",
      size = 1,
    },
    [91] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "direction" },
      },
      handler = "ScrCmd_turnobject",
      name = "turnobject",
      size = 4,
    },
    [92] = {
      args = {
        { kind = "byte", name = "type" },
        { kind = "half", name = "trainer" },
        { kind = "half", name = "local_id" },
        { kind = "word", name = "pointer1" },
      },
      handler = "ScrCmd_trainerbattle",
      name = "trainerbattle",
      prefix = 10,
      variable = true,
    },
    [93] = {
      args = {},
      handler = "ScrCmd_trainerbattlebegin",
      name = "trainerbattlebegin",
      size = 1,
    },
    [94] = {
      args = {},
      handler = "ScrCmd_gotopostbattlescript",
      name = "gotopostbattlescript",
      size = 1,
    },
    [95] = {
      args = {},
      handler = "ScrCmd_gotobeatenscript",
      name = "gotobeatenscript",
      size = 1,
    },
    [96] = {
      args = {
        { kind = "half", name = "trainer" },
      },
      handler = "ScrCmd_checktrainerflag",
      name = "checktrainerflag",
      size = 3,
    },
    [97] = {
      args = {
        { kind = "half", name = "trainer" },
      },
      handler = "ScrCmd_settrainerflag",
      name = "settrainerflag",
      size = 3,
    },
    [98] = {
      args = {
        { kind = "half", name = "trainer" },
      },
      handler = "ScrCmd_cleartrainerflag",
      name = "cleartrainerflag",
      size = 3,
    },
    [99] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_setobjectxyperm",
      name = "setobjectxyperm",
      size = 7,
    },
    [100] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_moveobjectoffscreen",
      name = "moveobjectoffscreen",
      size = 3,
    },
    [101] = {
      args = {
        { kind = "half", name = "word" },
        { kind = "byte", name = "byte" },
      },
      handler = "ScrCmd_setobjectmovementtype",
      name = "setobjectmovementtype",
      size = 4,
    },
    [102] = {
      args = {},
      handler = "ScrCmd_waitmessage",
      name = "waitmessage",
      size = 1,
    },
    [103] = {
      args = {
        { kind = "word", name = "text" },
      },
      handler = "ScrCmd_message",
      name = "message",
      size = 5,
    },
    [104] = {
      args = {},
      handler = "ScrCmd_closemessage",
      name = "closemessage",
      size = 1,
    },
    [105] = {
      args = {},
      handler = "ScrCmd_lockall",
      name = "lockall",
      size = 1,
    },
    [106] = {
      args = {},
      handler = "ScrCmd_lock",
      name = "lock",
      size = 1,
    },
    [107] = {
      args = {},
      handler = "ScrCmd_releaseall",
      name = "releaseall",
      size = 1,
    },
    [108] = {
      args = {},
      handler = "ScrCmd_release",
      name = "release",
      size = 1,
    },
    [109] = {
      args = {},
      handler = "ScrCmd_waitbuttonpress",
      name = "waitbuttonpress",
      size = 1,
    },
    [110] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_yesnobox",
      name = "yesnobox",
      size = 3,
    },
    [111] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "list" },
        { kind = "byte", name = "b" },
      },
      handler = "ScrCmd_multichoice",
      name = "multichoice",
      size = 5,
    },
    [112] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "list" },
        { kind = "byte", name = "default" },
        { kind = "byte", name = "b" },
      },
      handler = "ScrCmd_multichoicedefault",
      name = "multichoicedefault",
      size = 6,
    },
    [113] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "list" },
        { kind = "byte", name = "per_row" },
        { kind = "byte", name = "B" },
      },
      handler = "ScrCmd_multichoicegrid",
      name = "multichoicegrid",
      size = 6,
    },
    [114] = {
      args = {
        { kind = "byte", name = "byte1" },
        { kind = "byte", name = "byte2" },
        { kind = "byte", name = "byte3" },
        { kind = "byte", name = "byte4" },
      },
      handler = "ScrCmd_drawbox",
      name = "drawbox",
      size = 5,
    },
    [115] = {
      args = {
        { kind = "byte", name = "byte1" },
        { kind = "byte", name = "byte2" },
        { kind = "byte", name = "byte3" },
        { kind = "byte", name = "byte4" },
      },
      handler = "ScrCmd_erasebox",
      name = "erasebox",
      size = 5,
    },
    [116] = {
      args = {
        { kind = "byte", name = "byte1" },
        { kind = "byte", name = "byte2" },
        { kind = "byte", name = "byte3" },
        { kind = "byte", name = "byte4" },
      },
      handler = "ScrCmd_drawboxtext",
      name = "drawboxtext",
      size = 5,
    },
    [117] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_showmonpic",
      name = "showmonpic",
      size = 5,
    },
    [118] = {
      args = {},
      handler = "ScrCmd_hidemonpic",
      name = "hidemonpic",
      size = 1,
    },
    [119] = {
      args = {
        { kind = "byte", name = "a" },
      },
      handler = "ScrCmd_showcontestwinner",
      name = "showcontestwinner",
      size = 2,
    },
    [120] = {
      args = {
        { kind = "word", name = "text" },
      },
      handler = "ScrCmd_braillemessage",
      name = "braillemessage",
      size = 5,
    },
    [121] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "byte", name = "level" },
        { kind = "half", name = "item" },
        { kind = "word", name = "0x0" },
        { kind = "word", name = "0x0" },
        { kind = "byte", name = "0" },
      },
      handler = "ScrCmd_givemon",
      name = "givemon",
      size = 15,
    },
    [122] = {
      args = {
        { kind = "half", name = "species" },
      },
      handler = "ScrCmd_giveegg",
      name = "giveegg",
      size = 3,
    },
    [123] = {
      args = {
        { kind = "byte", name = "index" },
        { kind = "byte", name = "slot" },
        { kind = "half", name = "move" },
      },
      handler = "ScrCmd_setmonmove",
      name = "setmonmove",
      size = 5,
    },
    [124] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_checkpartymove",
      name = "checkpartymove",
      size = 3,
    },
    [125] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "species" },
      },
      handler = "ScrCmd_bufferspeciesname",
      name = "bufferspeciesname",
      size = 4,
    },
    [126] = {
      args = {
        { kind = "byte", name = "out" },
      },
      handler = "ScrCmd_bufferleadmonspeciesname",
      name = "bufferleadmonspeciesname",
      size = 2,
    },
    [127] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "slot" },
      },
      handler = "ScrCmd_bufferpartymonnick",
      name = "bufferpartymonnick",
      size = 4,
    },
    [128] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "item" },
      },
      handler = "ScrCmd_bufferitemname",
      name = "bufferitemname",
      size = 4,
    },
    [129] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "decoration" },
      },
      handler = "ScrCmd_bufferdecorationname",
      name = "bufferdecorationname",
      size = 4,
    },
    [130] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "move" },
      },
      handler = "ScrCmd_buffermovename",
      name = "buffermovename",
      size = 4,
    },
    [131] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "input" },
      },
      handler = "ScrCmd_buffernumberstring",
      name = "buffernumberstring",
      size = 4,
    },
    [132] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_bufferstdstring",
      name = "bufferstdstring",
      size = 4,
    },
    [133] = {
      args = {
        { kind = "byte", name = "out" },
        { kind = "word", name = "offset" },
      },
      handler = "ScrCmd_bufferstring",
      name = "bufferstring",
      size = 6,
    },
    [134] = {
      args = {
        { kind = "word", name = "products" },
      },
      handler = "ScrCmd_pokemart",
      name = "pokemart",
      size = 5,
    },
    [135] = {
      args = {
        { kind = "word", name = "products" },
      },
      handler = "ScrCmd_pokemartdecoration",
      name = "pokemartdecoration",
      size = 5,
    },
    [136] = {
      args = {
        { kind = "word", name = "products" },
      },
      handler = "ScrCmd_pokemartdecoration2",
      name = "pokemartdecoration2",
      size = 5,
    },
    [137] = {
      args = {
        { kind = "half", name = "word" },
      },
      handler = "ScrCmd_playslotmachine",
      name = "playslotmachine",
      size = 3,
    },
    [138] = {
      args = {
        { kind = "byte", name = "tree_id" },
        { kind = "byte", name = "berry" },
        { kind = "byte", name = "growth_stage" },
      },
      handler = "ScrCmd_setberrytree",
      name = "setberrytree",
      size = 4,
    },
    [139] = {
      args = {},
      handler = "ScrCmd_choosecontestmon",
      name = "choosecontestmon",
      size = 1,
    },
    [140] = {
      args = {},
      handler = "ScrCmd_startcontest",
      name = "startcontest",
      size = 1,
    },
    [141] = {
      args = {},
      handler = "ScrCmd_showcontestresults",
      name = "showcontestresults",
      size = 1,
    },
    [142] = {
      args = {},
      handler = "ScrCmd_contestlinktransfer",
      name = "contestlinktransfer",
      size = 1,
    },
    [143] = {
      args = {
        { kind = "half", name = "limit" },
      },
      handler = "ScrCmd_random",
      name = "random",
      size = 3,
    },
    [144] = {
      args = {
        { kind = "word", name = "value" },
        { kind = "byte", name = "check" },
      },
      handler = "ScrCmd_addmoney",
      name = "addmoney",
      size = 6,
    },
    [145] = {
      args = {
        { kind = "word", name = "value" },
        { kind = "byte", name = "check" },
      },
      handler = "ScrCmd_removemoney",
      name = "removemoney",
      size = 6,
    },
    [146] = {
      args = {
        { kind = "word", name = "value" },
        { kind = "byte", name = "check" },
      },
      handler = "ScrCmd_checkmoney",
      name = "checkmoney",
      size = 6,
    },
    [147] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_showmoneybox",
      name = "showmoneybox",
      size = 3,
    },
    [148] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_hidemoneybox",
      name = "hidemoneybox",
      size = 3,
    },
    [149] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_updatemoneybox",
      name = "updatemoneybox",
      size = 3,
    },
    [150] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_getpricereduction",
      name = "getpricereduction",
      size = 3,
    },
    [151] = {
      args = {
        { kind = "byte", name = "mode" },
      },
      handler = "ScrCmd_fadescreen",
      name = "fadescreen",
      size = 2,
    },
    [152] = {
      args = {
        { kind = "byte", name = "mode" },
        { kind = "byte", name = "speed" },
      },
      handler = "ScrCmd_fadescreenspeed",
      name = "fadescreenspeed",
      size = 3,
    },
    [153] = {
      args = {
        { kind = "half", name = "word" },
      },
      handler = "ScrCmd_setflashradius",
      name = "setflashradius",
      size = 3,
    },
    [154] = {
      args = {
        { kind = "byte", name = "byte" },
      },
      handler = "ScrCmd_animateflash",
      name = "animateflash",
      size = 2,
    },
    [155] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_messageautoscroll",
      name = "messageautoscroll",
      size = 5,
    },
    [156] = {
      args = {
        { kind = "half", name = "animation" },
      },
      handler = "ScrCmd_dofieldeffect",
      name = "dofieldeffect",
      size = 3,
    },
    [157] = {
      args = {
        { kind = "byte", name = "argument" },
        { kind = "half", name = "param" },
      },
      handler = "ScrCmd_setfieldeffectargument",
      name = "setfieldeffectargument",
      size = 4,
    },
    [158] = {
      args = {
        { kind = "half", name = "animation" },
      },
      handler = "ScrCmd_waitfieldeffect",
      name = "waitfieldeffect",
      size = 3,
    },
    [159] = {
      args = {
        { kind = "half", name = "heallocation" },
      },
      handler = "ScrCmd_setrespawn",
      name = "setrespawn",
      size = 3,
    },
    [160] = {
      args = {},
      handler = "ScrCmd_checkplayergender",
      name = "checkplayergender",
      size = 1,
    },
    [161] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "half", name = "effect" },
      },
      handler = "ScrCmd_playmoncry",
      name = "playmoncry",
      size = 5,
    },
    [162] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
        { kind = "half", name = "metatile_number" },
        { kind = "half", name = "has_collision" },
      },
      handler = "ScrCmd_setmetatile",
      name = "setmetatile",
      size = 9,
    },
    [163] = {
      args = {},
      handler = "ScrCmd_resetweather",
      name = "resetweather",
      size = 1,
    },
    [164] = {
      args = {
        { kind = "half", name = "type" },
      },
      handler = "ScrCmd_setweather",
      name = "setweather",
      size = 3,
    },
    [165] = {
      args = {},
      handler = "ScrCmd_doweather",
      name = "doweather",
      size = 1,
    },
    [166] = {
      args = {
        { kind = "byte", name = "subroutine" },
      },
      handler = "ScrCmd_setstepcallback",
      name = "setstepcallback",
      size = 2,
    },
    [167] = {
      args = {
        { kind = "half", name = "index" },
      },
      handler = "ScrCmd_setmaplayoutindex",
      name = "setmaplayoutindex",
      size = 3,
    },
    [168] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "priority" },
      },
      handler = "ScrCmd_setobjectpriority",
      name = "setobjectpriority",
      size = 6,
    },
    [169] = {
      args = {
        { kind = "half", name = "index" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      handler = "ScrCmd_resetobjectpriority",
      name = "resetobjectpriority",
      size = 5,
    },
    [170] = {
      args = {
        { kind = "byte", name = "sprite" },
        { kind = "byte", name = "byte2" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
        { kind = "byte", name = "elevation" },
        { kind = "byte", name = "direction" },
      },
      handler = "ScrCmd_createvobject",
      name = "createvobject",
      size = 9,
    },
    [171] = {
      args = {
        { kind = "byte", name = "index" },
        { kind = "byte", name = "direction" },
      },
      handler = "ScrCmd_turnvobject",
      name = "turnvobject",
      size = 3,
    },
    [172] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_opendoor",
      name = "opendoor",
      size = 5,
    },
    [173] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_closedoor",
      name = "closedoor",
      size = 5,
    },
    [174] = {
      args = {},
      handler = "ScrCmd_waitdooranim",
      name = "waitdooranim",
      size = 1,
    },
    [175] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_setdooropen",
      name = "setdooropen",
      size = 5,
    },
    [176] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_setdoorclosed",
      name = "setdoorclosed",
      size = 5,
    },
    [177] = {
      args = {
        { kind = "byte", name = "floor" },
        { kind = "half", name = "mapGroup" },
        { kind = "half", name = "mapNum" },
        { kind = "half", name = "warpId" },
      },
      handler = "ScrCmd_addelevmenuitem",
      name = "addelevmenuitem",
      size = 8,
    },
    [178] = {
      args = {},
      handler = "ScrCmd_showelevmenu",
      name = "showelevmenu",
      size = 1,
    },
    [179] = {
      args = {
        { kind = "half", name = "count" },
      },
      handler = "ScrCmd_checkcoins",
      name = "checkcoins",
      size = 3,
    },
    [180] = {
      args = {
        { kind = "half", name = "count" },
      },
      handler = "ScrCmd_addcoins",
      name = "addcoins",
      size = 3,
    },
    [181] = {
      args = {
        { kind = "half", name = "count" },
      },
      handler = "ScrCmd_removecoins",
      name = "removecoins",
      size = 3,
    },
    [182] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "byte", name = "level" },
        { kind = "half", name = "item" },
      },
      handler = "ScrCmd_setwildbattle",
      name = "setwildbattle",
      size = 6,
    },
    [183] = {
      args = {},
      handler = "ScrCmd_dowildbattle",
      name = "dowildbattle",
      size = 1,
    },
    [184] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_setvaddress",
      name = "setvaddress",
      size = 5,
    },
    [185] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vgoto",
      name = "vgoto",
      size = 5,
    },
    [186] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vcall",
      name = "vcall",
      size = 5,
    },
    [187] = {
      args = {
        { kind = "byte", name = "byte" },
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vgoto_if",
      name = "vgoto_if",
      size = 6,
    },
    [188] = {
      args = {
        { kind = "byte", name = "byte" },
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vcall_if",
      name = "vcall_if",
      size = 6,
    },
    [189] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vmessage",
      name = "vmessage",
      size = 5,
    },
    [190] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vloadptr",
      name = "vloadptr",
      size = 5,
    },
    [191] = {
      args = {
        { kind = "byte", name = "byte" },
        { kind = "word", name = "pointer" },
      },
      handler = "ScrCmd_vbufferstring",
      name = "vbufferstring",
      size = 6,
    },
    [192] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_showcoinsbox",
      name = "showcoinsbox",
      size = 3,
    },
    [193] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_hidecoinsbox",
      name = "hidecoinsbox",
      size = 3,
    },
    [194] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      handler = "ScrCmd_updatecoinsbox",
      name = "updatecoinsbox",
      size = 3,
    },
    [195] = {
      args = {
        { kind = "byte", name = "stat" },
      },
      handler = "ScrCmd_incrementgamestat",
      name = "incrementgamestat",
      size = 2,
    },
    [196] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "warp" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      handler = "ScrCmd_setescapewarp",
      name = "setescapewarp",
      size = 8,
    },
    [197] = {
      args = {},
      handler = "ScrCmd_waitmoncry",
      name = "waitmoncry",
      size = 1,
    },
  },
  byName = {
    addcoins = 180,
    adddecoration = 75,
    addelevmenuitem = 177,
    additem = 68,
    addmoney = 144,
    addobject = 85,
    addobject_at = 86,
    addpcitem = 73,
    addvar = 23,
    animateflash = 154,
    applymovement = 79,
    applymovement_at = 80,
    braillemessage = 120,
    bufferdecorationname = 129,
    bufferitemname = 128,
    bufferleadmonspeciesname = 126,
    buffermovename = 130,
    buffernumberstring = 131,
    bufferpartymonnick = 127,
    bufferspeciesname = 125,
    bufferstdstring = 132,
    bufferstring = 133,
    call = 4,
    call_if = 7,
    callnative = 35,
    callstd = 9,
    callstd_if = 11,
    checkcoins = 179,
    checkdecor = 77,
    checkdecorspace = 78,
    checkflag = 43,
    checkitem = 71,
    checkitemspace = 70,
    checkitemtype = 72,
    checkmoney = 146,
    checkpartymove = 124,
    checkpcitem = 74,
    checkplayergender = 160,
    checktrainerflag = 96,
    choosecontestmon = 139,
    clearflag = 42,
    cleartrainerflag = 98,
    closedoor = 173,
    closemessage = 104,
    compare_addr_to_addr = 32,
    compare_addr_to_local = 30,
    compare_addr_to_value = 31,
    compare_local_to_addr = 29,
    compare_local_to_local = 27,
    compare_local_to_value = 28,
    compare_var_to_value = 33,
    compare_var_to_var = 34,
    contestlinktransfer = 142,
    copybyte = 21,
    copylocal = 20,
    copyvar = 25,
    createvobject = 170,
    delay = 40,
    dofieldeffect = 156,
    dotimebasedevents = 45,
    doweather = 165,
    dowildbattle = 183,
    drawbox = 114,
    drawboxtext = 116,
    ["end"] = 2,
    erasebox = 115,
    faceplayer = 90,
    fadedefaultbgm = 53,
    fadeinbgm = 56,
    fadenewbgm = 54,
    fadeoutbgm = 55,
    fadescreen = 151,
    fadescreenspeed = 152,
    getpartysize = 67,
    getplayerxy = 66,
    getpricereduction = 150,
    gettime = 46,
    giveegg = 122,
    givemon = 121,
    ["goto"] = 5,
    goto_if = 6,
    gotobeatenscript = 95,
    gotonative = 36,
    gotopostbattlescript = 94,
    gotoram = 12,
    gotostd = 8,
    gotostd_if = 10,
    hidecoinsbox = 193,
    hidemoneybox = 148,
    hidemonpic = 118,
    hideobjectat = 89,
    incrementgamestat = 195,
    initclock = 44,
    killscript = 13,
    loadbyte = 16,
    loadbytefromaddr = 18,
    loadword = 15,
    lock = 106,
    lockall = 105,
    message = 103,
    messageautoscroll = 155,
    moveobjectoffscreen = 100,
    multichoice = 111,
    multichoicedefault = 112,
    multichoicegrid = 113,
    nop = 0,
    nop1 = 1,
    opendoor = 172,
    playbgm = 51,
    playfanfare = 49,
    playmoncry = 161,
    playse = 47,
    playslotmachine = 137,
    pokemart = 134,
    pokemartdecoration = 135,
    pokemartdecoration2 = 136,
    random = 143,
    release = 108,
    releaseall = 107,
    removecoins = 181,
    removedecoration = 76,
    removeitem = 69,
    removemoney = 145,
    removeobject = 83,
    removeobject_at = 84,
    resetobjectpriority = 169,
    resetweather = 163,
    ["return"] = 3,
    savebgm = 52,
    setberrytree = 138,
    setdivewarp = 64,
    setdoorclosed = 176,
    setdooropen = 175,
    setdynamicwarp = 63,
    setescapewarp = 196,
    setfieldeffectargument = 157,
    setflag = 41,
    setflashradius = 153,
    setholewarp = 65,
    setmaplayoutindex = 167,
    setmetatile = 162,
    setmonmove = 123,
    setmysteryeventstatus = 14,
    setobjectmovementtype = 101,
    setobjectpriority = 168,
    setobjectxy = 87,
    setobjectxyperm = 99,
    setorcopyvar = 26,
    setptrbyte = 19,
    setrespawn = 159,
    setstepcallback = 166,
    settrainerflag = 97,
    setvaddress = 184,
    setvar = 22,
    setwarp = 62,
    setweather = 164,
    setwildbattle = 182,
    showcoinsbox = 192,
    showcontestresults = 141,
    showcontestwinner = 119,
    showelevmenu = 178,
    showmoneybox = 147,
    showmonpic = 117,
    showobjectat = 88,
    special = 37,
    specialvar = 38,
    startcontest = 140,
    subvar = 24,
    trainerbattle = 92,
    trainerbattlebegin = 93,
    turnobject = 91,
    turnvobject = 171,
    updatecoinsbox = 194,
    updatemoneybox = 149,
    vbufferstring = 191,
    vcall = 186,
    vcall_if = 188,
    vgoto = 185,
    vgoto_if = 187,
    vloadptr = 190,
    vmessage = 189,
    waitbuttonpress = 109,
    waitdooranim = 174,
    waitfanfare = 50,
    waitfieldeffect = 158,
    waitmessage = 102,
    waitmoncry = 197,
    waitmovement = 81,
    waitmovement_at = 82,
    waitse = 48,
    waitstate = 39,
    warp = 57,
    warpdoor = 59,
    warphole = 60,
    warpsilent = 58,
    warpteleport = 61,
    writebytetoaddr = 17,
    yesnobox = 110,
  },
  count = 198,
}
