local A = {}
local F = {}
A.sAffineAnim_AirWaveCrescent = {{f=0,d=3},{f=0,d=3,h=1},{f=0,d=3,v=1},{f=0,d=3,v=1,h=1},{j=0}}
A.sAngelSpriteAnimCmds = {{f=0,d=24},{e=1}}
A.sAnim_AcidPoisonDroplet = {{f=4,d=1},{e=1}}
A.sAnim_AuroraBeamRing_0 = {{f=0,d=1},{e=1}}
A.sAnim_AuroraBeamRing_1 = {{f=4,d=1},{e=1}}
A.sAnim_BasicFire = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{f=64,d=4},{j=0}}
A.sAnim_BentSpoon_0 = {{f=8,d=60,h=1},{f=16,d=5,h=1},{f=8,d=5,h=1},{f=0,d=5,h=1},{f=8,d=22,h=1},{l=0},{f=16,d=5,h=1},{f=8,d=5,h=1},{f=0,d=5,h=1},{f=8,d=5,h=1},{l=1},{f=8,d=22,h=1},{f=24,d=3,h=1},{f=32,d=3,h=1},{f=40,d=22,h=1},{e=1}}
A.sAnim_BentSpoon_1 = {{f=8,d=60},{f=16,d=5},{f=8,d=5},{f=0,d=5},{f=8,d=22},{l=0},{f=16,d=5},{f=8,d=5},{f=0,d=5},{f=8,d=5},{l=1},{f=8,d=22},{f=24,d=3},{f=32,d=3},{f=40,d=22},{e=1}}
A.sAnim_BlizzardIceCrystal = {{f=8,d=1},{e=1}}
A.sAnim_BouncingMusicNote = {{f=4,d=1},{e=1}}
A.sAnim_BubbleBurst = {{f=0,d=10},{f=4,d=10},{f=8,d=10},{f=12,d=10},{f=16,d=26},{f=16,d=5},{f=20,d=5},{f=24,d=15},{e=1}}
A.sAnim_BubbleBurst_Flipped = {{f=0,d=10,h=1},{f=4,d=10,h=1},{f=8,d=10,h=1},{f=12,d=10,h=1},{f=16,d=26,h=1},{f=16,d=5,h=1},{f=20,d=5,h=1},{f=24,d=15,h=1},{e=1}}
A.sAnim_CirclingMusicNote_BeamedEighth = {{f=4,d=1},{e=1}}
A.sAnim_CirclingMusicNote_BeamedEighth_Flipped = {{f=4,d=1,v=1},{e=1}}
A.sAnim_CirclingMusicNote_Eighth = {{f=0,d=1},{e=1}}
A.sAnim_CirclingMusicNote_EighthRest = {{f=20,d=1},{e=1}}
A.sAnim_CirclingMusicNote_Eighth_Flipped = {{f=0,d=1,v=1},{e=1}}
A.sAnim_CirclingMusicNote_Quarter = {{f=12,d=1},{e=1}}
A.sAnim_CirclingMusicNote_QuarterRest = {{f=16,d=1},{e=1}}
A.sAnim_CirclingMusicNote_Quarter_Flipped = {{f=12,d=1,v=1},{e=1}}
A.sAnim_CirclingMusicNote_SlantedBeamedEighth = {{f=8,d=1},{e=1}}
A.sAnim_CirclingMusicNote_SlantedBeamedEighth_Flipped = {{f=8,d=1,v=1},{e=1}}
A.sAnim_CirclingSparkle = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=64,d=3},{j=0}}
A.sAnim_ClawSlash_0 = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{f=64,d=4},{e=1}}
A.sAnim_ClawSlash_1 = {{f=0,d=4,h=1},{f=16,d=4,h=1},{f=32,d=4,h=1},{f=48,d=4,h=1},{f=64,d=4,h=1},{e=1}}
A.sAnim_Cloud = {{f=0,d=8},{f=8,d=8},{j=0}}
A.sAnim_ConfusionDuck_0 = {{f=0,d=8},{f=4,d=8},{f=0,d=8,h=1},{f=8,d=8},{j=0}}
A.sAnim_ConfusionDuck_1 = {{f=0,d=8,h=1},{f=4,d=8},{f=0,d=8},{f=8,d=8},{j=0}}
A.sAnim_ConstrictBinding = {{f=0,d=4},{f=32,d=4},{f=64,d=4},{f=96,d=4},{e=1}}
A.sAnim_ConstrictBinding_Flipped = {{f=0,d=4,h=1},{f=32,d=4,h=1},{f=64,d=4,h=1},{f=96,d=4,h=1},{e=1}}
A.sAnim_DragonBreathFire_0 = {{f=16,d=3},{f=32,d=3},{f=48,d=3},{j=0}}
A.sAnim_DragonBreathFire_1 = {{f=16,d=3,v=1,h=1},{f=32,d=3,v=1,h=1},{f=48,d=3,v=1,h=1},{j=0}}
A.sAnim_DragonRageFire = {{f=16,d=3},{f=32,d=3},{f=48,d=3},{j=0}}
A.sAnim_DragonRageFirePlume = {{f=0,d=5},{f=16,d=5},{f=32,d=5},{f=48,d=5},{f=64,d=5},{e=1}}
A.sAnim_ElectricChargingParticles_0 = {{f=3,d=1},{f=2,d=1},{f=1,d=1},{f=0,d=1},{e=1}}
A.sAnim_ElectricChargingParticles_1 = {{f=0,d=5},{f=1,d=5},{f=2,d=5},{f=3,d=5},{e=1}}
A.sAnim_ElectricPuff = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{e=1}}
A.sAnim_FallingFeather_0 = {{f=0,d=0},{e=1}}
A.sAnim_FallingFeather_1 = {{f=16,d=0,h=1},{e=1}}
A.sAnim_FireBlastCross = {{f=32,d=6},{f=48,d=6},{j=0}}
A.sAnim_FirePlume = {{f=0,d=5},{f=16,d=5},{f=32,d=5},{f=48,d=5},{f=64,d=5},{j=0}}
A.sAnim_FireSpiralSpread_0 = {{f=16,d=4},{f=32,d=4},{f=48,d=4},{j=0}}
A.sAnim_FireSpiralSpread_1 = {{f=16,d=4,v=1,h=1},{f=32,d=4,v=1,h=1},{f=48,d=4,v=1,h=1},{j=0}}
A.sAnim_Fist = {{f=0,d=1},{e=1}}
A.sAnim_FlamethrowerFlame = {{f=16,d=2},{f=32,d=2},{f=48,d=2},{j=0}}
A.sAnim_FlickeringImpact_0 = {{f=0,d=5},{j=0}}
A.sAnim_FlickeringImpact_1 = {{f=0,d=5},{j=0}}
A.sAnim_FlickeringImpact_2 = {{f=0,d=5},{j=0}}
A.sAnim_FlickeringOrb = {{f=0,d=3},{f=4,d=3},{f=8,d=3},{f=12,d=3},{j=0}}
A.sAnim_FlickeringShrinkOrb = {{f=0,d=15},{j=0}}
A.sAnim_FlyingRock_0 = {{f=32,d=1},{e=1}}
A.sAnim_FlyingRock_1 = {{f=48,d=1},{e=1}}
A.sAnim_FlyingRock_2 = {{f=64,d=1},{e=1}}
A.sAnim_FootTall = {{f=32,d=1},{e=1}}
A.sAnim_FootWide = {{f=16,d=1},{e=1}}
A.sAnim_FurySwipes = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{e=1}}
A.sAnim_FurySwipes_Flipped = {{f=0,d=4,h=1},{f=16,d=4,h=1},{f=32,d=4,h=1},{f=48,d=4,h=1},{e=1}}
A.sAnim_GrudgeFlame = {{f=0,d=4},{f=8,d=4},{f=16,d=4},{f=24,d=4},{j=0}}
A.sAnim_HandLeft = {{f=48,d=1},{e=1}}
A.sAnim_HandRight = {{f=48,d=1,h=1},{e=1}}
A.sAnim_IceBallChunk_0 = {{f=0,d=1},{e=1}}
A.sAnim_IceBallChunk_1 = {{f=16,d=4},{f=32,d=4},{f=48,d=4},{f=64,d=4},{e=1}}
A.sAnim_IceCrystalLarge = {{f=4,d=1},{e=1}}
A.sAnim_IceCrystalLargeChunk = {{f=0,d=1},{e=1}}
A.sAnim_IceCrystalSmall = {{f=6,d=1},{e=1}}
A.sAnim_IceGroundSpike = {{f=0,d=5},{f=2,d=5},{f=4,d=5},{f=6,d=5},{f=4,d=5},{f=2,d=5},{f=0,d=5},{e=1}}
A.sAnim_LargeFlame = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=64,d=3},{f=80,d=3},{f=96,d=3},{f=112,d=3},{j=0}}
A.sAnim_Lick = {{f=0,d=2},{f=8,d=2},{f=16,d=2},{f=24,d=2},{f=32,d=2},{e=1}}
A.sAnim_Lightning = {{f=0,d=5},{f=16,d=5},{f=32,d=8},{f=48,d=5},{f=64,d=5},{e=1}}
A.sAnim_LuxuryPremierBall = {{f=6,d=4},{f=7,d=4},{j=0}}
A.sAnim_MasterBall = {{f=3,d=1},{e=1}}
A.sAnim_MudSlapMud = {{f=1,d=1},{e=1}}
A.sAnim_NestBall = {{f=5,d=1},{e=1}}
A.sAnim_NetDiveBall = {{f=4,d=1},{e=1}}
A.sAnim_OutrageOverheatFire_0 = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{f=64,d=4},{j=0}}
A.sAnim_PoisonProjectile = {{f=0,d=1},{e=1}}
A.sAnim_QuestionMark = {{f=0,d=6},{f=16,d=6},{f=32,d=6},{f=48,d=6},{f=64,d=6},{f=80,d=6},{f=96,d=18},{e=1}}
A.sAnim_RainDrop = {{f=0,d=2},{f=8,d=2},{f=16,d=2},{f=24,d=6},{f=32,d=2},{f=40,d=2},{f=48,d=2},{e=1}}
A.sAnim_ReflectSparkle = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=64,d=3},{e=1}}
A.sAnim_RegularBall = {{f=0,d=1},{f=1,d=1},{f=2,d=1},{f=0,d=1,h=1},{f=2,d=1},{f=1,d=1},{j=0}}
A.sAnim_RevengeBigScratch_0 = {{f=0,d=6},{f=64,d=6},{e=1}}
A.sAnim_RevengeBigScratch_1 = {{f=0,d=6,v=1,h=1},{f=64,d=6,v=1,h=1},{e=1}}
A.sAnim_RevengeBigScratch_2 = {{f=0,d=6,h=1},{f=64,d=6,h=1},{e=1}}
A.sAnim_RevengeSmallScratch_0 = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{e=1}}
A.sAnim_RevengeSmallScratch_1 = {{f=0,d=4,v=1},{f=16,d=4,v=1},{f=32,d=4,v=1},{e=1}}
A.sAnim_RevengeSmallScratch_2 = {{f=0,d=4,h=1},{f=16,d=4,h=1},{f=32,d=4,h=1},{e=1}}
A.sAnim_Rock_Big = {{f=32,d=1},{e=1}}
A.sAnim_Rock_Bigger = {{f=16,d=1},{e=1}}
A.sAnim_Rock_Biggest = {{f=0,d=1},{e=1}}
A.sAnim_Rock_Small = {{f=48,d=1},{e=1}}
A.sAnim_Rock_Smaller = {{f=64,d=1},{e=1}}
A.sAnim_Rock_Smallest = {{f=80,d=1},{e=1}}
A.sAnim_SlidingHit = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{f=64,d=5},{e=1}}
A.sAnim_SludgeBombHit = {{f=8,d=1},{e=1}}
A.sAnim_SmallBubblePair = {{f=12,d=6},{f=13,d=6},{j=0}}
A.sAnim_SmallExplosion = {{f=0,d=9},{f=16,d=3},{f=32,d=3},{f=48,d=3},{e=1}}
A.sAnim_SmokescreenImpact_0 = {{f=0,d=4},{f=4,d=4},{f=8,d=4},{e=1}}
A.sAnim_SmokescreenImpact_1 = {{f=0,d=4,h=1},{f=4,d=4,h=1},{f=8,d=4,h=1},{e=1}}
A.sAnim_SmokescreenImpact_2 = {{f=0,d=4,v=1},{f=4,d=4,v=1},{f=8,d=4,v=1},{e=1}}
A.sAnim_SmokescreenImpact_3 = {{f=0,d=4,h=1,v=1},{f=4,d=4,h=1,v=1},{f=8,d=4,h=1,v=1},{e=1}}
A.sAnim_Snowball = {{f=7,d=1},{e=1}}
A.sAnim_SpecialScreenSparkle = {{f=0,d=5},{f=4,d=5},{f=8,d=5},{f=12,d=5},{e=1}}
A.sAnim_SpinningSparkle = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=64,d=3},{e=1}}
A.sAnim_ThunderboltOrb = {{f=0,d=6},{f=16,d=6},{f=32,d=6},{j=0}}
A.sAnim_ToxicBubble = {{f=0,d=5},{f=8,d=5},{f=16,d=5},{f=24,d=5},{e=1}}
A.sAnim_UltraRepeatTimerBall = {{f=7,d=4},{e=1}}
A.sAnim_Unused = {{f=0,d=5,h=1},{f=1,d=5,h=1},{j=0}}
A.sAnim_UnusedCirclingShock = {{f=0,d=5},{f=16,d=5},{f=32,d=5},{f=48,d=5},{f=64,d=5},{f=80,d=5},{j=0}}
A.sAnim_UnusedSmallEmber = {{f=16,d=6},{f=32,d=6},{f=48,d=6},{j=0}}
A.sAnim_VoltTackleBolt_0 = {{f=0,d=3},{e=1}}
A.sAnim_VoltTackleBolt_1 = {{f=2,d=3},{e=1}}
A.sAnim_VoltTackleBolt_2 = {{f=4,d=3},{e=1}}
A.sAnim_VoltTackleBolt_3 = {{f=6,d=3},{e=1}}
A.sAnim_WaterBubble = {{f=0,d=1},{e=1}}
A.sAnim_WaterBubbleProjectile = {{f=0,d=1},{f=4,d=5},{f=8,d=5},{e=1}}
A.sAnim_WaterGunDroplet = {{f=4,d=1},{e=1}}
A.sAnim_WaterMudOrb = {{f=0,d=1},{f=4,d=1},{f=8,d=1},{f=12,d=1},{j=0}}
A.sAnim_WaterPulseBubble_0 = {{f=8,d=1},{e=1}}
A.sAnim_WaterPulseBubble_1 = {{f=9,d=1},{e=1}}
A.sAnim_WeatherBallNormal = {{f=0,d=3},{j=0}}
A.sAnim_WeatherBallWaterDown = {{f=4,d=1},{e=1}}
A.sAnim_Whip = {{f=64,d=3},{f=80,d=3},{f=96,d=3},{f=112,d=6},{e=1}}
A.sAnim_Whip_Flipped = {{f=64,d=3,h=1},{f=80,d=3,h=1},{f=96,d=3,h=1},{f=112,d=6,h=1},{e=1}}
A.sAnim_WhirlwindLines = {{f=0,d=1},{f=8,d=1},{f=16,d=1},{f=8,d=1,h=1},{f=0,d=1,h=1},{e=1}}
A.sAnim_WillOWispFire = {{f=0,d=5},{f=16,d=5},{f=32,d=5},{f=48,d=5},{j=0}}
A.sAnim_WillOWispOrb_0 = {{f=0,d=5},{f=4,d=5},{f=8,d=5},{f=12,d=5},{j=0}}
A.sAnim_WillOWispOrb_1 = {{f=16,d=5},{e=1}}
A.sAnim_WillOWispOrb_2 = {{f=20,d=5},{e=1}}
A.sAnim_WillOWispOrb_3 = {{f=20,d=5},{e=1}}
A.sBellAnimCmds = {{f=0,d=6},{f=16,d=6},{f=32,d=15},{f=16,d=6},{f=0,d=6},{f=16,d=6,h=1},{f=32,d=15,h=1},{f=16,d=6,h=1},{f=0,d=6},{f=16,d=6},{f=32,d=15},{f=16,d=6},{f=0,d=6},{e=1}}
A.sBreathPuffAnimCmds1 = {{f=0,d=4,h=1},{f=4,d=40,h=1},{f=8,d=4,h=1},{f=12,d=4,h=1},{e=1}}
A.sBreathPuffAnimCmds2 = {{f=0,d=4},{f=4,d=40},{f=8,d=4},{f=12,d=4},{e=1}}
A.sCoinAnimCmds = {{f=8,d=1},{e=1}}
A.sConversion2AnimCmds = {{f=0,d=5},{f=1,d=5},{f=2,d=5},{f=3,d=5},{e=1}}
A.sConversionAnimCmds = {{f=3,d=5},{f=2,d=5},{f=1,d=5},{f=0,d=5},{e=1}}
A.sCuttingSliceAnimCmds = {{f=0,d=5},{f=16,d=5},{f=32,d=5},{f=48,d=5},{e=1}}
A.sDevilAnimCmds1 = {{f=0,d=3},{j=0}}
A.sDevilAnimCmds2 = {{f=16,d=3},{j=0}}
A.sEclipsingOrbAnimCmds = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=32,d=3,h=1},{f=16,d=3,h=1},{f=0,d=3,h=1},{l=1},{e=1}}
A.sEndureEnergyAnimCmds = {{f=0,d=4},{f=8,d=12},{f=16,d=4},{f=24,d=4},{e=1}}
A.sExplosionAnimCmds = {{f=0,d=5},{f=16,d=5},{f=32,d=5},{f=48,d=5},{e=1}}
A.sEyeSparkleAnimCmds = {{f=0,d=4},{f=4,d=4},{f=8,d=4},{f=4,d=4},{f=0,d=4},{e=1}}
A.sFallingBagAnimCmds = {{f=0,d=30},{e=1}}
A.sFangAnimCmds = {{f=0,d=8},{f=16,d=16},{f=32,d=4},{f=48,d=4},{e=1}}
A.sGrantingStarsAnimCmds = {{f=0,d=7},{f=16,d=7},{f=32,d=7},{f=48,d=7},{f=64,d=7},{f=80,d=7},{f=96,d=7},{f=112,d=7},{j=0}}
A.sGreenStarAnimCmds1 = {{f=0,d=6},{f=4,d=6},{j=0}}
A.sGreenStarAnimCmds2 = {{f=8,d=6},{e=1}}
A.sGreenStarAnimCmds3 = {{f=12,d=6},{e=1}}
A.sGuillotineAnimCmds1 = {{f=0,d=2},{f=16,d=2},{f=32,d=1},{e=1}}
A.sGuillotineAnimCmds2 = {{f=0,d=2,v=1,h=1},{f=16,d=2,v=1,h=1},{f=32,d=1,v=1,h=1},{e=1}}
A.sHealingBlueStarAnimCmds = {{f=0,d=2},{f=16,d=2},{f=32,d=2},{f=48,d=3},{f=64,d=5},{f=80,d=3},{f=96,d=2},{f=0,d=2},{e=1}}
A.sIngrainOrbAnimCmds = {{f=3,d=3},{f=0,d=5},{j=0}}
A.sIngrainRootAnimCmds1 = {{f=0,d=7},{f=16,d=7},{f=32,d=7},{f=48,d=7},{e=1}}
A.sIngrainRootAnimCmds2 = {{f=0,d=7,h=1},{f=16,d=7,h=1},{f=32,d=7,h=1},{f=48,d=7,h=1},{e=1}}
A.sIngrainRootAnimCmds3 = {{f=0,d=7},{f=16,d=7},{f=32,d=7},{e=1}}
A.sIngrainRootAnimCmds4 = {{f=0,d=7,h=1},{f=16,d=7,h=1},{f=32,d=7,h=1},{e=1}}
A.sKinesisZapEnergyAnimCmds = {{f=0,d=3,h=1},{f=8,d=3,h=1},{f=16,d=3,h=1},{f=24,d=3,h=1},{f=32,d=3,h=1},{f=40,d=3,h=1},{f=48,d=3,h=1},{l=1},{e=1}}
A.sKnockOffStrikeAnimCmds = {{f=0,d=4},{f=64,d=4},{e=1}}
A.sLeafBladeAnimCmds1 = {{f=28,d=1},{e=1}}
A.sLeafBladeAnimCmds2 = {{f=32,d=1},{e=1}}
A.sLeafBladeAnimCmds3 = {{f=20,d=1},{e=1}}
A.sLeafBladeAnimCmds4 = {{f=28,d=1,h=1},{e=1}}
A.sLeafBladeAnimCmds5 = {{f=16,d=1},{e=1}}
A.sLeafBladeAnimCmds6 = {{f=16,d=1,h=1},{e=1}}
A.sLeafBladeAnimCmds7 = {{f=28,d=1},{e=1}}
A.sLeechSeedAnimCmds1 = {{f=0,d=1},{e=1}}
A.sLeechSeedAnimCmds2 = {{f=4,d=7},{f=8,d=7},{j=0}}
A.sLeerAnimCmds = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=64,d=3},{e=1}}
A.sLetterZAnimCmds = {{f=0,d=3},{e=1}}
A.sMetronomeThroughtBubbleAnimCmds1 = {{f=0,d=2,h=1},{f=16,d=2,h=1},{f=32,d=2,h=1},{f=48,d=2,h=1},{e=1}}
A.sMetronomeThroughtBubbleAnimCmds2 = {{f=0,d=2},{f=16,d=2},{f=32,d=2},{f=48,d=2},{e=1}}
A.sMetronomeThroughtBubbleAnimCmds3 = {{f=48,d=2,h=1},{f=32,d=2,h=1},{f=16,d=2,h=1},{f=0,d=2,h=1},{e=1}}
A.sMetronomeThroughtBubbleAnimCmds4 = {{f=48,d=2},{f=32,d=2},{f=16,d=2},{f=0,d=2},{e=1}}
A.sMoonlightSparkleAnimCmds = {{f=0,d=8},{f=4,d=8},{f=8,d=8},{f=12,d=8},{j=0}}
A.sMovementWavesAnimCmds1 = {{f=0,d=8},{f=16,d=8},{f=32,d=8},{f=16,d=8},{e=1}}
A.sMovementWavesAnimCmds2 = {{f=16,d=8,h=1},{f=32,d=8,h=1},{f=16,d=8,h=1},{f=0,d=8,h=1},{e=1}}
A.sOctazookaAnimCmds = {{f=0,d=3},{f=16,d=3},{f=32,d=3},{f=48,d=3},{f=64,d=3},{e=1}}
A.sOpeningEyeAnimCmds = {{f=0,d=40},{f=16,d=8},{f=32,d=40},{e=1}}
A.sPainSplitAnimCmds = {{f=0,d=5},{f=4,d=9},{f=8,d=5},{e=1}}
A.sPetalDanceBigFlowerAnimCmds = {{f=0,d=1},{e=1}}
A.sPetalDanceSmallFlowerAnimCmds = {{f=4,d=1},{e=1}}
A.sPowderParticlesAnimCmds = {{f=0,d=5},{f=2,d=5},{f=4,d=5},{f=6,d=5},{f=8,d=5},{f=10,d=5},{f=12,d=5},{f=14,d=5},{j=0}}
A.sPowerAbsorptionOrbAnimCmds = {{f=8,d=1},{e=1}}
A.sPresentHealParticleAnimCmds = {{f=0,d=4},{f=4,d=4},{f=8,d=4},{f=12,d=4},{e=1}}
A.sRapidSpinAnimCmds = {{f=0,d=2},{f=8,d=2},{f=16,d=2},{j=0}}
A.sRazorLeafCutterAnimCmds = {{f=0,d=3},{f=0,d=3,h=1},{f=0,d=3,v=1,h=1},{f=0,d=3,v=1},{j=0}}
A.sRazorLeafParticleAnimCmds1 = {{f=0,d=5},{f=4,d=5},{f=8,d=5},{f=12,d=5},{f=16,d=5},{f=20,d=5},{f=16,d=5},{f=12,d=5},{f=8,d=5},{f=4,d=5},{j=0}}
A.sRazorLeafParticleAnimCmds2 = {{f=24,d=5},{f=28,d=5},{f=32,d=5},{e=1}}
A.sRoarNoiseLineAnimCmds1 = {{f=0,d=3},{f=16,d=3},{j=0}}
A.sRoarNoiseLineAnimCmds2 = {{f=32,d=3},{f=48,d=3},{j=0}}
A.sScratchAnimCmds = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{f=64,d=4},{e=1}}
A.sSharpenSphereAnimCmds = {{f=0,d=18},{f=0,d=6},{f=16,d=18},{f=0,d=6},{f=16,d=6},{f=32,d=18},{f=16,d=6},{f=32,d=6},{f=48,d=18},{f=32,d=6},{f=48,d=6},{f=64,d=18},{f=48,d=6},{f=64,d=54},{e=1}}
A.sSlashSliceAnimCmds1 = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=48,d=4},{e=1}}
A.sSlashSliceAnimCmds2 = {{f=48,d=4},{e=1}}
A.sSleepLetterZAnimCmds = {{f=0,d=40},{e=1}}
A.sSolarBeamBigOrbAnimCmds1 = {{f=0,d=1},{e=1}}
A.sSolarBeamBigOrbAnimCmds2 = {{f=1,d=1},{e=1}}
A.sSolarBeamBigOrbAnimCmds3 = {{f=2,d=1},{e=1}}
A.sSolarBeamBigOrbAnimCmds4 = {{f=3,d=1},{e=1}}
A.sSolarBeamBigOrbAnimCmds5 = {{f=4,d=1},{e=1}}
A.sSolarBeamBigOrbAnimCmds6 = {{f=5,d=1},{e=1}}
A.sSolarBeamBigOrbAnimCmds7 = {{f=6,d=1},{e=1}}
A.sSolarBeamSmallOrbAnimCms = {{f=7,d=1},{e=1}}
A.sSpeedDustAnimCmds = {{f=0,d=3},{f=4,d=3},{f=8,d=3},{f=4,d=3},{f=0,d=3},{e=1}}
A.sSporeParticleAnimCmds1 = {{f=0,d=1},{e=1}}
A.sSporeParticleAnimCmds2 = {{f=4,d=7},{e=1}}
A.sSpriteAnim_SafariRock_0 = {{f=64,d=1},{e=1}}
A.sSuperFangAnimCmds = {{f=0,d=2},{f=16,d=2},{f=32,d=2},{f=48,d=2},{e=1}}
A.sSweetScentPetalAnimCmds1 = {{f=0,d=8},{f=1,d=8},{f=2,d=8},{f=3,d=8},{f=3,d=8,v=1},{f=2,d=8,v=1},{f=0,d=8,v=1},{f=1,d=8,v=1},{j=0}}
A.sSweetScentPetalAnimCmds2 = {{f=0,d=8,h=1},{f=1,d=8,h=1},{f=2,d=8,h=1},{f=3,d=8,h=1},{f=3,d=8,v=1,h=1},{f=2,d=8,v=1,h=1},{f=0,d=8,v=1,h=1},{f=1,d=8,v=1,h=1},{j=0}}
A.sSweetScentPetalAnimCmds3 = {{f=0,d=8},{e=1}}
A.sTauntFingerAnimCmds1 = {{f=0,d=1},{e=1}}
A.sTauntFingerAnimCmds2 = {{f=0,d=1,h=1},{e=1}}
A.sTauntFingerAnimCmds3 = {{f=0,d=4},{f=16,d=4},{f=32,d=4},{f=16,d=4},{f=0,d=4},{f=16,d=4},{f=32,d=4},{e=1}}
A.sTauntFingerAnimCmds4 = {{f=0,d=4,h=1},{f=16,d=4,h=1},{f=32,d=4,h=1},{f=16,d=4,h=1},{f=0,d=4,h=1},{f=16,d=4,h=1},{f=32,d=4,h=1},{e=1}}
A.sTriAttackTriangleAnimCmds = {{f=0,d=8},{e=1}}
A.sViceGripAnimCmds1 = {{f=0,d=3},{f=16,d=3},{f=32,d=20},{e=1}}
A.sViceGripAnimCmds2 = {{f=0,d=3,v=1,h=1},{f=16,d=3,v=1,h=1},{f=32,d=20,v=1,h=1},{e=1}}
A.sWavyMusicNotesAnimCmds1 = {{f=0,d=10},{e=1}}
A.sWavyMusicNotesAnimCmds2 = {{f=4,d=10},{e=1}}
A.sWavyMusicNotesAnimCmds3 = {{f=8,d=41},{e=1}}
A.sWavyMusicNotesAnimCmds4 = {{f=12,d=10},{e=1}}
A.sWavyMusicNotesAnimCmds5 = {{f=16,d=10},{e=1}}
A.sWavyMusicNotesAnimCmds6 = {{f=20,d=10},{e=1}}
A.sWavyMusicNotesAnimCmds7 = {{f=0,d=10,v=1},{e=1}}
A.sWavyMusicNotesAnimCmds8 = {{f=4,d=10,v=1},{e=1}}
F.DefenseCurlDeformMonAffineAnimCmds = {{x=-12,y=20,r=0,d=8},{x=12,y=-20,r=0,d=8},{l=2},{e=1}}
F.sAbsorptionOrbAffineAnimCmds = {{x=-5,y=-5,r=0,d=1},{j=0}}
F.sAffineAnim_AcidPoisonDroplet = {{x=-16,y=16,r=0,d=6},{x=16,y=-16,r=0,d=6},{j=0}}
F.sAffineAnim_AuroraBeamRing = {{x=0,y=0,r=0,d=1},{x=96,y=96,r=0,d=1},{e=1}}
F.sAffineAnim_BasicRock_0 = {{x=0,y=0,r=-5,d=5},{j=0}}
F.sAffineAnim_BasicRock_1 = {{x=0,y=0,r=5,d=5},{j=0}}
F.sAffineAnim_Bite_0 = {{x=0,y=0,r=0,d=1},{e=1}}
F.sAffineAnim_Bite_1 = {{x=0,y=0,r=32,d=1},{e=1}}
F.sAffineAnim_Bite_2 = {{x=0,y=0,r=64,d=1},{e=1}}
F.sAffineAnim_Bite_3 = {{x=0,y=0,r=96,d=1},{e=1}}
F.sAffineAnim_Bite_4 = {{x=0,y=0,r=-128,d=1},{e=1}}
F.sAffineAnim_Bite_5 = {{x=0,y=0,r=-96,d=1},{e=1}}
F.sAffineAnim_Bite_6 = {{x=0,y=0,r=-64,d=1},{e=1}}
F.sAffineAnim_Bite_7 = {{x=0,y=0,r=-32,d=1},{e=1}}
F.sAffineAnim_Bonemerang = {{x=0,y=0,r=15,d=1},{j=0}}
F.sAffineAnim_BounceBallLand = {{x=160,y=256,r=0,d=0},{e=1}}
F.sAffineAnim_BounceBallShrink = {{x=16,y=256,r=0,d=0},{x=40,y=0,r=0,d=6},{x=0,y=-32,r=0,d=5},{x=-20,y=0,r=0,d=7},{x=-20,y=-20,r=0,d=5},{e=1}}
F.sAffineAnim_Bubble = {{x=156,y=156,r=0,d=0},{x=5,y=5,r=0,d=20},{e=1}}
F.sAffineAnim_ConfuseRayBallBounce = {{x=30,y=30,r=10,d=5},{x=-30,y=-30,r=10,d=5},{j=0}}
F.sAffineAnim_ConstrictBinding = {{x=256,y=256,r=0,d=0},{x=-11,y=0,r=0,d=6},{x=11,y=0,r=0,d=6},{e=1}}
F.sAffineAnim_ConstrictBinding_Flipped = {{x=-256,y=256,r=0,d=0},{x=11,y=0,r=0,d=6},{x=-11,y=0,r=0,d=6},{e=1}}
F.sAffineAnim_DiveBall = {{x=16,y=256,r=0,d=0},{x=40,y=0,r=0,d=6},{x=0,y=-32,r=0,d=5},{x=-16,y=32,r=0,d=10},{e=1}}
F.sAffineAnim_DragonBreathFire_0 = {{x=80,y=80,r=127,d=0},{x=13,y=13,r=0,d=100},{e=1}}
F.sAffineAnim_DragonBreathFire_1 = {{x=80,y=80,r=0,d=0},{x=13,y=13,r=0,d=100},{e=1}}
F.sAffineAnim_DragonRageFire_0 = {{x=100,y=100,r=127,d=1},{e=1}}
F.sAffineAnim_DragonRageFire_1 = {{x=100,y=100,r=0,d=1},{e=1}}
F.sAffineAnim_FlashingSpark = {{x=0,y=0,r=20,d=1},{j=0}}
F.sAffineAnim_FlickeringPunch_Normal = {{x=256,y=256,r=0,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_TurnedBottomLeft = {{x=256,y=256,r=96,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_TurnedBottomRight = {{x=256,y=256,r=-96,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_TurnedLeft = {{x=256,y=256,r=64,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_TurnedRight = {{x=256,y=256,r=-64,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_TurnedTopLeft = {{x=256,y=256,r=32,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_TurnedTopRight = {{x=256,y=256,r=-32,d=0},{e=1}}
F.sAffineAnim_FlickeringPunch_UpsideDown = {{x=256,y=256,r=-128,d=0},{e=1}}
F.sAffineAnim_FlickeringShrinkOrb = {{x=96,y=96,r=0,d=0},{x=2,y=2,r=0,d=1},{j=1}}
F.sAffineAnim_FlyBallAttack_0 = {{x=0,y=0,r=50,d=1},{e=1}}
F.sAffineAnim_FlyBallAttack_1 = {{x=0,y=0,r=-40,d=1},{e=1}}
F.sAffineAnim_FlyBallUp = {{x=16,y=256,r=0,d=0},{x=40,y=0,r=0,d=6},{x=0,y=-32,r=0,d=5},{x=-16,y=32,r=0,d=10},{e=1}}
F.sAffineAnim_FocusPunchFist = {{x=512,y=512,r=0,d=0},{x=-32,y=-32,r=0,d=8},{e=1}}
F.sAffineAnim_GrowingElectricOrb_0 = {{x=16,y=16,r=0,d=0},{x=4,y=4,r=0,d=60},{x=256,y=256,r=0,d=0},{l=0},{x=-4,y=-4,r=0,d=5},{x=4,y=4,r=0,d=5},{l=10},{e=1}}
F.sAffineAnim_GrowingElectricOrb_1 = {{x=16,y=16,r=0,d=0},{x=8,y=8,r=0,d=30},{x=256,y=256,r=0,d=0},{x=-4,y=-4,r=0,d=5},{x=4,y=4,r=0,d=5},{j=3}}
F.sAffineAnim_GrowingElectricOrb_2 = {{x=16,y=16,r=0,d=0},{x=8,y=8,r=0,d=30},{x=-8,y=-8,r=0,d=30},{e=1}}
F.sAffineAnim_GustToTarget = {{x=16,y=256,r=0,d=0},{x=10,y=0,r=0,d=24},{e=1}}
F.sAffineAnim_HailParticle_0 = {{x=256,y=256,r=0,d=0},{e=1}}
F.sAffineAnim_HailParticle_1 = {{x=240,y=240,r=0,d=0},{e=1}}
F.sAffineAnim_HailParticle_2 = {{x=224,y=224,r=0,d=0},{e=1}}
F.sAffineAnim_HitSplat_0 = {{x=0,y=0,r=0,d=8},{e=1}}
F.sAffineAnim_HitSplat_1 = {{x=216,y=216,r=0,d=0},{x=0,y=0,r=0,d=8},{e=1}}
F.sAffineAnim_HitSplat_2 = {{x=176,y=176,r=0,d=0},{x=0,y=0,r=0,d=8},{e=1}}
F.sAffineAnim_HitSplat_3 = {{x=128,y=128,r=0,d=0},{x=0,y=0,r=0,d=8},{e=1}}
F.sAffineAnim_HydroCannonBeam = {{x=336,y=336,r=0,d=0},{e=1}}
F.sAffineAnim_HydroCannonCharge = {{x=3,y=3,r=10,d=50},{x=0,y=0,r=0,d=10},{x=-20,y=-20,r=-10,d=20},{e=1}}
F.sAffineAnim_IceBallChunk_0 = {{x=224,y=224,r=0,d=0},{e=1}}
F.sAffineAnim_IceBallChunk_1 = {{x=280,y=280,r=0,d=0},{e=1}}
F.sAffineAnim_IceBallChunk_2 = {{x=336,y=336,r=0,d=0},{e=1}}
F.sAffineAnim_IceBallChunk_3 = {{x=384,y=384,r=0,d=0},{e=1}}
F.sAffineAnim_IceBallChunk_4 = {{x=448,y=448,r=0,d=0},{e=1}}
F.sAffineAnim_IceBeamInnerCrystal = {{x=0,y=0,r=10,d=1},{j=0}}
F.sAffineAnim_IceCrystalHit = {{x=206,y=206,r=0,d=0},{x=5,y=5,r=0,d=10},{x=0,y=0,r=0,d=6},{e=1}}
F.sAffineAnim_IceCrystalSpiralInwardLarge = {{x=0,y=0,r=40,d=1},{j=0}}
F.sAffineAnim_LargeFlame = {{x=50,y=256,r=0,d=0},{x=32,y=0,r=0,d=7},{e=1}}
F.sAffineAnim_LeechLifeNeedle_0 = {{x=0,y=0,r=-33,d=1},{e=1}}
F.sAffineAnim_LeechLifeNeedle_1 = {{x=0,y=0,r=96,d=1},{e=1}}
F.sAffineAnim_LeechLifeNeedle_2 = {{x=0,y=0,r=-96,d=1},{e=1}}
F.sAffineAnim_LusterPurgeCircle = {{x=32,y=32,r=0,d=0},{x=4,y=4,r=0,d=120},{e=1}}
F.sAffineAnim_MeditateStretchAttacker = {{x=-8,y=10,r=0,d=16},{x=18,y=-18,r=0,d=16},{x=-20,y=16,r=0,d=8},{e=1}}
F.sAffineAnim_MegaPunchKick = {{x=256,y=256,r=0,d=0},{x=-4,y=-4,r=20,d=1},{j=1}}
F.sAffineAnim_MegahornHorn_0 = {{x=256,y=256,r=30,d=0},{e=1}}
F.sAffineAnim_MegahornHorn_1 = {{x=256,y=256,r=-99,d=0},{e=1}}
F.sAffineAnim_MegahornHorn_2 = {{x=256,y=256,r=94,d=0},{e=1}}
F.sAffineAnim_PoisonProjectile = {{x=352,y=352,r=0,d=0},{x=-10,y=-10,r=0,d=10},{x=10,y=10,r=0,d=10},{j=0}}
F.sAffineAnim_PsychUpSpiral = {{x=256,y=256,r=0,d=0},{x=-2,y=-2,r=-10,d=120},{e=1}}
F.sAffineAnim_PsychoBoostOrb_0 = {{x=32,y=32,r=0,d=0},{x=16,y=16,r=0,d=17},{l=0},{x=-8,y=-8,r=0,d=10},{x=8,y=8,r=0,d=10},{l=4},{l=0},{x=-16,y=-16,r=0,d=5},{x=16,y=16,r=0,d=5},{l=7},{e=1}}
F.sAffineAnim_PsychoBoostOrb_1 = {{x=-20,y=24,r=0,d=15},{e=1}}
F.sAffineAnim_QuestionMark = {{x=0,y=0,r=4,d=4},{x=0,y=0,r=-4,d=8},{x=0,y=0,r=4,d=4},{l=2},{e=1}}
F.sAffineAnim_ShadowBall = {{x=0,y=0,r=10,d=1},{j=0}}
F.sAffineAnim_SkillSwapOrb_0 = {{x=-8,y=-8,r=0,d=8},{x=8,y=8,r=0,d=8},{j=0}}
F.sAffineAnim_SkillSwapOrb_1 = {{x=240,y=240,r=0,d=0},{x=-8,y=-8,r=0,d=6},{x=8,y=8,r=0,d=8},{x=-8,y=-8,r=0,d=2},{j=1}}
F.sAffineAnim_SkillSwapOrb_2 = {{x=208,y=208,r=0,d=0},{x=-8,y=-8,r=0,d=4},{x=8,y=8,r=0,d=8},{x=-8,y=-8,r=0,d=4},{j=1}}
F.sAffineAnim_SkillSwapOrb_3 = {{x=176,y=176,r=0,d=0},{x=-8,y=-8,r=0,d=2},{x=8,y=8,r=0,d=8},{x=-8,y=-8,r=0,d=6},{j=1}}
F.sAffineAnim_SludgeBombHit = {{x=236,y=236,r=0,d=0},{e=1}}
F.sAffineAnim_SmallExplosion = {{x=80,y=80,r=0,d=0},{x=9,y=9,r=0,d=18},{e=1}}
F.sAffineAnim_SpiderWeb = {{x=16,y=16,r=0,d=0},{x=6,y=6,r=0,d=1},{j=1}}
F.sAffineAnim_SpinningBone = {{x=0,y=0,r=20,d=1},{j=0}}
F.sAffineAnim_SpinningHandOrFoot = {{x=256,y=256,r=0,d=0},{x=-8,y=-8,r=20,d=1},{j=1}}
F.sAffineAnim_SunlightRay = {{x=80,y=80,r=0,d=0},{x=2,y=2,r=10,d=1},{j=1}}
F.sAffineAnim_SuperpowerOrb = {{x=32,y=32,r=0,d=0},{x=4,y=4,r=0,d=64},{x=-6,y=-6,r=0,d=8},{x=6,y=6,r=0,d=8},{j=2}}
F.sAffineAnim_TailGlowOrb = {{x=16,y=16,r=0,d=0},{x=8,y=8,r=0,d=18},{l=0},{x=-5,y=-5,r=0,d=8},{x=5,y=5,r=0,d=8},{l=5},{e=1}}
F.sAffineAnim_TearDrop_0 = {{x=192,y=192,r=80,d=0},{x=0,y=0,r=-2,d=8},{e=1}}
F.sAffineAnim_TearDrop_1 = {{x=192,y=192,r=-80,d=0},{x=0,y=0,r=2,d=8},{e=1}}
F.sAffineAnim_Teleport = {{x=64,y=-4,r=0,d=20},{x=0,y=0,r=0,d=-56},{e=1}}
F.sAffineAnim_ThunderboltOrb = {{x=232,y=232,r=0,d=0},{x=-8,y=-8,r=0,d=10},{x=8,y=8,r=0,d=10},{j=1}}
F.sAffineAnim_Unused = {{x=512,y=512,r=0,d=0},{e=1}}
F.sAffineAnim_UnusedSpinningFist = {{x=256,y=256,r=0,d=0},{x=0,y=0,r=0,d=20},{x=0,y=0,r=-16,d=60},{e=1}}
F.sAffineAnim_Unused_0 = {{x=0,y=0,r=0,d=1},{e=1}}
F.sAffineAnim_Unused_1 = {{x=160,y=160,r=0,d=0},{e=1}}
F.sAffineAnim_VoltTackleBolt = {{x=256,y=256,r=64,d=0},{e=1}}
F.sAffineAnim_WaterBubbleProjectile = {{x=-5,y=-5,r=0,d=10},{x=5,y=5,r=0,d=10},{j=0}}
F.sAffineAnim_WaterPulseRingBubble_0 = {{x=256,y=256,r=0,d=0},{x=-10,y=-10,r=0,d=15},{e=1}}
F.sAffineAnim_WaterPulseRingBubble_1 = {{x=224,y=224,r=0,d=0},{x=-8,y=-8,r=0,d=15},{e=1}}
F.sAffineAnim_WeatherBallIceDown = {{x=336,y=336,r=0,d=0},{e=1}}
F.sAffineAnim_WeatherBallWaterDown = {{x=336,y=336,r=0,d=0},{x=0,y=0,r=0,d=15},{e=1}}
F.sAffineAnim_Whirlpool = {{x=192,y=192,r=0,d=0},{x=2,y=-3,r=0,d=5},{x=-2,y=3,r=0,d=5},{j=1}}
F.sAffineAnims_StretchBattlerUp = {{x=10,y=-13,r=0,d=10},{x=-10,y=13,r=0,d=10},{e=1}}
F.sAffineAnims_Torment = {{x=-12,y=8,r=0,d=4},{x=20,y=-20,r=0,d=4},{x=-8,y=12,r=0,d=4},{e=1}}
F.sAngerMarkAffineAnimCmds = {{x=11,y=11,r=0,d=8},{x=-11,y=-11,r=0,d=8},{e=1}}
F.sAnim_Unused = {{x=256,y=0,r=0,d=0},{x=0,y=32,r=0,d=12},{x=0,y=-32,r=0,d=11},{e=1}}
F.sAromatherapyBigFlowerAffineAnimCmds = {{x=256,y=256,r=0,d=0},{x=0,y=0,r=4,d=1},{j=1}}
F.sBarrageBallAffineAnimCmds1 = {{x=0,y=0,r=-4,d=24},{e=1}}
F.sBarrageBallAffineAnimCmds2 = {{x=256,y=256,r=-64,d=0},{x=0,y=0,r=4,d=24},{e=1}}
F.sBulletSeedAffineAnimCmds = {{x=0,y=0,r=20,d=1},{j=0}}
F.sConversionAffineAnimCmds = {{x=512,y=512,r=0,d=0},{e=1}}
F.sDeepInhaleAffineAnimCmds = {{x=16,y=0,r=0,d=4},{x=0,y=-3,r=0,d=16},{x=4,y=0,r=0,d=4},{x=0,y=0,r=0,d=24},{x=-5,y=3,r=0,d=16},{e=1}}
F.sFacadeSquishAffineAnimCmds = {{x=-16,y=16,r=0,d=6},{x=16,y=-16,r=0,d=12},{x=-16,y=16,r=0,d=6},{e=1}}
F.sFallingBagAffineAnimCmds1 = {{x=0,y=0,r=-4,d=10},{x=0,y=0,r=4,d=20},{x=0,y=0,r=-4,d=10},{e=1}}
F.sFallingBagAffineAnimCmds2 = {{x=0,y=0,r=-1,d=2},{x=0,y=0,r=1,d=4},{x=0,y=0,r=-1,d=4},{x=0,y=0,r=1,d=4},{x=0,y=0,r=-1,d=4},{x=0,y=0,r=1,d=2},{e=1}}
F.sFallingCoinAffineAnimCmds = {{x=0,y=0,r=10,d=1},{j=0}}
F.sFangAffineAnimCmds = {{x=512,y=512,r=0,d=0},{x=-32,y=-32,r=0,d=8},{e=1}}
F.sGrowAndShrinkAffineAnimCmds = {{x=-4,y=-5,r=0,d=12},{x=0,y=0,r=0,d=24},{x=4,y=5,r=0,d=12},{e=1}}
F.sGrowingRingAffineAnimCmds = {{x=32,y=32,r=0,d=0},{x=7,y=7,r=0,d=-56},{e=1}}
F.sGuardRingAffineAnimCmds1 = {{x=256,y=256,r=0,d=0},{e=1}}
F.sGuardRingAffineAnimCmds2 = {{x=512,y=256,r=0,d=0},{e=1}}
F.sHiddenPowerOrbAffineAnimCmds = {{x=128,y=128,r=0,d=0},{x=8,y=8,r=0,d=1},{j=1}}
F.sHyperVoiceRingAffineAnimCmds = {{x=16,y=16,r=0,d=0},{x=11,y=11,r=0,d=45},{e=1}}
F.sKnockOffStrikeAffineanimCmds1 = {{x=256,y=256,r=0,d=0},{x=0,y=0,r=-4,d=8},{e=1}}
F.sKnockOffStrikeAffineanimCmds2 = {{x=-256,y=256,r=0,d=0},{x=0,y=0,r=4,d=8},{e=1}}
F.sLetterZAffineAnimCmds = {{x=-7,y=-7,r=-3,d=16},{x=7,y=7,r=3,d=16},{j=0}}
F.sMeanLookEyeAffineAnimCmds1 = {{x=384,y=384,r=0,d=0},{x=-32,y=24,r=0,d=5},{x=24,y=-32,r=0,d=5},{j=1}}
F.sMeanLookEyeAffineAnimCmds2 = {{x=48,y=48,r=0,d=0},{x=32,y=32,r=0,d=6},{e=1}}
F.sMetronomeFingerAffineAnimCmds1 = {{x=16,y=16,r=0,d=0},{x=30,y=30,r=0,d=8},{e=1}}
F.sMetronomeFingerAffineAnimCmds2 = {{x=0,y=0,r=4,d=11},{x=0,y=0,r=-4,d=11},{l=2},{x=-30,y=-30,r=0,d=8},{e=1}}
F.sMetronomeFingerAffineAnimCmds2_2 = {{x=16,y=16,r=0,d=0},{x=30,y=30,r=0,d=8},{x=0,y=0,r=0,d=16},{l=0},{x=0,y=0,r=4,d=11},{x=0,y=0,r=-4,d=11},{l=2},{x=-30,y=-30,r=0,d=8},{e=1}}
F.sMilkBottleAffineAnimCmds1 = {{x=256,y=256,r=0,d=0},{e=1}}
F.sMilkBottleAffineAnimCmds2 = {{x=0,y=0,r=2,d=12},{x=0,y=0,r=0,d=6},{x=0,y=0,r=-2,d=24},{x=0,y=0,r=0,d=6},{x=0,y=0,r=2,d=12},{j=0}}
F.sMimicOrbAffineAnimCmds1 = {{x=0,y=0,r=0,d=0},{x=48,y=48,r=0,d=14},{e=1}}
F.sMimicOrbAffineAnimCmds2 = {{x=-16,y=-16,r=0,d=1},{j=0}}
F.sPerishSongMusicNoteAffineAnimCmds1 = {{x=0,y=0,r=0,d=5},{e=1}}
F.sPerishSongMusicNoteAffineAnimCmds2 = {{x=0,y=0,r=-8,d=16},{e=1}}
F.sPerishSongMusicNoteAffineAnimCmds3 = {{x=0,y=0,r=8,d=16},{e=1}}
F.sPowerAbsorptionOrbAffineAnimCmds = {{x=-5,y=-5,r=0,d=1},{j=0}}
F.sRazorWindTornadoAffineAnimCmds = {{x=16,y=256,r=0,d=0},{x=4,y=0,r=0,d=40},{e=1}}
F.sRecycleSpriteAffineAnimCmds = {{x=0,y=0,r=-4,d=64},{j=0}}
F.sSilverWindBigSparkAffineAnimCmds = {{x=256,y=256,r=0,d=0},{x=0,y=0,r=-10,d=1},{j=1}}
F.sSilverWindMediumSparkAffineAnimCmds = {{x=192,y=192,r=0,d=0},{x=0,y=0,r=-12,d=1},{j=1}}
F.sSilverWindSmallSparkAffineAnimCmds = {{x=143,y=143,r=0,d=0},{x=0,y=0,r=-15,d=1},{j=1}}
F.sSlackOffSquishAffineAnimCmds = {{x=0,y=16,r=0,d=4},{x=-2,y=0,r=0,d=8},{x=0,y=4,r=0,d=4},{x=0,y=0,r=0,d=24},{x=1,y=-5,r=0,d=16},{e=1}}
F.sSleepLetterZAffineAnimCmds1 = {{x=20,y=20,r=-30,d=0},{x=8,y=8,r=1,d=24},{e=1}}
F.sSleepLetterZAffineAnimCmds1_2 = {{l=0},{x=0,y=0,r=1,d=24},{l=10}}
F.sSleepLetterZAffineAnimCmds2 = {{x=20,y=20,r=30,d=0},{x=8,y=8,r=-1,d=24},{e=1}}
F.sSleepLetterZAffineAnimCmds2_2 = {{l=0},{x=0,y=0,r=-1,d=24},{l=10}}
F.sSlowFlyingMusicNotesAffineAnimCmds = {{x=160,y=160,r=0,d=0},{x=4,y=4,r=0,d=1},{j=1}}
F.sSmellingSaltsSquishAffineAnimCmds = {{x=0,y=-16,r=0,d=6},{x=0,y=16,r=0,d=6},{e=1}}
F.sSmokeBallEscapeCloudAffineAnimCmds1 = {{x=128,y=128,r=0,d=0},{x=-4,y=-6,r=0,d=16},{x=4,y=6,r=0,d=16},{j=0}}
F.sSmokeBallEscapeCloudAffineAnimCmds2 = {{x=192,y=192,r=0,d=0},{x=4,y=6,r=0,d=16},{x=-4,y=-6,r=0,d=16},{j=0}}
F.sSmokeBallEscapeCloudAffineAnimCmds3 = {{x=256,y=256,r=0,d=0},{x=4,y=6,r=0,d=16},{x=-4,y=-6,r=0,d=16},{j=0}}
F.sSmokeBallEscapeCloudAffineAnimCmds4 = {{x=256,y=256,r=0,d=0},{x=8,y=10,r=0,d=30},{x=-8,y=-10,r=0,d=16},{j=0}}
F.sSoftBoiledEggAffineAnimCmds1 = {{x=0,y=0,r=-8,d=2},{x=0,y=0,r=8,d=4},{x=0,y=0,r=-8,d=2},{j=0}}
F.sSoftBoiledEggAffineAnimCmds2 = {{x=256,y=256,r=0,d=0},{e=1}}
F.sSoftBoiledEggAffineAnimCmds3 = {{x=-8,y=4,r=0,d=8},{l=0},{x=16,y=-8,r=0,d=8},{x=-16,y=8,r=0,d=8},{l=1},{x=256,y=256,r=0,d=0},{x=0,y=0,r=0,d=15},{e=1}}
F.sSpitUpDeformMonAffineAnimCmds = {{x=0,y=6,r=0,d=20},{x=0,y=0,r=0,d=20},{x=0,y=-18,r=0,d=6},{x=-18,y=-18,r=0,d=3},{x=0,y=0,r=0,d=15},{x=4,y=4,r=0,d=13},{e=1}}
F.sSpitUpOrbAffineAnimCmds = {{x=128,y=128,r=0,d=0},{x=8,y=8,r=0,d=1},{j=1}}
F.sSplashEffectAffineAnimCmds = {{x=-6,y=4,r=0,d=8},{x=10,y=-10,r=0,d=8},{x=-4,y=6,r=0,d=8},{e=1}}
F.sSpotlightAffineAnimCmds1 = {{x=0,y=384,r=0,d=0},{x=16,y=0,r=0,d=20},{e=1}}
F.sSpotlightAffineAnimCmds2 = {{x=320,y=384,r=0,d=0},{x=-16,y=0,r=0,d=19},{e=1}}
F.sStockpileAbsorptionOrbAffineCmds = {{x=320,y=320,r=0,d=0},{x=-14,y=-14,r=0,d=1},{j=1}}
F.sStockpileDeformMonAffineAnimCmds = {{x=8,y=-8,r=0,d=12},{x=-16,y=16,r=0,d=12},{x=8,y=-8,r=0,d=12},{l=1},{e=1}}
F.sStretchAttackerAffineAnimCmds = {{x=96,y=-13,r=0,d=8},{e=1}}
F.sStrongFrustrationAffineAnimCmds = {{x=0,y=-15,r=0,d=7},{x=0,y=15,r=0,d=7},{l=2},{e=1}}
F.sSwallowDeformMonAffineAnimCmds = {{x=0,y=6,r=0,d=20},{x=0,y=0,r=0,d=20},{x=7,y=-30,r=0,d=6},{x=0,y=0,r=0,d=20},{x=-2,y=3,r=0,d=20},{e=1}}
F.sSwiftStarAffineAnimCmds = {{x=0,y=0,r=0,d=1},{j=0}}
F.sSwordsDanceBladeAffineAnimCmds = {{x=16,y=256,r=0,d=0},{x=20,y=0,r=0,d=12},{x=0,y=0,r=0,d=32},{e=1}}
F.sThinRingExpandingAffineAnimCmds1 = {{x=16,y=16,r=0,d=0},{x=16,y=16,r=0,d=30},{e=1}}
F.sThinRingExpandingAffineAnimCmds2 = {{x=16,y=16,r=0,d=0},{x=32,y=32,r=0,d=15},{e=1}}
F.sThinRingShrinkingAffineAnimCmds = {{x=512,y=512,r=0,d=0},{x=-16,y=-16,r=0,d=30},{e=1}}
F.sThrashMoveMonAffineAnimCmds = {{x=-10,y=9,r=0,d=7},{x=20,y=-20,r=0,d=7},{x=-20,y=20,r=0,d=7},{x=10,y=-9,r=0,d=7},{l=2},{e=1}}
F.sTriAttackTriangleAffineAnimCmds = {{x=0,y=0,r=5,d=40},{x=0,y=0,r=10,d=10},{x=0,y=0,r=15,d=10},{x=0,y=0,r=20,d=40},{j=0}}
F.sTrickBagAffineAnimCmds1 = {{x=0,y=0,r=0,d=3},{e=1}}
F.sTrickBagAffineAnimCmds2 = {{x=0,y=-10,r=0,d=3},{x=0,y=-6,r=0,d=3},{x=0,y=-2,r=0,d=3},{x=0,y=0,r=0,d=3},{x=0,y=2,r=0,d=3},{x=0,y=6,r=0,d=3},{x=0,y=10,r=0,d=3},{e=1}}
F.sUproarAffineAnimCmds = {{x=-12,y=8,r=0,d=4},{x=20,y=-20,r=0,d=4},{x=-8,y=12,r=0,d=4},{e=1}}
F.sWaterPulseRingAffineAnimCmds = {{x=5,y=5,r=0,d=10},{x=-10,y=-10,r=0,d=10},{x=10,y=10,r=0,d=10},{x=-10,y=-10,r=0,d=10},{x=10,y=10,r=0,d=10},{x=-10,y=-10,r=0,d=10},{x=10,y=10,r=0,d=10},{e=1}}
F.sWavyMusicNotesAffineAnimCmds = {{x=12,y=12,r=0,d=16},{x=65524,y=65524,r=0,d=16},{j=0}}
F.sYawnCloudAffineAnimCmds1 = {{x=128,y=128,r=0,d=0},{x=-8,y=-8,r=0,d=8},{x=8,y=8,r=0,d=8},{j=0}}
F.sYawnCloudAffineAnimCmds2 = {{x=192,y=192,r=0,d=0},{x=8,y=8,r=0,d=8},{x=-8,y=-8,r=0,d=8},{j=0}}
F.sYawnCloudAffineAnimCmds3 = {{x=256,y=256,r=0,d=0},{x=8,y=8,r=0,d=8},{x=-8,y=-8,r=0,d=8},{j=0}}
local T = {}
T.gAbsorptionOrbSpriteTemplate = {tag="ORBS",w=16,h=16,aff=1,blend=1,anims={A.sPowerAbsorptionOrbAnimCmds},affine={F.sAbsorptionOrbAffineAnimCmds}}
T.gAcidPoisonBubbleSpriteTemplate = {tag="POISON_BUBBLE",w=16,h=16,aff=3,blend=0,anims={A.sAnim_PoisonProjectile},affine={F.sAffineAnim_PoisonProjectile}}
T.gAcidPoisonDropletSpriteTemplate = {tag="POISON_BUBBLE",w=16,h=16,aff=3,blend=0,anims={A.sAnim_AcidPoisonDroplet},affine={F.sAffineAnim_AcidPoisonDroplet}}
T.gAirCutterSliceSpriteTemplate = {tag="CUT",w=32,h=32,aff=0,blend=1,anims={A.sCuttingSliceAnimCmds}}
T.gAirWaveCrescentSpriteTemplate = {tag="AIR_WAVE_2",w=32,h=16,aff=0,blend=0,anims={A.sAffineAnim_AirWaveCrescent}}
T.gAirWaveProjectileSpriteTemplate = {tag="AIR_WAVE",w=32,h=16,aff=0,blend=1}
T.gAncientPowerRockSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Rock_Biggest,A.sAnim_Rock_Bigger,A.sAnim_Rock_Big,A.sAnim_Rock_Small,A.sAnim_Rock_Smaller,A.sAnim_Rock_Smallest}}
T.gAngelSpriteTemplate = {tag="ANGEL",w=32,h=32,aff=0,blend=0,anims={A.sAngelSpriteAnimCmds}}
T.gAngerMarkSpriteTemplate = {tag="ANGER",w=16,h=16,aff=1,blend=0,affine={F.sAngerMarkAffineAnimCmds}}
T.gArmThrustHandSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gAromatherapyBigFlowerSpriteTemplate = {tag="FLOWER",w=16,h=16,aff=1,blend=0,anims={A.sPetalDanceBigFlowerAnimCmds},affine={F.sAromatherapyBigFlowerAffineAnimCmds}}
T.gAromatherapySmallFlowerSpriteTemplate = {tag="FLOWER",w=8,h=8,aff=0,blend=0,anims={A.sPetalDanceSmallFlowerAnimCmds}}
T.gAssistPawprintSpriteTemplate = {tag="PAW_PRINT",w=32,h=32,aff=0,blend=0}
T.gAuroraBeamRingSpriteTemplate = {tag="RAINBOW_RINGS",w=8,h=16,aff=3,blend=0,anims={A.sAnim_AuroraBeamRing_0,A.sAnim_AuroraBeamRing_1},affine={F.sAffineAnim_AuroraBeamRing}}
T.gBarrageBallSpriteTemplate = {tag="RED_BALL",w=32,h=32,aff=1,blend=0,affine={F.sBarrageBallAffineAnimCmds1,F.sBarrageBallAffineAnimCmds2}}
T.gBarrierWallSpriteTemplate = {tag="GRAY_LIGHT_WALL",w=64,h=64,aff=0,blend=1}
T.gBasicHitSplatSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gBatonPassPokeballSpriteTemplate = {tag="POKEBALL",w=16,h=16,aff=0,blend=0}
T.gBellSpriteTemplate = {tag="BELL",w=32,h=32,aff=0,blend=0,anims={A.sBellAnimCmds}}
T.gBellyDrumHandSpriteTemplate = {tag="PURPLE_HAND_OUTLINE",w=32,h=32,aff=0,blend=0}
T.gBentSpoonSpriteTemplate = {tag="BENT_SPOON",w=16,h=32,aff=0,blend=0,anims={A.sAnim_BentSpoon_0,A.sAnim_BentSpoon_1}}
T.gBlackBallSpriteTemplate = {tag="BLACK_BALL",w=8,h=8,aff=0,blend=0}
T.gBlackSmokeSpriteTemplate = {tag="BLACK_SMOKE",w=32,h=16,aff=0,blend=0}
T.gBlendThinRingExpandingSpriteTemplate = {tag="THIN_RING",w=64,h=64,aff=3,blend=1,affine={F.sThinRingExpandingAffineAnimCmds1,F.sThinRingExpandingAffineAnimCmds2}}
T.gBlizzardIceCrystalSpriteTemplate = {tag="ICE_CRYSTALS",w=16,h=16,aff=0,blend=0,anims={A.sAnim_BlizzardIceCrystal}}
T.gBlockXSpriteTemplate = {tag="X_SIGN",w=64,h=64,aff=0,blend=0}
T.gBonemerangSpriteTemplate = {tag="BONE",w=32,h=32,aff=1,blend=0,affine={F.sAffineAnim_Bonemerang}}
T.gBounceBallLandSpriteTemplate = {tag="ROUND_SHADOW",w=64,h=64,aff=3,blend=0,affine={F.sAffineAnim_BounceBallLand}}
T.gBounceBallShrinkSpriteTemplate = {tag="ROUND_SHADOW",w=64,h=64,aff=3,blend=0,affine={F.sAffineAnim_BounceBallShrink}}
T.gBowMonSpriteTemplate = {tag="0"}
T.gBreathPuffSpriteTemplate = {tag="BREATH",w=16,h=16,aff=0,blend=0,anims={A.sBreathPuffAnimCmds1,A.sBreathPuffAnimCmds2}}
T.gBrickBreakWallShardSpriteTemplate = {tag="TORN_METAL",w=32,h=32,aff=0,blend=0}
T.gBrickBreakWallSpriteTemplate = {tag="BLUE_LIGHT_WALL",w=64,h=64,aff=0,blend=1}
T.gBulletSeedSpriteTemplate = {tag="SEED",w=16,h=16,aff=1,blend=0,affine={F.sBulletSeedAffineAnimCmds}}
T.gBurnFlameSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_BasicFire}}
T.gClampJawSpriteTemplate = {tag="CLAMP",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_Bite_0,F.sAffineAnim_Bite_1,F.sAffineAnim_Bite_2,F.sAffineAnim_Bite_3,F.sAffineAnim_Bite_4,F.sAffineAnim_Bite_5,F.sAffineAnim_Bite_6,F.sAffineAnim_Bite_7}}
T.gClappingHand2SpriteTemplate = {tag="TAG_HAND",w=32,h=32,aff=0,blend=0}
T.gClappingHandSpriteTemplate = {tag="TAG_HAND",w=32,h=32,aff=0,blend=0}
T.gClawSlashSpriteTemplate = {tag="CLAW_SLASH",w=32,h=32,aff=0,blend=0,anims={A.sAnim_ClawSlash_0,A.sAnim_ClawSlash_1}}
T.gCoinThrowSpriteTemplate = {tag="COIN",w=16,h=16,aff=1,blend=0,anims={A.sCoinAnimCmds}}
T.gComplexPaletteBlendSpriteTemplate = {tag="0"}
T.gConfuseRayBallBounceSpriteTemplate = {tag="YELLOW_BALL",w=16,h=16,aff=3,blend=0,affine={F.sAffineAnim_ConfuseRayBallBounce}}
T.gConfuseRayBallSpiralSpriteTemplate = {tag="YELLOW_BALL",w=16,h=16,aff=0,blend=1}
T.gConfusionDuckSpriteTemplate = {tag="DUCK",w=16,h=16,aff=0,blend=0,anims={A.sAnim_ConfusionDuck_0,A.sAnim_ConfusionDuck_1}}
T.gConstrictBindingSpriteTemplate = {tag="TENDRILS",w=64,h=32,aff=1,blend=0,anims={A.sAnim_ConstrictBinding,A.sAnim_ConstrictBinding_Flipped},affine={F.sAffineAnim_ConstrictBinding,F.sAffineAnim_ConstrictBinding_Flipped}}
T.gConversion2SpriteTemplate = {tag="CONVERSION",w=8,h=8,aff=3,blend=1,anims={A.sConversion2AnimCmds},affine={F.sConversionAffineAnimCmds}}
T.gConversionSpriteTemplate = {tag="CONVERSION",w=8,h=8,aff=3,blend=1,anims={A.sConversionAnimCmds},affine={F.sConversionAffineAnimCmds}}
T.gCrossChopHandSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gCrossImpactSpriteTemplate = {tag="CROSS_IMPACT",w=32,h=32,aff=0,blend=1}
T.gCurseGhostSpriteTemplate = {tag="GHOSTLY_SPIRIT",w=32,h=32,aff=0,blend=1}
T.gCurseNailSpriteTemplate = {tag="NAIL",w=32,h=16,aff=0,blend=1}
T.gCuttingSliceSpriteTemplate = {tag="CUT",w=32,h=32,aff=0,blend=1,anims={A.sCuttingSliceAnimCmds}}
T.gDestinyBondWhiteShadowSpriteTemplate = {tag="WHITE_SHADOW",w=64,h=32,aff=0,blend=1}
T.gDevilSpriteTemplate = {tag="DEVIL",w=32,h=32,aff=0,blend=0,anims={A.sDevilAnimCmds1,A.sDevilAnimCmds2}}
T.gDirtMoundSpriteTemplate = {tag="DIRT_MOUND",w=32,h=16,aff=0,blend=0}
T.gDirtPlumeSpriteTemplate = {tag="MUD_SAND",w=8,h=8,aff=0,blend=0}
T.gDiveBallSpriteTemplate = {tag="ROUND_SHADOW",w=64,h=64,aff=3,blend=0,affine={F.sAffineAnim_DiveBall}}
T.gDiveWaterSplashSpriteTemplate = {tag="SPLASH",w=64,h=64,aff=3,blend=0}
T.gDizzyPunchDuckSpriteTemplate = {tag="DUCK",w=16,h=16,aff=0,blend=0}
T.gDragonBreathFireSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=3,blend=0,anims={A.sAnim_DragonBreathFire_0,A.sAnim_DragonBreathFire_1},affine={F.sAffineAnim_DragonBreathFire_0,F.sAffineAnim_DragonBreathFire_1}}
T.gDragonDanceOrbSpriteTemplate = {tag="HOLLOW_ORB",w=16,h=16,aff=0,blend=0}
T.gDragonRageFirePlumeSpriteTemplate = {tag="FIRE_PLUME",w=32,h=32,aff=0,blend=0,anims={A.sAnim_DragonRageFirePlume}}
T.gDragonRageFireSpitSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=3,blend=0,anims={A.sAnim_DragonRageFire,A.sAnim_DragonRageFire},affine={F.sAffineAnim_DragonRageFire_0,F.sAffineAnim_DragonRageFire_1}}
T.gEclipsingOrbSpriteTemplate = {tag="ECLIPSING_ORB",w=32,h=32,aff=0,blend=0,anims={A.sEclipsingOrbAnimCmds}}
T.gEggThrowSpriteTemplate = {tag="LARGE_FRESH_EGG",w=16,h=16,aff=0,blend=0}
T.gElectricChargingParticlesSpriteTemplate = {tag="ELECTRIC_ORBS",w=8,h=8,aff=0,blend=0,anims={A.sAnim_ElectricChargingParticles_0,A.sAnim_ElectricChargingParticles_1}}
T.gElectricPuffSpriteTemplate = {tag="ELECTRICITY",w=32,h=32,aff=0,blend=0,anims={A.sAnim_ElectricPuff}}
T.gElectricitySpriteTemplate = {tag="SPARK_2",w=16,h=16,aff=0,blend=0}
T.gEllipticalGustSpriteTemplate = {tag="GUST",w=32,h=64,aff=0,blend=0}
T.gEmberFlareSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_BasicFire}}
T.gEmberSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0}
T.gEndureEnergySpriteTemplate = {tag="FOCUS_ENERGY",w=16,h=32,aff=0,blend=0,anims={A.sEndureEnergyAnimCmds}}
T.gEruptionFallingRockSpriteTemplate = {tag="WARM_ROCK",w=32,h=32,aff=0,blend=0}
T.gEruptionLaunchRockSpriteTemplate = {tag="WARM_ROCK",w=16,h=16,aff=0,blend=0}
T.gExplosionSpriteTemplate = {tag="EXPLOSION",w=32,h=32,aff=0,blend=0,anims={A.sExplosionAnimCmds}}
T.gEyeSparkleSpriteTemplate = {tag="EYE_SPARKLE",w=16,h=16,aff=0,blend=0,anims={A.sEyeSparkleAnimCmds}}
T.gFacadeSweatDropSpriteTemplate = {tag="SWEAT_DROP",w=8,h=8,aff=0,blend=0}
T.gFallingCoinSpriteTemplate = {tag="COIN",w=16,h=16,aff=1,blend=0,anims={A.sCoinAnimCmds},affine={F.sFallingCoinAffineAnimCmds}}
T.gFallingFeatherSpriteTemplate = {tag="WHITE_FEATHER",w=32,h=32,aff=1,blend=0,anims={A.sAnim_FallingFeather_0,A.sAnim_FallingFeather_1}}
T.gFallingRockSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FlyingRock_0,A.sAnim_FlyingRock_1,A.sAnim_FlyingRock_2}}
T.gFalseSwipePositionedSliceSpriteTemplate = {tag="SLASH_2",w=32,h=32,aff=0,blend=0,anims={A.sSlashSliceAnimCmds1,A.sSlashSliceAnimCmds2}}
T.gFalseSwipeSliceSpriteTemplate = {tag="SLASH_2",w=32,h=32,aff=0,blend=0,anims={A.sSlashSliceAnimCmds1,A.sSlashSliceAnimCmds2}}
T.gFangSpriteTemplate = {tag="FANG_ATTACK",w=32,h=32,aff=3,blend=0,anims={A.sFangAnimCmds},affine={F.sFangAffineAnimCmds}}
T.gFastFlyingMusicNotesSpriteTemplate = {tag="MUSIC_NOTES",w=16,h=16,aff=3,blend=0,anims={A.sWavyMusicNotesAnimCmds1,A.sWavyMusicNotesAnimCmds2,A.sWavyMusicNotesAnimCmds3,A.sWavyMusicNotesAnimCmds4,A.sWavyMusicNotesAnimCmds5,A.sWavyMusicNotesAnimCmds6,A.sWavyMusicNotesAnimCmds7,A.sWavyMusicNotesAnimCmds8},affine={F.sWavyMusicNotesAffineAnimCmds}}
T.gFireBlastCrossSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FireBlastCross}}
T.gFireBlastRingSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_BasicFire}}
T.gFirePlumeSpriteTemplate = {tag="FIRE_PLUME",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FirePlume}}
T.gFireSpinSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_BasicFire}}
T.gFireSpiralInwardSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FireSpiralSpread_0,A.sAnim_FireSpiralSpread_1}}
T.gFireSpiralOutwardSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_BasicFire}}
T.gFireSpreadSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FireSpiralSpread_0,A.sAnim_FireSpiralSpread_1}}
T.gFistFootRandomPosSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gFistFootSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gFlamethrowerFlameSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FlamethrowerFlame}}
T.gFlashingHitSplatSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=1,blend=0,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gFlatterConfettiSpriteTemplate = {tag="CONFETTI",w=8,h=8,aff=0,blend=0}
T.gFlatterSpotlightSpriteTemplate = {tag="SPOTLIGHT",w=64,h=64,aff=3,blend=0,affine={F.sSpotlightAffineAnimCmds1,F.sSpotlightAffineAnimCmds2}}
T.gFlyBallAttackSpriteTemplate = {tag="ROUND_SHADOW",w=64,h=64,aff=1,blend=0,affine={F.sAffineAnim_FlyBallAttack_0,F.sAffineAnim_FlyBallAttack_1}}
T.gFlyBallUpSpriteTemplate = {tag="ROUND_SHADOW",w=64,h=64,aff=3,blend=0,affine={F.sAffineAnim_FlyBallUp}}
T.gFlyingSandCrescentSpriteTemplate = {tag="FLYING_DIRT",w=32,h=16,aff=0,blend=0}
T.gFocusPunchFistSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=3,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight},affine={F.sAffineAnim_FocusPunchFist}}
T.gFollowMeFingerSpriteTemplate = {tag="FINGER",w=32,h=32,aff=1,blend=0,affine={F.sMetronomeFingerAffineAnimCmds1,F.sMetronomeFingerAffineAnimCmds2}}
T.gForesightMagnifyingGlassSpriteTemplate = {tag="MAGNIFYING_GLASS",w=32,h=32,aff=0,blend=1}
T.gFrenzyPlantRootSpriteTemplate = {tag="ROOTS",w=32,h=32,aff=0,blend=0,anims={A.sIngrainRootAnimCmds1,A.sIngrainRootAnimCmds2,A.sIngrainRootAnimCmds3,A.sIngrainRootAnimCmds4}}
T.gFurySwipesSpriteTemplate = {tag="SWIPE",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FurySwipes,A.sAnim_FurySwipes_Flipped}}
T.gGlareEyeDotSpriteTemplate = {tag="SMALL_RED_EYE",w=8,h=8,aff=0,blend=0}
T.gGoldRingSpriteTemplate = {tag="GOLD_RING",w=16,h=32,aff=0,blend=0}
T.gGrantingStarsSpriteTemplate = {tag="SPARKLE_2",w=32,h=32,aff=0,blend=0,anims={A.sGrantingStarsAnimCmds}}
T.gGreenStarSpriteTemplate = {tag="GREEN_STAR",w=16,h=16,aff=0,blend=0,anims={A.sGreenStarAnimCmds1,A.sGreenStarAnimCmds2,A.sGreenStarAnimCmds3}}
T.gGrowingChargeOrbSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_GrowingElectricOrb_0,F.sAffineAnim_GrowingElectricOrb_1,F.sAffineAnim_GrowingElectricOrb_2}}
T.gGrowingShockWaveOrbSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_GrowingElectricOrb_0,F.sAffineAnim_GrowingElectricOrb_1,F.sAffineAnim_GrowingElectricOrb_2}}
T.gGrudgeFlameSpriteTemplate = {tag="PURPLE_FLAME",w=16,h=32,aff=0,blend=1,anims={A.sAnim_GrudgeFlame}}
T.gGuardRingSpriteTemplate = {tag="GUARD_RING",w=64,h=32,aff=3,blend=1,affine={F.sGuardRingAffineAnimCmds1,F.sGuardRingAffineAnimCmds2}}
T.gGuillotineSpriteTemplate = {tag="CUT",w=32,h=32,aff=0,blend=1,anims={A.sGuillotineAnimCmds1,A.sGuillotineAnimCmds2}}
T.gGustToTargetSpriteTemplate = {tag="GUST",w=32,h=64,aff=1,blend=0,affine={F.sAffineAnim_GustToTarget}}
T.gHandleInvertHitSplatSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gHealBellMusicNoteSpriteTemplate = {tag="MUSIC_NOTES_2",w=16,h=16,aff=0,blend=0}
T.gHealingBlueStarSpriteTemplate = {tag="BLUE_STAR",w=32,h=32,aff=0,blend=0,anims={A.sHealingBlueStarAnimCmds}}
T.gHelpingHandClapSpriteTemplate = {tag="TAG_HAND",w=32,h=32,aff=0,blend=0}
T.gHiddenPowerOrbScatterSpriteTemplate = {tag="RED_ORB",w=16,h=16,aff=3,blend=0,affine={F.sHiddenPowerOrbAffineAnimCmds}}
T.gHiddenPowerOrbSpriteTemplate = {tag="RED_ORB",w=16,h=16,aff=1,blend=0,affine={F.sHiddenPowerOrbAffineAnimCmds}}
T.gHorizontalLungeSpriteTemplate = {tag="0"}
T.gHornHitSpriteTemplate = {tag="HORN_HIT",w=32,h=32,aff=0,blend=0}
T.gHydroCannonBeamSpriteTemplate = {tag="WATER_ORB",w=16,h=16,aff=3,blend=1,anims={A.sAnim_WaterMudOrb},affine={F.sAffineAnim_HydroCannonBeam}}
T.gHydroCannonChargeSpriteTemplate = {tag="WATER_ORB",w=16,h=16,aff=3,blend=1,anims={A.sAnim_WaterMudOrb},affine={F.sAffineAnim_HydroCannonCharge}}
T.gHydroPumpOrbSpriteTemplate = {tag="WATER_ORB",w=16,h=16,aff=0,blend=1,anims={A.sAnim_WaterMudOrb}}
T.gHyperBeamOrbSpriteTemplate = {tag="ORBS",w=8,h=8,aff=0,blend=0,anims={A.sSolarBeamBigOrbAnimCmds1,A.sSolarBeamBigOrbAnimCmds2,A.sSolarBeamBigOrbAnimCmds3,A.sSolarBeamBigOrbAnimCmds4,A.sSolarBeamBigOrbAnimCmds5,A.sSolarBeamBigOrbAnimCmds6,A.sSolarBeamBigOrbAnimCmds7}}
T.gHyperVoiceRingSpriteTemplate = {tag="THIN_RING",w=64,h=64,aff=3,blend=1,affine={F.sHyperVoiceRingAffineAnimCmds}}
T.gIceBallChunkSpriteTemplate = {tag="ICE_CHUNK",w=32,h=32,aff=3,blend=0,anims={A.sAnim_IceBallChunk_0,A.sAnim_IceBallChunk_1},affine={F.sAffineAnim_IceBallChunk_0,F.sAffineAnim_IceBallChunk_1,F.sAffineAnim_IceBallChunk_2,F.sAffineAnim_IceBallChunk_3,F.sAffineAnim_IceBallChunk_4}}
T.gIceBallImpactShardSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=0,anims={A.sAnim_IceCrystalSmall}}
T.gIceBeamInnerCrystalSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=16,aff=1,blend=1,anims={A.sAnim_IceCrystalLarge},affine={F.sAffineAnim_IceBeamInnerCrystal}}
T.gIceBeamOuterCrystalSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=1,anims={A.sAnim_IceCrystalSmall}}
T.gIceCrystalHitLargeSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=16,aff=1,blend=1,anims={A.sAnim_IceCrystalLarge},affine={F.sAffineAnim_IceCrystalHit}}
T.gIceCrystalHitSmallSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=1,blend=1,anims={A.sAnim_IceCrystalSmall},affine={F.sAffineAnim_IceCrystalHit}}
T.gIceCrystalSpiralInwardLarge = {tag="ICE_CRYSTALS",w=8,h=16,aff=3,blend=1,anims={A.sAnim_IceCrystalLarge},affine={F.sAffineAnim_IceCrystalSpiralInwardLarge}}
T.gIceCrystalSpiralInwardSmall = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=1,anims={A.sAnim_IceCrystalSmall}}
T.gIceGroundSpikeSpriteTemplate = {tag="ICE_SPIKES",w=8,h=16,aff=0,blend=1,anims={A.sAnim_IceGroundSpike}}
T.gIcicleSpearSpriteTemplate = {tag="ICICLE_SPEAR",w=32,h=32,aff=1,blend=0}
T.gIngrainOrbSpriteTemplate = {tag="ORBS",w=8,h=8,aff=0,blend=0,anims={A.sIngrainOrbAnimCmds}}
T.gIngrainRootSpriteTemplate = {tag="ROOTS",w=32,h=32,aff=0,blend=0,anims={A.sIngrainRootAnimCmds1,A.sIngrainRootAnimCmds2,A.sIngrainRootAnimCmds3,A.sIngrainRootAnimCmds4}}
T.gItemStealSpriteTemplate = {tag="ITEM_BAG",w=32,h=32,aff=1,blend=0,anims={A.sFallingBagAnimCmds},affine={F.sFallingBagAffineAnimCmds1,F.sFallingBagAffineAnimCmds2}}
T.gJaggedMusicNoteSpriteTemplate = {tag="JAGGED_MUSIC_NOTE",w=32,h=32,aff=0,blend=0}
T.gJumpKickSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gKarateChopSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gKinesisZapEnergySpriteTemplate = {tag="ALERT",w=32,h=16,aff=0,blend=0,anims={A.sKinesisZapEnergyAnimCmds}}
T.gKnockOffItemSpriteTemplate = {tag="ITEM_BAG",w=32,h=32,aff=1,blend=0,anims={A.sFallingBagAnimCmds},affine={F.sFallingBagAffineAnimCmds1,F.sFallingBagAffineAnimCmds2}}
T.gKnockOffStrikeSpriteTemplate = {tag="SLAM_HIT_2",w=64,h=64,aff=1,blend=0,anims={A.sKnockOffStrikeAnimCmds},affine={F.sKnockOffStrikeAffineanimCmds1,F.sKnockOffStrikeAffineanimCmds2}}
T.gLargeFlameScatterSpriteTemplate = {tag="FIRE",w=32,h=32,aff=0,blend=0,anims={A.sAnim_LargeFlame}}
T.gLargeFlameSpriteTemplate = {tag="FIRE",w=32,h=32,aff=1,blend=0,anims={A.sAnim_LargeFlame},affine={F.sAffineAnim_LargeFlame}}
T.gLeafBladeSpriteTemplate = {tag="LEAF",w=16,h=16,aff=0,blend=0,anims={A.sLeafBladeAnimCmds1,A.sLeafBladeAnimCmds2,A.sLeafBladeAnimCmds3,A.sLeafBladeAnimCmds4,A.sLeafBladeAnimCmds5,A.sLeafBladeAnimCmds6,A.sLeafBladeAnimCmds7}}
T.gLeechLifeNeedleSpriteTemplate = {tag="NEEDLE",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_LeechLifeNeedle_0,F.sAffineAnim_LeechLifeNeedle_1,F.sAffineAnim_LeechLifeNeedle_2}}
T.gLeechSeedSpriteTemplate = {tag="SEED",w=16,h=16,aff=0,blend=0,anims={A.sLeechSeedAnimCmds1,A.sLeechSeedAnimCmds2}}
T.gLeerSpriteTemplate = {tag="LEER",w=32,h=32,aff=0,blend=0,anims={A.sLeerAnimCmds}}
T.gLetterZSpriteTemplate = {tag="LETTER_Z",w=32,h=32,aff=1,blend=0,anims={A.sLetterZAnimCmds},affine={F.sLetterZAffineAnimCmds}}
T.gLickSpriteTemplate = {tag="LICK",w=16,h=32,aff=0,blend=0,anims={A.sAnim_Lick}}
T.gLightScreenWallSpriteTemplate = {tag="GREEN_LIGHT_WALL",w=64,h=64,aff=0,blend=1}
T.gLightningSpriteTemplate = {tag="LIGHTNING",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Lightning}}
T.gLinearStingerSpriteTemplate = {tag="NEEDLE",w=16,h=16,aff=1,blend=0}
T.gLockOnMoveTargetSpriteTemplate = {tag="LOCK_ON",w=16,h=16,aff=0,blend=0}
T.gLockOnTargetSpriteTemplate = {tag="LOCK_ON",w=32,h=32,aff=0,blend=0}
T.gLusterPurgeCircleSpriteTemplate = {tag="WHITE_CIRCLE_OF_LIGHT",w=64,h=64,aff=3,blend=1,affine={F.sAffineAnim_LusterPurgeCircle}}
T.gMagentaHeartSpriteTemplate = {tag="MAGENTA_HEART",w=16,h=16,aff=0,blend=0}
T.gMagicCoatWallSpriteTemplate = {tag="ORANGE_LIGHT_WALL",w=64,h=64,aff=0,blend=1}
T.gMeanLookEyeSpriteTemplate = {tag="EYE",w=64,h=64,aff=3,blend=1,affine={F.sMeanLookEyeAffineAnimCmds1,F.sMeanLookEyeAffineAnimCmds2}}
T.gMegaPunchKickSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=3,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight},affine={F.sAffineAnim_MegaPunchKick}}
T.gMegahornHornSpriteTemplate = {tag="HORN_HIT_2",w=32,h=16,aff=3,blend=0,affine={F.sAffineAnim_MegahornHorn_0,F.sAffineAnim_MegahornHorn_1,F.sAffineAnim_MegahornHorn_2}}
T.gMetalSoundSpriteTemplate = {tag="METAL_SOUND_WAVES",w=32,h=64,aff=3,blend=0,affine={F.sGrowingRingAffineAnimCmds}}
T.gMeteorMashStarSpriteTemplate = {tag="GOLD_STARS",w=16,h=16,aff=0,blend=0}
T.gMetronomeFingerSpriteTemplate = {tag="FINGER",w=32,h=32,aff=3,blend=0,affine={F.sMetronomeFingerAffineAnimCmds1,F.sMetronomeFingerAffineAnimCmds2}}
T.gMilkBottleSpriteTemplate = {tag="MILK_BOTTLE",w=32,h=32,aff=1,blend=1,affine={F.sMilkBottleAffineAnimCmds1,F.sMilkBottleAffineAnimCmds2}}
T.gMimicOrbSpriteTemplate = {tag="ORBS",w=16,h=16,aff=3,blend=0,anims={A.sPowerAbsorptionOrbAnimCmds},affine={F.sMimicOrbAffineAnimCmds1,F.sMimicOrbAffineAnimCmds2}}
T.gMiniTwinklingStarSpriteTemplate = {tag="GOLD_STARS",w=8,h=8,aff=0,blend=0}
T.gMirrorCoatWallSpriteTemplate = {tag="RED_LIGHT_WALL",w=64,h=64,aff=0,blend=1}
T.gMistBallSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=0,blend=0}
T.gMistCloudSpriteTemplate = {tag="MIST_CLOUD",w=32,h=16,aff=0,blend=1,anims={A.sAnim_Cloud}}
T.gMonEdgeHitSplatSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gMoonSpriteTemplate = {tag="MOON",w=64,h=64,aff=0,blend=1}
T.gMoonlightSparkleSpriteTemplate = {tag="GREEN_SPARKLE",w=16,h=16,aff=0,blend=0,anims={A.sMoonlightSparkleAnimCmds}}
T.gMovementWavesSpriteTemplate = {tag="MOVEMENT_WAVES",w=32,h=32,aff=0,blend=0,anims={A.sMovementWavesAnimCmds1,A.sMovementWavesAnimCmds2}}
T.gMudShotOrbSpriteTemplate = {tag="BROWN_ORB",w=16,h=16,aff=0,blend=1,anims={A.sAnim_WaterMudOrb}}
T.gMudSlapMudSpriteTemplate = {tag="MUD_SAND",w=16,h=16,aff=0,blend=0,anims={A.sAnim_MudSlapMud}}
T.gMudsportMudSpriteTemplate = {tag="MUD_SAND",w=16,h=16,aff=0,blend=0}
T.gNeedleArmSpikeSpriteTemplate = {tag="GREEN_SPIKE",w=16,h=16,aff=1,blend=0}
T.gNightmareDevilSpriteTemplate = {tag="DEVIL",w=32,h=32,aff=0,blend=1}
T.gOctazookaBallSpriteTemplate = {tag="BLACK_BALL",w=8,h=8,aff=0,blend=0}
T.gOctazookaSmokeSpriteTemplate = {tag="GRAY_SMOKE",w=32,h=32,aff=0,blend=0,anims={A.sOctazookaAnimCmds}}
T.gOpeningEyeSpriteTemplate = {tag="OPENING_EYE",w=32,h=32,aff=0,blend=0,anims={A.sOpeningEyeAnimCmds}}
T.gOutrageFlameSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_OutrageOverheatFire_0}}
T.gOverheatFlameSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_OutrageOverheatFire_0}}
T.gPainSplitProjectileSpriteTemplate = {tag="PAIN_SPLIT",w=16,h=16,aff=0,blend=0,anims={A.sPainSplitAnimCmds}}
T.gPencilSpriteTemplate = {tag="PENCIL",w=32,h=32,aff=0,blend=0}
T.gPerishSongMusicNote2SpriteTemplate = {tag="MUSIC_NOTES_2",w=16,h=16,aff=1,blend=0,anims={A.sWavyMusicNotesAnimCmds1,A.sWavyMusicNotesAnimCmds2,A.sWavyMusicNotesAnimCmds3,A.sWavyMusicNotesAnimCmds4,A.sWavyMusicNotesAnimCmds5,A.sWavyMusicNotesAnimCmds6,A.sWavyMusicNotesAnimCmds7,A.sWavyMusicNotesAnimCmds8},affine={F.sPerishSongMusicNoteAffineAnimCmds1,F.sPerishSongMusicNoteAffineAnimCmds2,F.sPerishSongMusicNoteAffineAnimCmds3}}
T.gPerishSongMusicNoteSpriteTemplate = {tag="MUSIC_NOTES_2",w=16,h=16,aff=1,blend=0,anims={A.sWavyMusicNotesAnimCmds1,A.sWavyMusicNotesAnimCmds2,A.sWavyMusicNotesAnimCmds3,A.sWavyMusicNotesAnimCmds4,A.sWavyMusicNotesAnimCmds5,A.sWavyMusicNotesAnimCmds6,A.sWavyMusicNotesAnimCmds7,A.sWavyMusicNotesAnimCmds8},affine={F.sPerishSongMusicNoteAffineAnimCmds1,F.sPerishSongMusicNoteAffineAnimCmds2,F.sPerishSongMusicNoteAffineAnimCmds3}}
T.gPersistHitSplatSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gPetalDanceBigFlowerSpriteTemplate = {tag="FLOWER",w=16,h=16,aff=0,blend=0,anims={A.sPetalDanceBigFlowerAnimCmds}}
T.gPetalDanceSmallFlowerSpriteTemplate = {tag="FLOWER",w=8,h=8,aff=0,blend=0,anims={A.sPetalDanceSmallFlowerAnimCmds}}
T.gPinMissileSpriteTemplate = {tag="NEEDLE",w=16,h=16,aff=1,blend=0}
T.gPinkHeartSpriteTemplate = {tag="PINK_HEART",w=16,h=16,aff=0,blend=0}
T.gPoisonBubbleSpriteTemplate = {tag="POISON_BUBBLE",w=16,h=16,aff=1,blend=0,anims={A.sAnim_PoisonProjectile},affine={F.sAffineAnim_Bubble}}
T.gPoisonGasCloudSpriteTemplate = {tag="PURPLE_GAS_CLOUD",w=32,h=16,aff=0,blend=1,anims={A.sAnim_Cloud}}
T.gPoisonPowderParticleSpriteTemplate = {tag="POISON_POWDER",w=8,h=16,aff=0,blend=0,anims={A.sPowderParticlesAnimCmds}}
T.gPowderSnowSnowballSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=0,anims={A.sAnim_Snowball}}
T.gPowerAbsorptionOrbSpriteTemplate = {tag="ORBS",w=16,h=16,aff=1,blend=1,anims={A.sPowerAbsorptionOrbAnimCmds},affine={F.sPowerAbsorptionOrbAffineAnimCmds}}
T.gPresentHealParticleSpriteTemplate = {tag="GREEN_SPARKLE",w=16,h=16,aff=0,blend=0,anims={A.sPresentHealParticleAnimCmds}}
T.gPresentSpriteTemplate = {tag="ITEM_BAG",w=32,h=32,aff=1,blend=0,anims={A.sFallingBagAnimCmds},affine={F.sFallingBagAffineAnimCmds1,F.sFallingBagAffineAnimCmds2}}
T.gProtectSpriteTemplate = {tag="PROTECT",w=64,h=64,aff=0,blend=1}
T.gPsychUpSpiralSpriteTemplate = {tag="SPIRAL",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_PsychUpSpiral}}
T.gPsychoBoostOrbSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=3,blend=1,affine={F.sAffineAnim_PsychoBoostOrb_0,F.sAffineAnim_PsychoBoostOrb_1}}
T.gPsywaveRingSpriteTemplate = {tag="BLUE_RING",w=16,h=32,aff=3,blend=0,affine={F.sGrowingRingAffineAnimCmds}}
T.gQuestionMarkSpriteTemplate = {tag="AMNESIA",w=32,h=32,aff=0,blend=0,anims={A.sAnim_QuestionMark}}
T.gRainDropSpriteTemplate = {tag="RAIN_DROPS",w=16,h=32,aff=0,blend=0,anims={A.sAnim_RainDrop}}
T.gRandomPosHitSplatSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gRapidSpinSpriteTemplate = {tag="RAPID_SPIN",w=32,h=16,aff=0,blend=0,anims={A.sRapidSpinAnimCmds}}
T.gRazorLeafCutterSpriteTemplate = {tag="RAZOR_LEAF",w=32,h=16,aff=0,blend=0,anims={A.sRazorLeafCutterAnimCmds}}
T.gRazorLeafParticleSpriteTemplate = {tag="LEAF",w=16,h=16,aff=0,blend=0,anims={A.sRazorLeafParticleAnimCmds1,A.sRazorLeafParticleAnimCmds2}}
T.gRazorWindTornadoSpriteTemplate = {tag="GUST",w=32,h=64,aff=1,blend=0,affine={F.sRazorWindTornadoAffineAnimCmds}}
T.gRecycleSpriteTemplate = {tag="RECYCLE",w=64,h=64,aff=1,blend=1,affine={F.sRecycleSpriteAffineAnimCmds}}
T.gRedHeartBurstSpriteTemplate = {tag="RED_HEART",w=16,h=16,aff=0,blend=0}
T.gRedHeartProjectileSpriteTemplate = {tag="RED_HEART",w=16,h=16,aff=0,blend=0}
T.gRedHeartRisingSpriteTemplate = {tag="RED_HEART",w=16,h=16,aff=0,blend=0}
T.gRedXSpriteTemplate = {tag="X_SIGN",w=64,h=64,aff=0,blend=0}
T.gReflectSparkleSpriteTemplate = {tag="SPARKLE_4",w=32,h=32,aff=0,blend=0,anims={A.sAnim_ReflectSparkle}}
T.gReflectWallSpriteTemplate = {tag="BLUE_LIGHT_WALL",w=64,h=64,aff=0,blend=1}
T.gRevengeBigScratchSpriteTemplate = {tag="PURPLE_SWIPE",w=64,h=64,aff=0,blend=0,anims={A.sAnim_RevengeBigScratch_0,A.sAnim_RevengeBigScratch_1,A.sAnim_RevengeBigScratch_2}}
T.gRevengeSmallScratchSpriteTemplate = {tag="PURPLE_SCRATCH",w=32,h=32,aff=0,blend=0,anims={A.sAnim_RevengeSmallScratch_0,A.sAnim_RevengeSmallScratch_1,A.sAnim_RevengeSmallScratch_2}}
T.gReversalOrbSpriteTemplate = {tag="BLUE_ORB",w=8,h=8,aff=0,blend=0}
T.gRoarNoiseLineSpriteTemplate = {tag="NOISE_LINE",w=32,h=32,aff=0,blend=0,anims={A.sRoarNoiseLineAnimCmds1,A.sRoarNoiseLineAnimCmds2}}
T.gRockBlastRockSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=1,blend=0,anims={A.sAnim_Rock_Biggest,A.sAnim_Rock_Bigger,A.sAnim_Rock_Big,A.sAnim_Rock_Small,A.sAnim_Rock_Smaller,A.sAnim_Rock_Smallest},affine={F.sAffineAnim_BasicRock_0,F.sAffineAnim_BasicRock_1}}
T.gRockFragmentSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FlyingRock_0,A.sAnim_FlyingRock_1,A.sAnim_FlyingRock_2}}
T.gRockScatterSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=1,blend=0,anims={A.sAnim_Rock_Biggest,A.sAnim_Rock_Bigger,A.sAnim_Rock_Big,A.sAnim_Rock_Small,A.sAnim_Rock_Smaller,A.sAnim_Rock_Smallest},affine={F.sAffineAnim_BasicRock_0,F.sAffineAnim_BasicRock_1}}
T.gRockTombRockSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Rock_Biggest,A.sAnim_Rock_Bigger,A.sAnim_Rock_Big,A.sAnim_Rock_Small,A.sAnim_Rock_Smaller,A.sAnim_Rock_Smallest}}
T.gRolloutMudSpriteTemplate = {tag="MUD_SAND",w=8,h=8,aff=0,blend=0}
T.gRolloutRockSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0}
T.gSafariBaitSpriteTemplate = {tag="SAFARI_BAIT",w=16,h=16,aff=0,blend=0}
T.gSafariRockTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0,anims={A.sSpriteAnim_SafariRock_0}}
T.gSandAttackDirtSpriteTemplate = {tag="MUD_SAND",w=8,h=8,aff=0,blend=0}
T.gScratchSpriteTemplate = {tag="SCRATCH",w=32,h=32,aff=0,blend=1,anims={A.sScratchAnimCmds}}
T.gScreechRingSpriteTemplate = {tag="PURPLE_RING",w=16,h=32,aff=3,blend=0,affine={F.sGrowingRingAffineAnimCmds}}
T.gShadowBallSpriteTemplate = {tag="SHADOW_BALL",w=32,h=32,aff=1,blend=0,affine={F.sAffineAnim_ShadowBall}}
T.gShakeMonOrTerrainSpriteTemplate = {tag="0"}
T.gSharpTeethSpriteTemplate = {tag="SHARP_TEETH",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_Bite_0,F.sAffineAnim_Bite_1,F.sAffineAnim_Bite_2,F.sAffineAnim_Bite_3,F.sAffineAnim_Bite_4,F.sAffineAnim_Bite_5,F.sAffineAnim_Bite_6,F.sAffineAnim_Bite_7}}
T.gSharpenSphereSpriteTemplate = {tag="SPHERE_TO_CUBE",w=32,h=32,aff=0,blend=0,anims={A.sSharpenSphereAnimCmds}}
T.gSignalBeamGreenOrbSpriteTemplate = {tag="GLOWY_GREEN_ORB",w=8,h=8,aff=0,blend=0}
T.gSignalBeamRedOrbSpriteTemplate = {tag="GLOWY_RED_ORB",w=8,h=8,aff=0,blend=0}
T.gSilverWindBigSparkSpriteTemplate = {tag="SPARKLE_6",w=16,h=16,aff=1,blend=0,affine={F.sSilverWindBigSparkAffineAnimCmds}}
T.gSilverWindMediumSparkSpriteTemplate = {tag="SPARKLE_6",w=16,h=16,aff=1,blend=0,affine={F.sSilverWindMediumSparkAffineAnimCmds}}
T.gSilverWindSmallSparkSpriteTemplate = {tag="SPARKLE_6",w=16,h=16,aff=1,blend=0,affine={F.sSilverWindSmallSparkAffineAnimCmds}}
T.gSimplePaletteBlendSpriteTemplate = {tag="0"}
T.gSkyAttackBirdSpriteTemplate = {tag="BIRD",w=64,h=64,aff=3,blend=0}
T.gSlamHitSpriteTemplate = {tag="SLAM_HIT",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Whip,A.sAnim_Whip_Flipped}}
T.gSlashSliceSpriteTemplate = {tag="SLASH",w=32,h=32,aff=0,blend=0,anims={A.sSlashSliceAnimCmds1,A.sSlashSliceAnimCmds2}}
T.gSleepLetterZSpriteTemplate = {tag="LETTER_Z",w=32,h=32,aff=1,blend=0,anims={A.sSleepLetterZAnimCmds},affine={F.sSleepLetterZAffineAnimCmds1,F.sSleepLetterZAffineAnimCmds2}}
T.gSleepPowderParticleSpriteTemplate = {tag="SLEEP_POWDER",w=8,h=16,aff=0,blend=0,anims={A.sPowderParticlesAnimCmds}}
T.gSlideMonToOffsetAndBackSpriteTemplate = {tag="0"}
T.gSlideMonToOffsetSpriteTemplate = {tag="0"}
T.gSlideMonToOriginalPosSpriteTemplate = {tag="0"}
T.gSlidingKickSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gSlowFlyingMusicNotesSpriteTemplate = {tag="MUSIC_NOTES",w=16,h=16,aff=3,blend=0,anims={A.sWavyMusicNotesAnimCmds1,A.sWavyMusicNotesAnimCmds2,A.sWavyMusicNotesAnimCmds3,A.sWavyMusicNotesAnimCmds4,A.sWavyMusicNotesAnimCmds5,A.sWavyMusicNotesAnimCmds6,A.sWavyMusicNotesAnimCmds7,A.sWavyMusicNotesAnimCmds8},affine={F.sSlowFlyingMusicNotesAffineAnimCmds}}
T.gSludgeBombHitParticleSpriteTemplate = {tag="POISON_BUBBLE",w=16,h=16,aff=1,blend=0,anims={A.sAnim_SludgeBombHit},affine={F.sAffineAnim_SludgeBombHit}}
T.gSludgeProjectileSpriteTemplate = {tag="POISON_BUBBLE",w=16,h=16,aff=3,blend=0,anims={A.sAnim_PoisonProjectile},affine={F.sAffineAnim_PoisonProjectile}}
T.gSmallBubblePairSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=0,anims={A.sAnim_SmallBubblePair}}
T.gSmallDriftingBubblesSpriteTemplate = {tag="SMALL_BUBBLES",w=8,h=8,aff=0,blend=0}
T.gSmallWaterOrbSpriteTemplate = {tag="GLOWY_BLUE_ORB",w=8,h=8,aff=0,blend=0}
T.gSmellingSaltExclamationSpriteTemplate = {tag="SMELLINGSALT_EFFECT",w=32,h=32,aff=0,blend=0}
T.gSmellingSaltsHandSpriteTemplate = {tag="TAG_HAND",w=32,h=32,aff=0,blend=0}
T.gSmogCloudSpriteTemplate = {tag="PURPLE_GAS_CLOUD",w=32,h=16,aff=0,blend=1,anims={A.sAnim_Cloud}}
T.gSmokeBallEscapeCloudSpriteTemplate = {tag="PINK_CLOUD",w=32,h=32,aff=3,blend=0,affine={F.sSmokeBallEscapeCloudAffineAnimCmds1,F.sSmokeBallEscapeCloudAffineAnimCmds2,F.sSmokeBallEscapeCloudAffineAnimCmds3,F.sSmokeBallEscapeCloudAffineAnimCmds4}}
T.gSnoreZSpriteTemplate = {tag="SNORE_Z",w=32,h=32,aff=0,blend=0}
T.gSoftBoiledEggSpriteTemplate = {tag="BREAKING_EGG",w=32,h=32,aff=3,blend=1,affine={F.sSoftBoiledEggAffineAnimCmds1,F.sSoftBoiledEggAffineAnimCmds2,F.sSoftBoiledEggAffineAnimCmds3}}
T.gSolarBeamBigOrbSpriteTemplate = {tag="ORBS",w=8,h=8,aff=0,blend=0,anims={A.sSolarBeamBigOrbAnimCmds1,A.sSolarBeamBigOrbAnimCmds2,A.sSolarBeamBigOrbAnimCmds3,A.sSolarBeamBigOrbAnimCmds4,A.sSolarBeamBigOrbAnimCmds5,A.sSolarBeamBigOrbAnimCmds6,A.sSolarBeamBigOrbAnimCmds7}}
T.gSolarBeamSmallOrbSpriteTemplate = {tag="ORBS",w=8,h=8,aff=0,blend=0,anims={A.sSolarBeamSmallOrbAnimCms}}
T.gSonicBoomSpriteTemplate = {tag="AIR_WAVE",w=32,h=16,aff=3,blend=1}
T.gSparkElectricityFlashingSpriteTemplate = {tag="SPARK_2",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_FlashingSpark}}
T.gSparkElectricitySpriteTemplate = {tag="SPARK_2",w=16,h=16,aff=1,blend=0}
T.gSparklingStarsSpriteTemplate = {tag="SPARKLE_2",w=32,h=32,aff=0,blend=0,anims={A.sGrantingStarsAnimCmds}}
T.gSpecialScreenSparkleSpriteTemplate = {tag="SPARKLE_3",w=16,h=16,aff=0,blend=0,anims={A.sAnim_SpecialScreenSparkle}}
T.gSpeedDustSpriteTemplate = {tag="SPEED_DUST",w=16,h=16,aff=0,blend=0,anims={A.sSpeedDustAnimCmds}}
T.gSpiderWebSpriteTemplate = {tag="SPIDER_WEB",w=64,h=64,aff=3,blend=1,affine={F.sAffineAnim_SpiderWeb}}
T.gSpikesSpriteTemplate = {tag="SPIKES",w=16,h=16,aff=0,blend=0}
T.gSpinningBoneSpriteTemplate = {tag="BONE",w=32,h=32,aff=1,blend=0,affine={F.sAffineAnim_SpinningBone}}
T.gSpinningHandOrFootSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=3,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight},affine={F.sAffineAnim_SpinningHandOrFoot}}
T.gSpinningSparkleSpriteTemplate = {tag="SPARKLE_4",w=32,h=32,aff=0,blend=0,anims={A.sAnim_SpinningSparkle}}
T.gSpitUpOrbSpriteTemplate = {tag="RED_ORB_2",w=8,h=8,aff=3,blend=0,affine={F.sSpitUpOrbAffineAnimCmds}}
T.gSporeParticleSpriteTemplate = {tag="SPORE",w=16,h=16,aff=0,blend=0,anims={A.sSporeParticleAnimCmds1,A.sSporeParticleAnimCmds2}}
T.gSpotlightSpriteTemplate = {tag="SPOTLIGHT",w=64,h=64,aff=3,blend=0,affine={F.sSpotlightAffineAnimCmds1,F.sSpotlightAffineAnimCmds2}}
T.gSprayWaterDropletSpriteTemplate = {tag="SWEAT_BEAD",w=8,h=8,aff=0,blend=0}
T.gSpriteTemplate_EnemyShadow = {tag="GFXTAG_SHADOW"}
T.gStockpileAbsorptionOrbSpriteTemplate = {tag="GRAY_ORB",w=8,h=8,aff=3,blend=0,affine={F.sStockpileAbsorptionOrbAffineCmds}}
T.gStompFootSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Fist,A.sAnim_FootWide,A.sAnim_FootTall,A.sAnim_HandLeft,A.sAnim_HandRight}}
T.gStringWrapSpriteTemplate = {tag="STRING",w=64,h=32,aff=0,blend=0}
T.gStunSporeParticleSpriteTemplate = {tag="STUN_SPORE",w=8,h=16,aff=0,blend=0,anims={A.sPowderParticlesAnimCmds}}
T.gSunlightRaySpriteTemplate = {tag="SUNLIGHT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_SunlightRay}}
T.gSuperFangSpriteTemplate = {tag="FANG_ATTACK",w=32,h=32,aff=0,blend=0,anims={A.sSuperFangAnimCmds}}
T.gSuperpowerFireballSpriteTemplate = {tag="METEOR",w=64,h=64,aff=0,blend=0}
T.gSuperpowerOrbSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=3,blend=1,affine={F.sAffineAnim_SuperpowerOrb}}
T.gSuperpowerRockSpriteTemplate = {tag="FLAT_ROCK",w=16,h=16,aff=0,blend=0}
T.gSupersonicRingSpriteTemplate = {tag="GOLD_RING",w=16,h=32,aff=3,blend=0,affine={F.sGrowingRingAffineAnimCmds}}
T.gSwallowBlueOrbSpriteTemplate = {tag="BLUE_ORB",w=8,h=8,aff=0,blend=0}
T.gSweetScentPetalSpriteTemplate = {tag="PINK_PETAL",w=8,h=8,aff=0,blend=0,anims={A.sSweetScentPetalAnimCmds1,A.sSweetScentPetalAnimCmds2,A.sSweetScentPetalAnimCmds3}}
T.gSwiftStarSpriteTemplate = {tag="YELLOW_STAR",w=32,h=32,aff=1,blend=0,affine={F.sSwiftStarAffineAnimCmds}}
T.gSwirlingDirtSpriteTemplate = {tag="MUD_SAND",w=8,h=8,aff=0,blend=0}
T.gSwirlingSnowballSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=0,anims={A.sAnim_Snowball}}
T.gSwordsDanceBladeSpriteTemplate = {tag="SWORD",w=32,h=64,aff=1,blend=1,affine={F.sSwordsDanceBladeAffineAnimCmds}}
T.gTailGlowOrbSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_TailGlowOrb}}
T.gTauntFingerSpriteTemplate = {tag="FINGER_2",w=32,h=32,aff=0,blend=0,anims={A.sTauntFingerAnimCmds1,A.sTauntFingerAnimCmds2,A.sTauntFingerAnimCmds3,A.sTauntFingerAnimCmds4}}
T.gTealAlertSpriteTemplate = {tag="TEAL_ALERT",w=32,h=32,aff=1,blend=0}
T.gTearDropSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_TearDrop_0,F.sAffineAnim_TearDrop_1}}
T.gThinRingExpandingSpriteTemplate = {tag="THIN_RING",w=64,h=64,aff=3,blend=0,affine={F.sThinRingExpandingAffineAnimCmds1,F.sThinRingExpandingAffineAnimCmds2}}
T.gThinRingShrinkingSpriteTemplate = {tag="THIN_RING",w=64,h=64,aff=3,blend=1,affine={F.sThinRingShrinkingAffineAnimCmds}}
T.gThoughtBubbleSpriteTemplate = {tag="THOUGHT_BUBBLE",w=32,h=32,aff=0,blend=0,anims={A.sMetronomeThroughtBubbleAnimCmds1,A.sMetronomeThroughtBubbleAnimCmds2,A.sMetronomeThroughtBubbleAnimCmds3,A.sMetronomeThroughtBubbleAnimCmds4}}
T.gThunderWaveSpriteTemplate = {tag="SPARK_H",w=32,h=16,aff=0,blend=0}
T.gThunderboltOrbSpriteTemplate = {tag="SHOCK_3",w=32,h=32,aff=1,blend=0,anims={A.sAnim_ThunderboltOrb},affine={F.sAffineAnim_ThunderboltOrb}}
T.gToxicBubbleSpriteTemplate = {tag="TOXIC_BUBBLE",w=16,h=32,aff=0,blend=0,anims={A.sAnim_ToxicBubble}}
T.gTriAttackTriangleSpriteTemplate = {tag="TRI_ATTACK_TRIANGLE",w=64,h=64,aff=3,blend=0,anims={A.sTriAttackTriangleAnimCmds},affine={F.sTriAttackTriangleAffineAnimCmds}}
T.gTrickBagSpriteTemplate = {tag="ITEM_BAG",w=32,h=32,aff=1,blend=0,anims={A.sFallingBagAnimCmds},affine={F.sTrickBagAffineAnimCmds1,F.sTrickBagAffineAnimCmds2,F.sFallingBagAffineAnimCmds1,F.sFallingBagAffineAnimCmds2}}
T.gTwisterLeafSpriteTemplate = {tag="LEAF",w=16,h=16,aff=0,blend=0,anims={A.sRazorLeafParticleAnimCmds1,A.sRazorLeafParticleAnimCmds2}}
T.gTwisterRockSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Rock_Biggest,A.sAnim_Rock_Bigger,A.sAnim_Rock_Big,A.sAnim_Rock_Small,A.sAnim_Rock_Smaller,A.sAnim_Rock_Smallest},affine={F.sAffineAnim_BasicRock_0,F.sAffineAnim_BasicRock_1}}
T.gUproarRingSpriteTemplate = {tag="THIN_RING",w=64,h=64,aff=3,blend=1,affine={F.sThinRingExpandingAffineAnimCmds1,F.sThinRingExpandingAffineAnimCmds2}}
T.gVerticalDipSpriteTemplate = {tag="0"}
T.gViceGripSpriteTemplate = {tag="CUT",w=32,h=32,aff=0,blend=1,anims={A.sViceGripAnimCmds1,A.sViceGripAnimCmds2}}
T.gVineWhipSpriteTemplate = {tag="WHIP_HIT",w=32,h=32,aff=0,blend=0,anims={A.sAnim_Whip,A.sAnim_Whip_Flipped}}
T.gVoltTackleBoltSpriteTemplate = {tag="SPARK",w=8,h=16,aff=3,blend=0,anims={A.sAnim_VoltTackleBolt_0,A.sAnim_VoltTackleBolt_1,A.sAnim_VoltTackleBolt_2,A.sAnim_VoltTackleBolt_3},affine={F.sAffineAnim_VoltTackleBolt}}
T.gVoltTackleOrbSlideSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_GrowingElectricOrb_0,F.sAffineAnim_GrowingElectricOrb_1,F.sAffineAnim_GrowingElectricOrb_2}}
T.gWaterBubbleProjectileSpriteTemplate = {tag="BUBBLE",w=16,h=16,aff=1,blend=1,anims={A.sAnim_WaterBubbleProjectile},affine={F.sAffineAnim_WaterBubbleProjectile}}
T.gWaterBubbleSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=1,blend=1,anims={A.sAnim_WaterBubble},affine={F.sAffineAnim_Bubble}}
T.gWaterGunDropletSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=3,blend=1,anims={A.sAnim_WaterGunDroplet},affine={F.sAffineAnim_AcidPoisonDroplet}}
T.gWaterGunProjectileSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=0,blend=1,anims={A.sAnim_WaterBubble}}
T.gWaterHitSplatSpriteTemplate = {tag="WATER_IMPACT",w=32,h=32,aff=1,blend=1,affine={F.sAffineAnim_HitSplat_0,F.sAffineAnim_HitSplat_1,F.sAffineAnim_HitSplat_2,F.sAffineAnim_HitSplat_3}}
T.gWaterPulseBubbleSpriteTemplate = {tag="SMALL_BUBBLES",w=8,h=8,aff=0,blend=0,anims={A.sAnim_WaterPulseBubble_0,A.sAnim_WaterPulseBubble_1}}
T.gWaterPulseRingBubbleSpriteTemplate = {tag="SMALL_BUBBLES",w=8,h=8,aff=1,blend=0,anims={A.sAnim_WaterPulseBubble_0,A.sAnim_WaterPulseBubble_1},affine={F.sAffineAnim_WaterPulseRingBubble_0,F.sAffineAnim_WaterPulseRingBubble_1}}
T.gWaterPulseRingSpriteTemplate = {tag="BLUE_RING_2",w=16,h=32,aff=3,blend=0,affine={F.sWaterPulseRingAffineAnimCmds}}
T.gWavyMusicNotesSpriteTemplate = {tag="MUSIC_NOTES",w=16,h=16,aff=3,blend=0,anims={A.sWavyMusicNotesAnimCmds1,A.sWavyMusicNotesAnimCmds2,A.sWavyMusicNotesAnimCmds3,A.sWavyMusicNotesAnimCmds4,A.sWavyMusicNotesAnimCmds5,A.sWavyMusicNotesAnimCmds6,A.sWavyMusicNotesAnimCmds7,A.sWavyMusicNotesAnimCmds8},affine={F.sWavyMusicNotesAffineAnimCmds}}
T.gWeakFrustrationAngerMarkSpriteTemplate = {tag="ANGER",w=16,h=16,aff=0,blend=0}
T.gWeatherBallFireDownSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_BasicFire}}
T.gWeatherBallIceDownSpriteTemplate = {tag="HAIL",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_WeatherBallIceDown}}
T.gWeatherBallNormalDownSpriteTemplate = {tag="WEATHER_BALL",w=32,h=32,aff=0,blend=0,anims={A.sAnim_WeatherBallNormal}}
T.gWeatherBallRockDownSpriteTemplate = {tag="ROCKS",w=32,h=32,aff=1,blend=0,anims={A.sAnim_Rock_Biggest,A.sAnim_Rock_Bigger,A.sAnim_Rock_Big,A.sAnim_Rock_Small,A.sAnim_Rock_Smaller,A.sAnim_Rock_Smallest},affine={F.sAffineAnim_BasicRock_0,F.sAffineAnim_BasicRock_1}}
T.gWeatherBallUpSpriteTemplate = {tag="WEATHER_BALL",w=32,h=32,aff=0,blend=0,anims={A.sAnim_WeatherBallNormal}}
T.gWeatherBallWaterDownSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=1,blend=0,anims={A.sAnim_WeatherBallWaterDown},affine={F.sAffineAnim_WeatherBallWaterDown}}
T.gWebThreadSpriteTemplate = {tag="WEB_THREAD",w=8,h=8,aff=0,blend=0}
T.gWhirlpoolSpriteTemplate = {tag="WATER_ORB",w=16,h=16,aff=1,blend=1,anims={A.sAnim_WaterMudOrb},affine={F.sAffineAnim_Whirlpool}}
T.gWhirlwindLineSpriteTemplate = {tag="WHIRLWIND_LINES",w=32,h=16,aff=0,blend=0,anims={A.sAnim_WhirlwindLines}}
T.gWhiteHaloSpriteTemplate = {tag="ROUND_WHITE_HALO",w=64,h=64,aff=0,blend=1}
T.gWillOWispFireSpriteTemplate = {tag="WISP_FIRE",w=32,h=32,aff=0,blend=0,anims={A.sAnim_WillOWispFire}}
T.gWillOWispOrbSpriteTemplate = {tag="WISP_ORB",w=16,h=16,aff=0,blend=0,anims={A.sAnim_WillOWispOrb_0,A.sAnim_WillOWispOrb_1,A.sAnim_WillOWispOrb_2,A.sAnim_WillOWispOrb_3}}
T.gWishStarSpriteTemplate = {tag="GOLD_STARS",w=16,h=16,aff=0,blend=0}
T.gYawnCloudSpriteTemplate = {tag="PINK_CLOUD",w=32,h=32,aff=1,blend=0,affine={F.sYawnCloudAffineAnimCmds1,F.sYawnCloudAffineAnimCmds2,F.sYawnCloudAffineAnimCmds3}}
T.gZapCannonBallSpriteTemplate = {tag="BLACK_BALL_2",w=16,h=16,aff=0,blend=0}
T.gZapCannonSparkSpriteTemplate = {tag="SPARK_2",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_FlashingSpark}}
T.sBouncingMusicNoteSpriteTemplate = {tag="MUSIC_NOTES",w=16,h=16,aff=0,blend=0}
T.sBubbleBurstSpriteTemplate = {tag="BUBBLE_BURST",w=16,h=16,aff=0,blend=0,anims={A.sAnim_BubbleBurst,A.sAnim_BubbleBurst_Flipped}}
T.sCirclingFingerSpriteTemplate = {tag="FINGER",w=32,h=32,aff=0,blend=0}
T.sCirclingMusicNoteSpriteTemplate = {tag="MUSIC_NOTES",w=16,h=16,aff=0,blend=0,anims={A.sAnim_CirclingMusicNote_Eighth,A.sAnim_CirclingMusicNote_BeamedEighth,A.sAnim_CirclingMusicNote_SlantedBeamedEighth,A.sAnim_CirclingMusicNote_Quarter,A.sAnim_CirclingMusicNote_QuarterRest,A.sAnim_CirclingMusicNote_EighthRest,A.sAnim_CirclingMusicNote_Eighth_Flipped,A.sAnim_CirclingMusicNote_BeamedEighth_Flipped,A.sAnim_CirclingMusicNote_SlantedBeamedEighth_Flipped,A.sAnim_CirclingMusicNote_Quarter_Flipped}}
T.sCirclingSparkleSpriteTemplate = {tag="SPARKLE_4",w=32,h=32,aff=0,blend=0,anims={A.sAnim_CirclingSparkle}}
T.sElectricBoltSegmentSpriteTemplate = {tag="SPARK",w=8,h=8,aff=0,blend=0}
T.sFlashingCircleImpactSpriteTemplate = {tag="CIRCLE_IMPACT",w=8,h=8,aff=0,blend=0}
T.sFlickeringFootSpriteTemplate = {tag="MONSTER_FOOT",w=32,h=32,aff=0,blend=0}
T.sFlickeringImpactSpriteTemplate = {tag="IMPACT",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FlickeringImpact_0,A.sAnim_FlickeringImpact_1,A.sAnim_FlickeringImpact_2}}
T.sFlickeringOrbFlippedSpriteTemplate = {tag="ORB",w=16,h=16,aff=0,blend=0,anims={A.sAnim_FlickeringOrb}}
T.sFlickeringOrbSpriteTemplate = {tag="ORB",w=16,h=16,aff=0,blend=0,anims={A.sAnim_FlickeringOrb}}
T.sFlickeringPunchSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=1,blend=0,affine={F.sAffineAnim_FlickeringPunch_Normal,F.sAffineAnim_FlickeringPunch_TurnedTopLeft,F.sAffineAnim_FlickeringPunch_TurnedLeft,F.sAffineAnim_FlickeringPunch_TurnedBottomLeft,F.sAffineAnim_FlickeringPunch_UpsideDown,F.sAffineAnim_FlickeringPunch_TurnedBottomRight,F.sAffineAnim_FlickeringPunch_TurnedRight,F.sAffineAnim_FlickeringPunch_TurnedTopRight}}
T.sFlickeringShrinkOrbSpriteTemplate = {tag="ORB",w=16,h=16,aff=3,blend=0,anims={A.sAnim_FlickeringShrinkOrb},affine={F.sAffineAnim_FlickeringShrinkOrb}}
T.sFrozenIceCubeSpriteTemplate = {tag="ICE_CUBE",w=64,h=64,aff=0,blend=1}
T.sHailParticleSpriteTemplate = {tag="HAIL",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_HailParticle_0,F.sAffineAnim_HailParticle_1,F.sAffineAnim_HailParticle_2}}
T.sImprisonOrbSpriteTemplate = {tag="HOLLOW_ORB",w=16,h=16,aff=0,blend=1}
T.sMonMoveCircularSpriteTemplate = {tag="0"}
T.sMovingClampSpriteTemplate = {tag="CLAMP",w=64,h=64,aff=1,blend=1,affine={F.sAffineAnim_Bite_0,F.sAffineAnim_Bite_1,F.sAffineAnim_Bite_2,F.sAffineAnim_Bite_3,F.sAffineAnim_Bite_4,F.sAffineAnim_Bite_5,F.sAffineAnim_Bite_6,F.sAffineAnim_Bite_7}}
T.sShockWaveProgressingBoltSpriteTemplate = {tag="SPARK",w=8,h=8,aff=0,blend=0}
T.sSkillSwapOrbSpriteTemplate = {tag="BLUEGREEN_ORB",w=16,h=16,aff=1,blend=0,affine={F.sAffineAnim_SkillSwapOrb_0,F.sAffineAnim_SkillSwapOrb_1,F.sAffineAnim_SkillSwapOrb_2,F.sAffineAnim_SkillSwapOrb_3}}
T.sSlidingHit1SpriteTemplate = {tag="HIT",w=32,h=32,aff=0,blend=0,anims={A.sAnim_SlidingHit}}
T.sSlidingHit2SpriteTemplate = {tag="HIT_2",w=32,h=32,aff=0,blend=0,anims={A.sAnim_SlidingHit}}
T.sSmallExplosionSpriteTemplate = {tag="EXPLOSION_6",w=32,h=32,aff=1,blend=0,anims={A.sAnim_SmallExplosion},affine={F.sAffineAnim_SmallExplosion}}
T.sSmokescreenImpactSpriteTemplate = {tag="TAG_SMOKESCREEN",anims={A.sAnim_SmokescreenImpact_0,A.sAnim_SmokescreenImpact_1,A.sAnim_SmokescreenImpact_2,A.sAnim_SmokescreenImpact_3}}
T.sTipMonSpriteTemplate = {tag="0"}
T.sUnusedBagStealSpriteTemplate = {tag="TIED_BAG",w=16,h=16,aff=0,blend=0}
T.sUnusedBubbleThrowSpriteTemplate = {tag="SMALL_BUBBLES",w=16,h=16,aff=0,blend=0}
T.sUnusedCirclingShockSpriteTemplate = {tag="SHOCK",w=32,h=32,aff=0,blend=0,anims={A.sAnim_UnusedCirclingShock}}
T.sUnusedEmberFirePlumeSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_FirePlume}}
T.sUnusedFeatherSpriteTemplate = {tag="WHITE_FEATHER",w=32,h=32,aff=1,blend=0,anims={A.sAnim_FallingFeather_0,A.sAnim_FallingFeather_1}}
T.sUnusedFlashingLightSpriteTemplate = {tag="CIRCLE_OF_LIGHT",w=64,h=64,aff=0,blend=1}
T.sUnusedHumanoidFootSpriteTemplate = {tag="HUMANOID_FOOT",w=32,h=32,aff=0,blend=0}
T.sUnusedIceCrystalThrowSpriteTemplate = {tag="ICE_CRYSTALS",w=8,h=8,aff=0,blend=0}
T.sUnusedItemBagStealSpriteTemplate = {tag="ITEM_BAG",w=32,h=32,aff=0,blend=0}
T.sUnusedSmallEmberSpriteTemplate = {tag="SMALL_EMBER",w=32,h=32,aff=0,blend=0,anims={A.sAnim_UnusedSmallEmber}}
T.sUnusedSpinningFistSpriteTemplate = {tag="HANDS_AND_FEET",w=32,h=32,aff=1,blend=0,affine={F.sAffineAnim_UnusedSpinningFist}}
T.sUnusedStarBurstSpriteTemplate = {tag="GOLD_STARS",w=16,h=16,aff=0,blend=0}
T.sVibrateBattlerBackSpriteTemplate = {tag="0"}
T.sVoidLinesSpriteTemplate = {tag="VOID_LINES",w=64,h=64,aff=0,blend=1}
return { anims = A, affine = F, templates = T }
