-- Canonical Gen 3 (FireRed) Move Table builtin fallback.
-- Generated from pokefirered battle_moves.h and move_names.h.
local BuiltinMoves = {
  [0] = { id = 0, name = "-$$$$$$", pp = 0, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "HIT" },
  [1] = { id = 1, name = "POUND", pp = 35, power = 40, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIT" },
  [2] = { id = 2, name = "KARATE CHOP", pp = 25, power = 50, accuracy = 100, type = "FIGHTING", priority = 0, effect = "HIGH_CRITICAL" },
  [3] = { id = 3, name = "DOUBLESLAP", pp = 10, power = 15, accuracy = 85, type = "NORMAL", priority = 0, effect = "MULTI_HIT" },
  [4] = { id = 4, name = "COMET PUNCH", pp = 15, power = 18, accuracy = 85, type = "NORMAL", priority = 0, effect = "MULTI_HIT" },
  [5] = { id = 5, name = "MEGA PUNCH", pp = 20, power = 80, accuracy = 85, type = "NORMAL", priority = 0, effect = "HIT" },
  [6] = { id = 6, name = "PAY DAY", pp = 20, power = 40, accuracy = 100, type = "NORMAL", priority = 0, effect = "PAY_DAY" },
  [7] = { id = 7, name = "FIRE PUNCH", pp = 15, power = 75, accuracy = 100, type = "FIRE", priority = 0, effect = "BURN_HIT" },
  [8] = { id = 8, name = "ICE PUNCH", pp = 15, power = 75, accuracy = 100, type = "ICE", priority = 0, effect = "FREEZE_HIT" },
  [9] = { id = 9, name = "THUNDERPUNCH", pp = 15, power = 75, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "PARALYZE_HIT" },
  [10] = { id = 10, name = "SCRATCH", pp = 35, power = 40, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIT" },
  [11] = { id = 11, name = "VICEGRIP", pp = 30, power = 55, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIT" },
  [12] = { id = 12, name = "GUILLOTINE", pp = 5, power = 1, accuracy = 30, type = "NORMAL", priority = 0, effect = "OHKO" },
  [13] = { id = 13, name = "RAZOR WIND", pp = 10, power = 80, accuracy = 100, type = "NORMAL", priority = 0, effect = "RAZOR_WIND" },
  [14] = { id = 14, name = "SWORDS DANCE", pp = 30, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "ATTACK_UP_2" },
  [15] = { id = 15, name = "CUT", pp = 30, power = 50, accuracy = 95, type = "NORMAL", priority = 0, effect = "HIT" },
  [16] = { id = 16, name = "GUST", pp = 35, power = 40, accuracy = 100, type = "FLYING", priority = 0, effect = "GUST" },
  [17] = { id = 17, name = "WING ATTACK", pp = 35, power = 60, accuracy = 100, type = "FLYING", priority = 0, effect = "HIT" },
  [18] = { id = 18, name = "WHIRLWIND", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = -6, effect = "ROAR" },
  [19] = { id = 19, name = "FLY", pp = 15, power = 70, accuracy = 95, type = "FLYING", priority = 0, effect = "SEMI_INVULNERABLE" },
  [20] = { id = 20, name = "BIND", pp = 20, power = 15, accuracy = 75, type = "NORMAL", priority = 0, effect = "TRAP" },
  [21] = { id = 21, name = "SLAM", pp = 20, power = 80, accuracy = 75, type = "NORMAL", priority = 0, effect = "HIT" },
  [22] = { id = 22, name = "VINE WHIP", pp = 10, power = 35, accuracy = 100, type = "GRASS", priority = 0, effect = "HIT" },
  [23] = { id = 23, name = "STOMP", pp = 20, power = 65, accuracy = 100, type = "NORMAL", priority = 0, effect = "FLINCH_MINIMIZE_HIT" },
  [24] = { id = 24, name = "DOUBLE KICK", pp = 30, power = 30, accuracy = 100, type = "FIGHTING", priority = 0, effect = "DOUBLE_HIT" },
  [25] = { id = 25, name = "MEGA KICK", pp = 5, power = 120, accuracy = 75, type = "NORMAL", priority = 0, effect = "HIT" },
  [26] = { id = 26, name = "JUMP KICK", pp = 25, power = 70, accuracy = 95, type = "FIGHTING", priority = 0, effect = "RECOIL_IF_MISS" },
  [27] = { id = 27, name = "ROLLING KICK", pp = 15, power = 60, accuracy = 85, type = "FIGHTING", priority = 0, effect = "FLINCH_HIT" },
  [28] = { id = 28, name = "SAND-ATTACK", pp = 15, power = 0, accuracy = 100, type = "GROUND", priority = 0, effect = "ACCURACY_DOWN" },
  [29] = { id = 29, name = "HEADBUTT", pp = 15, power = 70, accuracy = 100, type = "NORMAL", priority = 0, effect = "FLINCH_HIT" },
  [30] = { id = 30, name = "HORN ATTACK", pp = 25, power = 65, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIT" },
  [31] = { id = 31, name = "FURY ATTACK", pp = 20, power = 15, accuracy = 85, type = "NORMAL", priority = 0, effect = "MULTI_HIT" },
  [32] = { id = 32, name = "HORN DRILL", pp = 5, power = 1, accuracy = 30, type = "NORMAL", priority = 0, effect = "OHKO" },
  [33] = { id = 33, name = "TACKLE", pp = 35, power = 35, accuracy = 95, type = "NORMAL", priority = 0, effect = "HIT" },
  [34] = { id = 34, name = "BODY SLAM", pp = 15, power = 85, accuracy = 100, type = "NORMAL", priority = 0, effect = "PARALYZE_HIT" },
  [35] = { id = 35, name = "WRAP", pp = 20, power = 15, accuracy = 85, type = "NORMAL", priority = 0, effect = "TRAP" },
  [36] = { id = 36, name = "TAKE DOWN", pp = 20, power = 90, accuracy = 85, type = "NORMAL", priority = 0, effect = "RECOIL" },
  [37] = { id = 37, name = "THRASH", pp = 20, power = 90, accuracy = 100, type = "NORMAL", priority = 0, effect = "RAMPAGE" },
  [38] = { id = 38, name = "DOUBLE-EDGE", pp = 15, power = 120, accuracy = 100, type = "NORMAL", priority = 0, effect = "DOUBLE_EDGE" },
  [39] = { id = 39, name = "TAIL WHIP", pp = 30, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "DEFENSE_DOWN" },
  [40] = { id = 40, name = "POISON STING", pp = 35, power = 15, accuracy = 100, type = "POISON", priority = 0, effect = "POISON_HIT" },
  [41] = { id = 41, name = "TWINEEDLE", pp = 20, power = 25, accuracy = 100, type = "BUG", priority = 0, effect = "TWINEEDLE" },
  [42] = { id = 42, name = "PIN MISSILE", pp = 20, power = 14, accuracy = 85, type = "BUG", priority = 0, effect = "MULTI_HIT" },
  [43] = { id = 43, name = "LEER", pp = 30, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "DEFENSE_DOWN" },
  [44] = { id = 44, name = "BITE", pp = 25, power = 60, accuracy = 100, type = "DARK", priority = 0, effect = "FLINCH_HIT" },
  [45] = { id = 45, name = "GROWL", pp = 40, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "ATTACK_DOWN" },
  [46] = { id = 46, name = "ROAR", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = -6, effect = "ROAR" },
  [47] = { id = 47, name = "SING", pp = 15, power = 0, accuracy = 55, type = "NORMAL", priority = 0, effect = "SLEEP" },
  [48] = { id = 48, name = "SUPERSONIC", pp = 20, power = 0, accuracy = 55, type = "NORMAL", priority = 0, effect = "CONFUSE" },
  [49] = { id = 49, name = "SONICBOOM", pp = 20, power = 1, accuracy = 90, type = "NORMAL", priority = 0, effect = "SONICBOOM" },
  [50] = { id = 50, name = "DISABLE", pp = 20, power = 0, accuracy = 55, type = "NORMAL", priority = 0, effect = "DISABLE" },
  [51] = { id = 51, name = "ACID", pp = 30, power = 40, accuracy = 100, type = "POISON", priority = 0, effect = "DEFENSE_DOWN_HIT" },
  [52] = { id = 52, name = "EMBER", pp = 25, power = 40, accuracy = 100, type = "FIRE", priority = 0, effect = "BURN_HIT" },
  [53] = { id = 53, name = "FLAMETHROWER", pp = 15, power = 95, accuracy = 100, type = "FIRE", priority = 0, effect = "BURN_HIT" },
  [54] = { id = 54, name = "MIST", pp = 30, power = 0, accuracy = 0, type = "ICE", priority = 0, effect = "MIST" },
  [55] = { id = 55, name = "WATER GUN", pp = 25, power = 40, accuracy = 100, type = "WATER", priority = 0, effect = "HIT" },
  [56] = { id = 56, name = "HYDRO PUMP", pp = 5, power = 120, accuracy = 80, type = "WATER", priority = 0, effect = "HIT" },
  [57] = { id = 57, name = "SURF", pp = 15, power = 95, accuracy = 100, type = "WATER", priority = 0, effect = "HIT" },
  [58] = { id = 58, name = "ICE BEAM", pp = 10, power = 95, accuracy = 100, type = "ICE", priority = 0, effect = "FREEZE_HIT" },
  [59] = { id = 59, name = "BLIZZARD", pp = 5, power = 120, accuracy = 70, type = "ICE", priority = 0, effect = "FREEZE_HIT" },
  [60] = { id = 60, name = "PSYBEAM", pp = 20, power = 65, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "CONFUSE_HIT" },
  [61] = { id = 61, name = "BUBBLEBEAM", pp = 20, power = 65, accuracy = 100, type = "WATER", priority = 0, effect = "SPEED_DOWN_HIT" },
  [62] = { id = 62, name = "AURORA BEAM", pp = 20, power = 65, accuracy = 100, type = "ICE", priority = 0, effect = "ATTACK_DOWN_HIT" },
  [63] = { id = 63, name = "HYPER BEAM", pp = 5, power = 150, accuracy = 90, type = "NORMAL", priority = 0, effect = "RECHARGE" },
  [64] = { id = 64, name = "PECK", pp = 35, power = 35, accuracy = 100, type = "FLYING", priority = 0, effect = "HIT" },
  [65] = { id = 65, name = "DRILL PECK", pp = 20, power = 80, accuracy = 100, type = "FLYING", priority = 0, effect = "HIT" },
  [66] = { id = 66, name = "SUBMISSION", pp = 25, power = 80, accuracy = 80, type = "FIGHTING", priority = 0, effect = "RECOIL" },
  [67] = { id = 67, name = "LOW KICK", pp = 20, power = 1, accuracy = 100, type = "FIGHTING", priority = 0, effect = "LOW_KICK" },
  [68] = { id = 68, name = "COUNTER", pp = 20, power = 1, accuracy = 100, type = "FIGHTING", priority = -5, effect = "COUNTER" },
  [69] = { id = 69, name = "SEISMIC TOSS", pp = 20, power = 1, accuracy = 100, type = "FIGHTING", priority = 0, effect = "LEVEL_DAMAGE" },
  [70] = { id = 70, name = "STRENGTH", pp = 15, power = 80, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIT" },
  [71] = { id = 71, name = "ABSORB", pp = 20, power = 20, accuracy = 100, type = "GRASS", priority = 0, effect = "ABSORB" },
  [72] = { id = 72, name = "MEGA DRAIN", pp = 10, power = 40, accuracy = 100, type = "GRASS", priority = 0, effect = "ABSORB" },
  [73] = { id = 73, name = "LEECH SEED", pp = 10, power = 0, accuracy = 90, type = "GRASS", priority = 0, effect = "LEECH_SEED" },
  [74] = { id = 74, name = "GROWTH", pp = 40, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SPECIAL_ATTACK_UP" },
  [75] = { id = 75, name = "RAZOR LEAF", pp = 25, power = 55, accuracy = 95, type = "GRASS", priority = 0, effect = "HIGH_CRITICAL" },
  [76] = { id = 76, name = "SOLARBEAM", pp = 10, power = 120, accuracy = 100, type = "GRASS", priority = 0, effect = "SOLAR_BEAM" },
  [77] = { id = 77, name = "POISONPOWDER", pp = 35, power = 0, accuracy = 75, type = "POISON", priority = 0, effect = "POISON" },
  [78] = { id = 78, name = "STUN SPORE", pp = 30, power = 0, accuracy = 75, type = "GRASS", priority = 0, effect = "PARALYZE" },
  [79] = { id = 79, name = "SLEEP POWDER", pp = 15, power = 0, accuracy = 75, type = "GRASS", priority = 0, effect = "SLEEP" },
  [80] = { id = 80, name = "PETAL DANCE", pp = 20, power = 70, accuracy = 100, type = "GRASS", priority = 0, effect = "RAMPAGE" },
  [81] = { id = 81, name = "STRING SHOT", pp = 40, power = 0, accuracy = 95, type = "BUG", priority = 0, effect = "SPEED_DOWN" },
  [82] = { id = 82, name = "DRAGON RAGE", pp = 10, power = 1, accuracy = 100, type = "DRAGON", priority = 0, effect = "DRAGON_RAGE" },
  [83] = { id = 83, name = "FIRE SPIN", pp = 15, power = 15, accuracy = 70, type = "FIRE", priority = 0, effect = "TRAP" },
  [84] = { id = 84, name = "THUNDERSHOCK", pp = 30, power = 40, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "PARALYZE_HIT" },
  [85] = { id = 85, name = "THUNDERBOLT", pp = 15, power = 95, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "PARALYZE_HIT" },
  [86] = { id = 86, name = "THUNDER WAVE", pp = 20, power = 0, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "PARALYZE" },
  [87] = { id = 87, name = "THUNDER", pp = 10, power = 120, accuracy = 70, type = "ELECTRIC", priority = 0, effect = "THUNDER" },
  [88] = { id = 88, name = "ROCK THROW", pp = 15, power = 50, accuracy = 90, type = "ROCK", priority = 0, effect = "HIT" },
  [89] = { id = 89, name = "EARTHQUAKE", pp = 10, power = 100, accuracy = 100, type = "GROUND", priority = 0, effect = "EARTHQUAKE" },
  [90] = { id = 90, name = "FISSURE", pp = 5, power = 1, accuracy = 30, type = "GROUND", priority = 0, effect = "OHKO" },
  [91] = { id = 91, name = "DIG", pp = 10, power = 60, accuracy = 100, type = "GROUND", priority = 0, effect = "SEMI_INVULNERABLE" },
  [92] = { id = 92, name = "TOXIC", pp = 10, power = 0, accuracy = 85, type = "POISON", priority = 0, effect = "TOXIC" },
  [93] = { id = 93, name = "CONFUSION", pp = 25, power = 50, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "CONFUSE_HIT" },
  [94] = { id = 94, name = "PSYCHIC", pp = 10, power = 90, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "SPECIAL_DEFENSE_DOWN_HIT" },
  [95] = { id = 95, name = "HYPNOSIS", pp = 20, power = 0, accuracy = 60, type = "PSYCHIC", priority = 0, effect = "SLEEP" },
  [96] = { id = 96, name = "MEDITATE", pp = 40, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "ATTACK_UP" },
  [97] = { id = 97, name = "AGILITY", pp = 30, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "SPEED_UP_2" },
  [98] = { id = 98, name = "QUICK ATTACK", pp = 30, power = 40, accuracy = 100, type = "NORMAL", priority = 1, effect = "QUICK_ATTACK" },
  [99] = { id = 99, name = "RAGE", pp = 20, power = 20, accuracy = 100, type = "NORMAL", priority = 0, effect = "RAGE" },
  [100] = { id = 100, name = "TELEPORT", pp = 20, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "TELEPORT" },
  [101] = { id = 101, name = "NIGHT SHADE", pp = 15, power = 1, accuracy = 100, type = "GHOST", priority = 0, effect = "LEVEL_DAMAGE" },
  [102] = { id = 102, name = "MIMIC", pp = 10, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "MIMIC" },
  [103] = { id = 103, name = "SCREECH", pp = 40, power = 0, accuracy = 85, type = "NORMAL", priority = 0, effect = "DEFENSE_DOWN_2" },
  [104] = { id = 104, name = "DOUBLE TEAM", pp = 15, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "EVASION_UP" },
  [105] = { id = 105, name = "RECOVER", pp = 20, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "RESTORE_HP" },
  [106] = { id = 106, name = "HARDEN", pp = 30, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "DEFENSE_UP" },
  [107] = { id = 107, name = "MINIMIZE", pp = 20, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "MINIMIZE" },
  [108] = { id = 108, name = "SMOKESCREEN", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "ACCURACY_DOWN" },
  [109] = { id = 109, name = "CONFUSE RAY", pp = 10, power = 0, accuracy = 100, type = "GHOST", priority = 0, effect = "CONFUSE" },
  [110] = { id = 110, name = "WITHDRAW", pp = 40, power = 0, accuracy = 0, type = "WATER", priority = 0, effect = "DEFENSE_UP" },
  [111] = { id = 111, name = "DEFENSE CURL", pp = 40, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "DEFENSE_CURL" },
  [112] = { id = 112, name = "BARRIER", pp = 30, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "DEFENSE_UP_2" },
  [113] = { id = 113, name = "LIGHT SCREEN", pp = 30, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "LIGHT_SCREEN" },
  [114] = { id = 114, name = "HAZE", pp = 30, power = 0, accuracy = 0, type = "ICE", priority = 0, effect = "HAZE" },
  [115] = { id = 115, name = "REFLECT", pp = 20, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "REFLECT" },
  [116] = { id = 116, name = "FOCUS ENERGY", pp = 30, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "FOCUS_ENERGY" },
  [117] = { id = 117, name = "BIDE", pp = 10, power = 1, accuracy = 100, type = "NORMAL", priority = 0, effect = "BIDE" },
  [118] = { id = 118, name = "METRONOME", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "METRONOME" },
  [119] = { id = 119, name = "MIRROR MOVE", pp = 20, power = 0, accuracy = 0, type = "FLYING", priority = 0, effect = "MIRROR_MOVE" },
  [120] = { id = 120, name = "SELFDESTRUCT", pp = 5, power = 200, accuracy = 100, type = "NORMAL", priority = 0, effect = "EXPLOSION" },
  [121] = { id = 121, name = "EGG BOMB", pp = 10, power = 100, accuracy = 75, type = "NORMAL", priority = 0, effect = "HIT" },
  [122] = { id = 122, name = "LICK", pp = 30, power = 20, accuracy = 100, type = "GHOST", priority = 0, effect = "PARALYZE_HIT" },
  [123] = { id = 123, name = "SMOG", pp = 20, power = 20, accuracy = 70, type = "POISON", priority = 0, effect = "POISON_HIT" },
  [124] = { id = 124, name = "SLUDGE", pp = 20, power = 65, accuracy = 100, type = "POISON", priority = 0, effect = "POISON_HIT" },
  [125] = { id = 125, name = "BONE CLUB", pp = 20, power = 65, accuracy = 85, type = "GROUND", priority = 0, effect = "FLINCH_HIT" },
  [126] = { id = 126, name = "FIRE BLAST", pp = 5, power = 120, accuracy = 85, type = "FIRE", priority = 0, effect = "BURN_HIT" },
  [127] = { id = 127, name = "WATERFALL", pp = 15, power = 80, accuracy = 100, type = "WATER", priority = 0, effect = "HIT" },
  [128] = { id = 128, name = "CLAMP", pp = 10, power = 35, accuracy = 75, type = "WATER", priority = 0, effect = "TRAP" },
  [129] = { id = 129, name = "SWIFT", pp = 20, power = 60, accuracy = 0, type = "NORMAL", priority = 0, effect = "ALWAYS_HIT" },
  [130] = { id = 130, name = "SKULL BASH", pp = 15, power = 100, accuracy = 100, type = "NORMAL", priority = 0, effect = "SKULL_BASH" },
  [131] = { id = 131, name = "SPIKE CANNON", pp = 15, power = 20, accuracy = 100, type = "NORMAL", priority = 0, effect = "MULTI_HIT" },
  [132] = { id = 132, name = "CONSTRICT", pp = 35, power = 10, accuracy = 100, type = "NORMAL", priority = 0, effect = "SPEED_DOWN_HIT" },
  [133] = { id = 133, name = "AMNESIA", pp = 20, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "SPECIAL_DEFENSE_UP_2" },
  [134] = { id = 134, name = "KINESIS", pp = 15, power = 0, accuracy = 80, type = "PSYCHIC", priority = 0, effect = "ACCURACY_DOWN" },
  [135] = { id = 135, name = "SOFTBOILED", pp = 10, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "SOFTBOILED" },
  [136] = { id = 136, name = "HI JUMP KICK", pp = 20, power = 85, accuracy = 90, type = "FIGHTING", priority = 0, effect = "RECOIL_IF_MISS" },
  [137] = { id = 137, name = "GLARE", pp = 30, power = 0, accuracy = 75, type = "NORMAL", priority = 0, effect = "PARALYZE" },
  [138] = { id = 138, name = "DREAM EATER", pp = 15, power = 100, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "DREAM_EATER" },
  [139] = { id = 139, name = "POISON GAS", pp = 40, power = 0, accuracy = 55, type = "POISON", priority = 0, effect = "POISON" },
  [140] = { id = 140, name = "BARRAGE", pp = 20, power = 15, accuracy = 85, type = "NORMAL", priority = 0, effect = "MULTI_HIT" },
  [141] = { id = 141, name = "LEECH LIFE", pp = 15, power = 20, accuracy = 100, type = "BUG", priority = 0, effect = "ABSORB" },
  [142] = { id = 142, name = "LOVELY KISS", pp = 10, power = 0, accuracy = 75, type = "NORMAL", priority = 0, effect = "SLEEP" },
  [143] = { id = 143, name = "SKY ATTACK", pp = 5, power = 140, accuracy = 90, type = "FLYING", priority = 0, effect = "SKY_ATTACK" },
  [144] = { id = 144, name = "TRANSFORM", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "TRANSFORM" },
  [145] = { id = 145, name = "BUBBLE", pp = 30, power = 20, accuracy = 100, type = "WATER", priority = 0, effect = "SPEED_DOWN_HIT" },
  [146] = { id = 146, name = "DIZZY PUNCH", pp = 10, power = 70, accuracy = 100, type = "NORMAL", priority = 0, effect = "CONFUSE_HIT" },
  [147] = { id = 147, name = "SPORE", pp = 15, power = 0, accuracy = 100, type = "GRASS", priority = 0, effect = "SLEEP" },
  [148] = { id = 148, name = "FLASH", pp = 20, power = 0, accuracy = 70, type = "NORMAL", priority = 0, effect = "ACCURACY_DOWN" },
  [149] = { id = 149, name = "PSYWAVE", pp = 15, power = 1, accuracy = 80, type = "PSYCHIC", priority = 0, effect = "PSYWAVE" },
  [150] = { id = 150, name = "SPLASH", pp = 40, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SPLASH" },
  [151] = { id = 151, name = "ACID ARMOR", pp = 40, power = 0, accuracy = 0, type = "POISON", priority = 0, effect = "DEFENSE_UP_2" },
  [152] = { id = 152, name = "CRABHAMMER", pp = 10, power = 90, accuracy = 85, type = "WATER", priority = 0, effect = "HIGH_CRITICAL" },
  [153] = { id = 153, name = "EXPLOSION", pp = 5, power = 250, accuracy = 100, type = "NORMAL", priority = 0, effect = "EXPLOSION" },
  [154] = { id = 154, name = "FURY SWIPES", pp = 15, power = 18, accuracy = 80, type = "NORMAL", priority = 0, effect = "MULTI_HIT" },
  [155] = { id = 155, name = "BONEMERANG", pp = 10, power = 50, accuracy = 90, type = "GROUND", priority = 0, effect = "DOUBLE_HIT" },
  [156] = { id = 156, name = "REST", pp = 10, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "REST" },
  [157] = { id = 157, name = "ROCK SLIDE", pp = 10, power = 75, accuracy = 90, type = "ROCK", priority = 0, effect = "FLINCH_HIT" },
  [158] = { id = 158, name = "HYPER FANG", pp = 15, power = 80, accuracy = 90, type = "NORMAL", priority = 0, effect = "FLINCH_HIT" },
  [159] = { id = 159, name = "SHARPEN", pp = 30, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "ATTACK_UP" },
  [160] = { id = 160, name = "CONVERSION", pp = 30, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "CONVERSION" },
  [161] = { id = 161, name = "TRI ATTACK", pp = 10, power = 80, accuracy = 100, type = "NORMAL", priority = 0, effect = "TRI_ATTACK" },
  [162] = { id = 162, name = "SUPER FANG", pp = 10, power = 1, accuracy = 90, type = "NORMAL", priority = 0, effect = "SUPER_FANG" },
  [163] = { id = 163, name = "SLASH", pp = 20, power = 70, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIGH_CRITICAL" },
  [164] = { id = 164, name = "SUBSTITUTE", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SUBSTITUTE" },
  [165] = { id = 165, name = "STRUGGLE", pp = 1, power = 50, accuracy = 100, type = "NORMAL", priority = 0, effect = "RECOIL" },
  [166] = { id = 166, name = "SKETCH", pp = 1, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SKETCH" },
  [167] = { id = 167, name = "TRIPLE KICK", pp = 10, power = 10, accuracy = 90, type = "FIGHTING", priority = 0, effect = "TRIPLE_KICK" },
  [168] = { id = 168, name = "THIEF", pp = 10, power = 40, accuracy = 100, type = "DARK", priority = 0, effect = "THIEF" },
  [169] = { id = 169, name = "SPIDER WEB", pp = 10, power = 0, accuracy = 100, type = "BUG", priority = 0, effect = "MEAN_LOOK" },
  [170] = { id = 170, name = "MIND READER", pp = 5, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "LOCK_ON" },
  [171] = { id = 171, name = "NIGHTMARE", pp = 15, power = 0, accuracy = 100, type = "GHOST", priority = 0, effect = "NIGHTMARE" },
  [172] = { id = 172, name = "FLAME WHEEL", pp = 25, power = 60, accuracy = 100, type = "FIRE", priority = 0, effect = "THAW_HIT" },
  [173] = { id = 173, name = "SNORE", pp = 15, power = 40, accuracy = 100, type = "NORMAL", priority = 0, effect = "SNORE" },
  [174] = { id = 174, name = "CURSE", pp = 10, power = 0, accuracy = 0, type = "MYSTERY", priority = 0, effect = "CURSE" },
  [175] = { id = 175, name = "FLAIL", pp = 15, power = 1, accuracy = 100, type = "NORMAL", priority = 0, effect = "FLAIL" },
  [176] = { id = 176, name = "CONVERSION 2", pp = 30, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "CONVERSION_2" },
  [177] = { id = 177, name = "AEROBLAST", pp = 5, power = 100, accuracy = 95, type = "FLYING", priority = 0, effect = "HIGH_CRITICAL" },
  [178] = { id = 178, name = "COTTON SPORE", pp = 40, power = 0, accuracy = 85, type = "GRASS", priority = 0, effect = "SPEED_DOWN_2" },
  [179] = { id = 179, name = "REVERSAL", pp = 15, power = 1, accuracy = 100, type = "FIGHTING", priority = 0, effect = "FLAIL" },
  [180] = { id = 180, name = "SPITE", pp = 10, power = 0, accuracy = 100, type = "GHOST", priority = 0, effect = "SPITE" },
  [181] = { id = 181, name = "POWDER SNOW", pp = 25, power = 40, accuracy = 100, type = "ICE", priority = 0, effect = "FREEZE_HIT" },
  [182] = { id = 182, name = "PROTECT", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 3, effect = "PROTECT" },
  [183] = { id = 183, name = "MACH PUNCH", pp = 30, power = 40, accuracy = 100, type = "FIGHTING", priority = 1, effect = "QUICK_ATTACK" },
  [184] = { id = 184, name = "SCARY FACE", pp = 10, power = 0, accuracy = 90, type = "NORMAL", priority = 0, effect = "SPEED_DOWN_2" },
  [185] = { id = 185, name = "FAINT ATTACK", pp = 20, power = 60, accuracy = 0, type = "DARK", priority = 0, effect = "ALWAYS_HIT" },
  [186] = { id = 186, name = "SWEET KISS", pp = 10, power = 0, accuracy = 75, type = "NORMAL", priority = 0, effect = "CONFUSE" },
  [187] = { id = 187, name = "BELLY DRUM", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "BELLY_DRUM" },
  [188] = { id = 188, name = "SLUDGE BOMB", pp = 10, power = 90, accuracy = 100, type = "POISON", priority = 0, effect = "POISON_HIT" },
  [189] = { id = 189, name = "MUD-SLAP", pp = 10, power = 20, accuracy = 100, type = "GROUND", priority = 0, effect = "ACCURACY_DOWN_HIT" },
  [190] = { id = 190, name = "OCTAZOOKA", pp = 10, power = 65, accuracy = 85, type = "WATER", priority = 0, effect = "ACCURACY_DOWN_HIT" },
  [191] = { id = 191, name = "SPIKES", pp = 20, power = 0, accuracy = 0, type = "GROUND", priority = 0, effect = "SPIKES" },
  [192] = { id = 192, name = "ZAP CANNON", pp = 5, power = 100, accuracy = 50, type = "ELECTRIC", priority = 0, effect = "PARALYZE_HIT" },
  [193] = { id = 193, name = "FORESIGHT", pp = 40, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "FORESIGHT" },
  [194] = { id = 194, name = "DESTINY BOND", pp = 5, power = 0, accuracy = 0, type = "GHOST", priority = 0, effect = "DESTINY_BOND" },
  [195] = { id = 195, name = "PERISH SONG", pp = 5, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "PERISH_SONG" },
  [196] = { id = 196, name = "ICY WIND", pp = 15, power = 55, accuracy = 95, type = "ICE", priority = 0, effect = "SPEED_DOWN_HIT" },
  [197] = { id = 197, name = "DETECT", pp = 5, power = 0, accuracy = 0, type = "FIGHTING", priority = 3, effect = "PROTECT" },
  [198] = { id = 198, name = "BONE RUSH", pp = 10, power = 25, accuracy = 80, type = "GROUND", priority = 0, effect = "MULTI_HIT" },
  [199] = { id = 199, name = "LOCK-ON", pp = 5, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "LOCK_ON" },
  [200] = { id = 200, name = "OUTRAGE", pp = 15, power = 90, accuracy = 100, type = "DRAGON", priority = 0, effect = "RAMPAGE" },
  [201] = { id = 201, name = "SANDSTORM", pp = 10, power = 0, accuracy = 0, type = "ROCK", priority = 0, effect = "SANDSTORM" },
  [202] = { id = 202, name = "GIGA DRAIN", pp = 5, power = 60, accuracy = 100, type = "GRASS", priority = 0, effect = "ABSORB" },
  [203] = { id = 203, name = "ENDURE", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 3, effect = "ENDURE" },
  [204] = { id = 204, name = "CHARM", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "ATTACK_DOWN_2" },
  [205] = { id = 205, name = "ROLLOUT", pp = 20, power = 30, accuracy = 90, type = "ROCK", priority = 0, effect = "ROLLOUT" },
  [206] = { id = 206, name = "FALSE SWIPE", pp = 40, power = 40, accuracy = 100, type = "NORMAL", priority = 0, effect = "FALSE_SWIPE" },
  [207] = { id = 207, name = "SWAGGER", pp = 15, power = 0, accuracy = 90, type = "NORMAL", priority = 0, effect = "SWAGGER" },
  [208] = { id = 208, name = "MILK DRINK", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SOFTBOILED" },
  [209] = { id = 209, name = "SPARK", pp = 20, power = 65, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "PARALYZE_HIT" },
  [210] = { id = 210, name = "FURY CUTTER", pp = 20, power = 10, accuracy = 95, type = "BUG", priority = 0, effect = "FURY_CUTTER" },
  [211] = { id = 211, name = "STEEL WING", pp = 25, power = 70, accuracy = 90, type = "STEEL", priority = 0, effect = "DEFENSE_UP_HIT" },
  [212] = { id = 212, name = "MEAN LOOK", pp = 5, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "MEAN_LOOK" },
  [213] = { id = 213, name = "ATTRACT", pp = 15, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "ATTRACT" },
  [214] = { id = 214, name = "SLEEP TALK", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SLEEP_TALK" },
  [215] = { id = 215, name = "HEAL BELL", pp = 5, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "HEAL_BELL" },
  [216] = { id = 216, name = "RETURN", pp = 20, power = 1, accuracy = 100, type = "NORMAL", priority = 0, effect = "RETURN" },
  [217] = { id = 217, name = "PRESENT", pp = 15, power = 1, accuracy = 90, type = "NORMAL", priority = 0, effect = "PRESENT" },
  [218] = { id = 218, name = "FRUSTRATION", pp = 20, power = 1, accuracy = 100, type = "NORMAL", priority = 0, effect = "FRUSTRATION" },
  [219] = { id = 219, name = "SAFEGUARD", pp = 25, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SAFEGUARD" },
  [220] = { id = 220, name = "PAIN SPLIT", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "PAIN_SPLIT" },
  [221] = { id = 221, name = "SACRED FIRE", pp = 5, power = 100, accuracy = 95, type = "FIRE", priority = 0, effect = "THAW_HIT" },
  [222] = { id = 222, name = "MAGNITUDE", pp = 30, power = 1, accuracy = 100, type = "GROUND", priority = 0, effect = "MAGNITUDE" },
  [223] = { id = 223, name = "DYNAMICPUNCH", pp = 5, power = 100, accuracy = 50, type = "FIGHTING", priority = 0, effect = "CONFUSE_HIT" },
  [224] = { id = 224, name = "MEGAHORN", pp = 10, power = 120, accuracy = 85, type = "BUG", priority = 0, effect = "HIT" },
  [225] = { id = 225, name = "DRAGONBREATH", pp = 20, power = 60, accuracy = 100, type = "DRAGON", priority = 0, effect = "PARALYZE_HIT" },
  [226] = { id = 226, name = "BATON PASS", pp = 40, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "BATON_PASS" },
  [227] = { id = 227, name = "ENCORE", pp = 5, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "ENCORE" },
  [228] = { id = 228, name = "PURSUIT", pp = 20, power = 40, accuracy = 100, type = "DARK", priority = 0, effect = "PURSUIT" },
  [229] = { id = 229, name = "RAPID SPIN", pp = 40, power = 20, accuracy = 100, type = "NORMAL", priority = 0, effect = "RAPID_SPIN" },
  [230] = { id = 230, name = "SWEET SCENT", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "EVASION_DOWN" },
  [231] = { id = 231, name = "IRON TAIL", pp = 15, power = 100, accuracy = 75, type = "STEEL", priority = 0, effect = "DEFENSE_DOWN_HIT" },
  [232] = { id = 232, name = "METAL CLAW", pp = 35, power = 50, accuracy = 95, type = "STEEL", priority = 0, effect = "ATTACK_UP_HIT" },
  [233] = { id = 233, name = "VITAL THROW", pp = 10, power = 70, accuracy = 100, type = "FIGHTING", priority = -1, effect = "VITAL_THROW" },
  [234] = { id = 234, name = "MORNING SUN", pp = 5, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "MORNING_SUN" },
  [235] = { id = 235, name = "SYNTHESIS", pp = 5, power = 0, accuracy = 0, type = "GRASS", priority = 0, effect = "SYNTHESIS" },
  [236] = { id = 236, name = "MOONLIGHT", pp = 5, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "MOONLIGHT" },
  [237] = { id = 237, name = "HIDDEN POWER", pp = 15, power = 1, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIDDEN_POWER" },
  [238] = { id = 238, name = "CROSS CHOP", pp = 5, power = 100, accuracy = 80, type = "FIGHTING", priority = 0, effect = "HIGH_CRITICAL" },
  [239] = { id = 239, name = "TWISTER", pp = 20, power = 40, accuracy = 100, type = "DRAGON", priority = 0, effect = "TWISTER" },
  [240] = { id = 240, name = "RAIN DANCE", pp = 5, power = 0, accuracy = 0, type = "WATER", priority = 0, effect = "RAIN_DANCE" },
  [241] = { id = 241, name = "SUNNY DAY", pp = 5, power = 0, accuracy = 0, type = "FIRE", priority = 0, effect = "SUNNY_DAY" },
  [242] = { id = 242, name = "CRUNCH", pp = 15, power = 80, accuracy = 100, type = "DARK", priority = 0, effect = "SPECIAL_DEFENSE_DOWN_HIT" },
  [243] = { id = 243, name = "MIRROR COAT", pp = 20, power = 1, accuracy = 100, type = "PSYCHIC", priority = -5, effect = "MIRROR_COAT" },
  [244] = { id = 244, name = "PSYCH UP", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "PSYCH_UP" },
  [245] = { id = 245, name = "EXTREMESPEED", pp = 5, power = 80, accuracy = 100, type = "NORMAL", priority = 1, effect = "QUICK_ATTACK" },
  [246] = { id = 246, name = "ANCIENTPOWER", pp = 5, power = 60, accuracy = 100, type = "ROCK", priority = 0, effect = "ALL_STATS_UP_HIT" },
  [247] = { id = 247, name = "SHADOW BALL", pp = 15, power = 80, accuracy = 100, type = "GHOST", priority = 0, effect = "SPECIAL_DEFENSE_DOWN_HIT" },
  [248] = { id = 248, name = "FUTURE SIGHT", pp = 15, power = 80, accuracy = 90, type = "PSYCHIC", priority = 0, effect = "FUTURE_SIGHT" },
  [249] = { id = 249, name = "ROCK SMASH", pp = 15, power = 20, accuracy = 100, type = "FIGHTING", priority = 0, effect = "DEFENSE_DOWN_HIT" },
  [250] = { id = 250, name = "WHIRLPOOL", pp = 15, power = 15, accuracy = 70, type = "WATER", priority = 0, effect = "TRAP" },
  [251] = { id = 251, name = "BEAT UP", pp = 10, power = 10, accuracy = 100, type = "DARK", priority = 0, effect = "BEAT_UP" },
  [252] = { id = 252, name = "FAKE OUT", pp = 10, power = 40, accuracy = 100, type = "NORMAL", priority = 1, effect = "FAKE_OUT" },
  [253] = { id = 253, name = "UPROAR", pp = 10, power = 50, accuracy = 100, type = "NORMAL", priority = 0, effect = "UPROAR" },
  [254] = { id = 254, name = "STOCKPILE", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "STOCKPILE" },
  [255] = { id = 255, name = "SPIT UP", pp = 10, power = 100, accuracy = 100, type = "NORMAL", priority = 0, effect = "SPIT_UP" },
  [256] = { id = 256, name = "SWALLOW", pp = 10, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "SWALLOW" },
  [257] = { id = 257, name = "HEAT WAVE", pp = 10, power = 100, accuracy = 90, type = "FIRE", priority = 0, effect = "BURN_HIT" },
  [258] = { id = 258, name = "HAIL", pp = 10, power = 0, accuracy = 0, type = "ICE", priority = 0, effect = "HAIL" },
  [259] = { id = 259, name = "TORMENT", pp = 15, power = 0, accuracy = 100, type = "DARK", priority = 0, effect = "TORMENT" },
  [260] = { id = 260, name = "FLATTER", pp = 15, power = 0, accuracy = 100, type = "DARK", priority = 0, effect = "FLATTER" },
  [261] = { id = 261, name = "WILL-O-WISP", pp = 15, power = 0, accuracy = 75, type = "FIRE", priority = 0, effect = "WILL_O_WISP" },
  [262] = { id = 262, name = "MEMENTO", pp = 10, power = 0, accuracy = 100, type = "DARK", priority = 0, effect = "MEMENTO" },
  [263] = { id = 263, name = "FACADE", pp = 20, power = 70, accuracy = 100, type = "NORMAL", priority = 0, effect = "FACADE" },
  [264] = { id = 264, name = "FOCUS PUNCH", pp = 20, power = 150, accuracy = 100, type = "FIGHTING", priority = -3, effect = "FOCUS_PUNCH" },
  [265] = { id = 265, name = "SMELLINGSALT", pp = 10, power = 60, accuracy = 100, type = "NORMAL", priority = 0, effect = "SMELLINGSALT" },
  [266] = { id = 266, name = "FOLLOW ME", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 3, effect = "FOLLOW_ME" },
  [267] = { id = 267, name = "NATURE POWER", pp = 20, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "NATURE_POWER" },
  [268] = { id = 268, name = "CHARGE", pp = 20, power = 0, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "CHARGE" },
  [269] = { id = 269, name = "TAUNT", pp = 20, power = 0, accuracy = 100, type = "DARK", priority = 0, effect = "TAUNT" },
  [270] = { id = 270, name = "HELPING HAND", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 5, effect = "HELPING_HAND" },
  [271] = { id = 271, name = "TRICK", pp = 10, power = 0, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "TRICK" },
  [272] = { id = 272, name = "ROLE PLAY", pp = 10, power = 0, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "ROLE_PLAY" },
  [273] = { id = 273, name = "WISH", pp = 10, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "WISH" },
  [274] = { id = 274, name = "ASSIST", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "ASSIST" },
  [275] = { id = 275, name = "INGRAIN", pp = 20, power = 0, accuracy = 100, type = "GRASS", priority = 0, effect = "INGRAIN" },
  [276] = { id = 276, name = "SUPERPOWER", pp = 5, power = 120, accuracy = 100, type = "FIGHTING", priority = 0, effect = "SUPERPOWER" },
  [277] = { id = 277, name = "MAGIC COAT", pp = 15, power = 0, accuracy = 100, type = "PSYCHIC", priority = 4, effect = "MAGIC_COAT" },
  [278] = { id = 278, name = "RECYCLE", pp = 10, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "RECYCLE" },
  [279] = { id = 279, name = "REVENGE", pp = 10, power = 60, accuracy = 100, type = "FIGHTING", priority = -4, effect = "REVENGE" },
  [280] = { id = 280, name = "BRICK BREAK", pp = 15, power = 75, accuracy = 100, type = "FIGHTING", priority = 0, effect = "BRICK_BREAK" },
  [281] = { id = 281, name = "YAWN", pp = 10, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "YAWN" },
  [282] = { id = 282, name = "KNOCK OFF", pp = 20, power = 20, accuracy = 100, type = "DARK", priority = 0, effect = "KNOCK_OFF" },
  [283] = { id = 283, name = "ENDEAVOR", pp = 5, power = 1, accuracy = 100, type = "NORMAL", priority = 0, effect = "ENDEAVOR" },
  [284] = { id = 284, name = "ERUPTION", pp = 5, power = 150, accuracy = 100, type = "FIRE", priority = 0, effect = "ERUPTION" },
  [285] = { id = 285, name = "SKILL SWAP", pp = 10, power = 0, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "SKILL_SWAP" },
  [286] = { id = 286, name = "IMPRISON", pp = 10, power = 0, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "IMPRISON" },
  [287] = { id = 287, name = "REFRESH", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "REFRESH" },
  [288] = { id = 288, name = "GRUDGE", pp = 5, power = 0, accuracy = 100, type = "GHOST", priority = 0, effect = "GRUDGE" },
  [289] = { id = 289, name = "SNATCH", pp = 10, power = 0, accuracy = 100, type = "DARK", priority = 4, effect = "SNATCH" },
  [290] = { id = 290, name = "SECRET POWER", pp = 20, power = 70, accuracy = 100, type = "NORMAL", priority = 0, effect = "SECRET_POWER" },
  [291] = { id = 291, name = "DIVE", pp = 10, power = 60, accuracy = 100, type = "WATER", priority = 0, effect = "SEMI_INVULNERABLE" },
  [292] = { id = 292, name = "ARM THRUST", pp = 20, power = 15, accuracy = 100, type = "FIGHTING", priority = 0, effect = "MULTI_HIT" },
  [293] = { id = 293, name = "CAMOUFLAGE", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "CAMOUFLAGE" },
  [294] = { id = 294, name = "TAIL GLOW", pp = 20, power = 0, accuracy = 100, type = "BUG", priority = 0, effect = "SPECIAL_ATTACK_UP_2" },
  [295] = { id = 295, name = "LUSTER PURGE", pp = 5, power = 70, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "SPECIAL_DEFENSE_DOWN_HIT" },
  [296] = { id = 296, name = "MIST BALL", pp = 5, power = 70, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "SPECIAL_ATTACK_DOWN_HIT" },
  [297] = { id = 297, name = "FEATHERDANCE", pp = 15, power = 0, accuracy = 100, type = "FLYING", priority = 0, effect = "ATTACK_DOWN_2" },
  [298] = { id = 298, name = "TEETER DANCE", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "TEETER_DANCE" },
  [299] = { id = 299, name = "BLAZE KICK", pp = 10, power = 85, accuracy = 90, type = "FIRE", priority = 0, effect = "BLAZE_KICK" },
  [300] = { id = 300, name = "MUD SPORT", pp = 15, power = 0, accuracy = 100, type = "GROUND", priority = 0, effect = "MUD_SPORT" },
  [301] = { id = 301, name = "ICE BALL", pp = 20, power = 30, accuracy = 90, type = "ICE", priority = 0, effect = "ROLLOUT" },
  [302] = { id = 302, name = "NEEDLE ARM", pp = 15, power = 60, accuracy = 100, type = "GRASS", priority = 0, effect = "FLINCH_MINIMIZE_HIT" },
  [303] = { id = 303, name = "SLACK OFF", pp = 10, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "RESTORE_HP" },
  [304] = { id = 304, name = "HYPER VOICE", pp = 10, power = 90, accuracy = 100, type = "NORMAL", priority = 0, effect = "HIT" },
  [305] = { id = 305, name = "POISON FANG", pp = 15, power = 50, accuracy = 100, type = "POISON", priority = 0, effect = "POISON_FANG" },
  [306] = { id = 306, name = "CRUSH CLAW", pp = 10, power = 75, accuracy = 95, type = "NORMAL", priority = 0, effect = "DEFENSE_DOWN_HIT" },
  [307] = { id = 307, name = "BLAST BURN", pp = 5, power = 150, accuracy = 90, type = "FIRE", priority = 0, effect = "RECHARGE" },
  [308] = { id = 308, name = "HYDRO CANNON", pp = 5, power = 150, accuracy = 90, type = "WATER", priority = 0, effect = "RECHARGE" },
  [309] = { id = 309, name = "METEOR MASH", pp = 10, power = 100, accuracy = 85, type = "STEEL", priority = 0, effect = "ATTACK_UP_HIT" },
  [310] = { id = 310, name = "ASTONISH", pp = 15, power = 30, accuracy = 100, type = "GHOST", priority = 0, effect = "FLINCH_MINIMIZE_HIT" },
  [311] = { id = 311, name = "WEATHER BALL", pp = 10, power = 50, accuracy = 100, type = "NORMAL", priority = 0, effect = "WEATHER_BALL" },
  [312] = { id = 312, name = "AROMATHERAPY", pp = 5, power = 0, accuracy = 0, type = "GRASS", priority = 0, effect = "HEAL_BELL" },
  [313] = { id = 313, name = "FAKE TEARS", pp = 20, power = 0, accuracy = 100, type = "DARK", priority = 0, effect = "SPECIAL_DEFENSE_DOWN_2" },
  [314] = { id = 314, name = "AIR CUTTER", pp = 25, power = 55, accuracy = 95, type = "FLYING", priority = 0, effect = "HIGH_CRITICAL" },
  [315] = { id = 315, name = "OVERHEAT", pp = 5, power = 140, accuracy = 90, type = "FIRE", priority = 0, effect = "OVERHEAT" },
  [316] = { id = 316, name = "ODOR SLEUTH", pp = 40, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "FORESIGHT" },
  [317] = { id = 317, name = "ROCK TOMB", pp = 10, power = 50, accuracy = 80, type = "ROCK", priority = 0, effect = "SPEED_DOWN_HIT" },
  [318] = { id = 318, name = "SILVER WIND", pp = 5, power = 60, accuracy = 100, type = "BUG", priority = 0, effect = "ALL_STATS_UP_HIT" },
  [319] = { id = 319, name = "METAL SOUND", pp = 40, power = 0, accuracy = 85, type = "STEEL", priority = 0, effect = "SPECIAL_DEFENSE_DOWN_2" },
  [320] = { id = 320, name = "GRASSWHISTLE", pp = 15, power = 0, accuracy = 55, type = "GRASS", priority = 0, effect = "SLEEP" },
  [321] = { id = 321, name = "TICKLE", pp = 20, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "TICKLE" },
  [322] = { id = 322, name = "COSMIC POWER", pp = 20, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "COSMIC_POWER" },
  [323] = { id = 323, name = "WATER SPOUT", pp = 5, power = 150, accuracy = 100, type = "WATER", priority = 0, effect = "ERUPTION" },
  [324] = { id = 324, name = "SIGNAL BEAM", pp = 15, power = 75, accuracy = 100, type = "BUG", priority = 0, effect = "CONFUSE_HIT" },
  [325] = { id = 325, name = "SHADOW PUNCH", pp = 20, power = 60, accuracy = 0, type = "GHOST", priority = 0, effect = "ALWAYS_HIT" },
  [326] = { id = 326, name = "EXTRASENSORY", pp = 30, power = 80, accuracy = 100, type = "PSYCHIC", priority = 0, effect = "FLINCH_MINIMIZE_HIT" },
  [327] = { id = 327, name = "SKY UPPERCUT", pp = 15, power = 85, accuracy = 90, type = "FIGHTING", priority = 0, effect = "SKY_UPPERCUT" },
  [328] = { id = 328, name = "SAND TOMB", pp = 15, power = 15, accuracy = 70, type = "GROUND", priority = 0, effect = "TRAP" },
  [329] = { id = 329, name = "SHEER COLD", pp = 5, power = 1, accuracy = 30, type = "ICE", priority = 0, effect = "OHKO" },
  [330] = { id = 330, name = "MUDDY WATER", pp = 10, power = 95, accuracy = 85, type = "WATER", priority = 0, effect = "ACCURACY_DOWN_HIT" },
  [331] = { id = 331, name = "BULLET SEED", pp = 30, power = 10, accuracy = 100, type = "GRASS", priority = 0, effect = "MULTI_HIT" },
  [332] = { id = 332, name = "AERIAL ACE", pp = 20, power = 60, accuracy = 0, type = "FLYING", priority = 0, effect = "ALWAYS_HIT" },
  [333] = { id = 333, name = "ICICLE SPEAR", pp = 30, power = 10, accuracy = 100, type = "ICE", priority = 0, effect = "MULTI_HIT" },
  [334] = { id = 334, name = "IRON DEFENSE", pp = 15, power = 0, accuracy = 0, type = "STEEL", priority = 0, effect = "DEFENSE_UP_2" },
  [335] = { id = 335, name = "BLOCK", pp = 5, power = 0, accuracy = 100, type = "NORMAL", priority = 0, effect = "MEAN_LOOK" },
  [336] = { id = 336, name = "HOWL", pp = 40, power = 0, accuracy = 0, type = "NORMAL", priority = 0, effect = "ATTACK_UP" },
  [337] = { id = 337, name = "DRAGON CLAW", pp = 15, power = 80, accuracy = 100, type = "DRAGON", priority = 0, effect = "HIT" },
  [338] = { id = 338, name = "FRENZY PLANT", pp = 5, power = 150, accuracy = 90, type = "GRASS", priority = 0, effect = "RECHARGE" },
  [339] = { id = 339, name = "BULK UP", pp = 20, power = 0, accuracy = 0, type = "FIGHTING", priority = 0, effect = "BULK_UP" },
  [340] = { id = 340, name = "BOUNCE", pp = 5, power = 85, accuracy = 85, type = "FLYING", priority = 0, effect = "SEMI_INVULNERABLE" },
  [341] = { id = 341, name = "MUD SHOT", pp = 15, power = 55, accuracy = 95, type = "GROUND", priority = 0, effect = "SPEED_DOWN_HIT" },
  [342] = { id = 342, name = "POISON TAIL", pp = 25, power = 50, accuracy = 100, type = "POISON", priority = 0, effect = "POISON_TAIL" },
  [343] = { id = 343, name = "COVET", pp = 40, power = 40, accuracy = 100, type = "NORMAL", priority = 0, effect = "THIEF" },
  [344] = { id = 344, name = "VOLT TACKLE", pp = 15, power = 120, accuracy = 100, type = "ELECTRIC", priority = 0, effect = "DOUBLE_EDGE" },
  [345] = { id = 345, name = "MAGICAL LEAF", pp = 20, power = 60, accuracy = 0, type = "GRASS", priority = 0, effect = "ALWAYS_HIT" },
  [346] = { id = 346, name = "WATER SPORT", pp = 15, power = 0, accuracy = 100, type = "WATER", priority = 0, effect = "WATER_SPORT" },
  [347] = { id = 347, name = "CALM MIND", pp = 20, power = 0, accuracy = 0, type = "PSYCHIC", priority = 0, effect = "CALM_MIND" },
  [348] = { id = 348, name = "LEAF BLADE", pp = 15, power = 70, accuracy = 100, type = "GRASS", priority = 0, effect = "HIGH_CRITICAL" },
  [349] = { id = 349, name = "DRAGON DANCE", pp = 20, power = 0, accuracy = 0, type = "DRAGON", priority = 0, effect = "DRAGON_DANCE" },
  [350] = { id = 350, name = "ROCK BLAST", pp = 10, power = 25, accuracy = 80, type = "ROCK", priority = 0, effect = "MULTI_HIT" },
  [351] = { id = 351, name = "SHOCK WAVE", pp = 20, power = 60, accuracy = 0, type = "ELECTRIC", priority = 0, effect = "ALWAYS_HIT" },
  [352] = { id = 352, name = "WATER PULSE", pp = 20, power = 60, accuracy = 100, type = "WATER", priority = 0, effect = "CONFUSE_HIT" },
  [353] = { id = 353, name = "DOOM DESIRE", pp = 5, power = 120, accuracy = 85, type = "STEEL", priority = 0, effect = "FUTURE_SIGHT" },
  [354] = { id = 354, name = "PSYCHO BOOST", pp = 5, power = 140, accuracy = 90, type = "PSYCHIC", priority = 0, effect = "OVERHEAT" },
}

return BuiltinMoves
