-- pret pokefirered/include/constants/battle_move_effects.h (1:1 numeric ids).
-- ROM gBattleMoves[].effect is the dispatch key everywhere.

local EffectIds = {
  HIT = 0,
  SLEEP = 1,
  POISON_HIT = 2,
  ABSORB = 3,
  BURN_HIT = 4,
  FREEZE_HIT = 5,
  PARALYZE_HIT = 6,
  EXPLOSION = 7,
  DREAM_EATER = 8,
  MIRROR_MOVE = 9,
  ATTACK_UP = 10,
  DEFENSE_UP = 11,
  SPEED_UP = 12,
  SPECIAL_ATTACK_UP = 13,
  SPECIAL_DEFENSE_UP = 14,
  ACCURACY_UP = 15,
  EVASION_UP = 16,
  ALWAYS_HIT = 17,
  ATTACK_DOWN = 18,
  DEFENSE_DOWN = 19,
  SPEED_DOWN = 20,
  SPECIAL_ATTACK_DOWN = 21,
  SPECIAL_DEFENSE_DOWN = 22,
  ACCURACY_DOWN = 23,
  EVASION_DOWN = 24,
  HAZE = 25,
  BIDE = 26,
  RAMPAGE = 27,
  ROAR = 28,
  MULTI_HIT = 29,
  CONVERSION = 30,
  FLINCH_HIT = 31,
  RESTORE_HP = 32,
  TOXIC = 33,
  PAY_DAY = 34,
  LIGHT_SCREEN = 35,
  TRI_ATTACK = 36,
  REST = 37,
  OHKO = 38,
  RAZOR_WIND = 39,
  SUPER_FANG = 40,
  DRAGON_RAGE = 41,
  TRAP = 42,
  HIGH_CRITICAL = 43,
  DOUBLE_HIT = 44,
  RECOIL_IF_MISS = 45,
  MIST = 46,
  FOCUS_ENERGY = 47,
  RECOIL = 48,
  CONFUSE = 49,
  ATTACK_UP_2 = 50,
  DEFENSE_UP_2 = 51,
  SPEED_UP_2 = 52,
  SPECIAL_ATTACK_UP_2 = 53,
  SPECIAL_DEFENSE_UP_2 = 54,
  ACCURACY_UP_2 = 55,
  EVASION_UP_2 = 56,
  TRANSFORM = 57,
  ATTACK_DOWN_2 = 58,
  DEFENSE_DOWN_2 = 59,
  SPEED_DOWN_2 = 60,
  SPECIAL_ATTACK_DOWN_2 = 61,
  SPECIAL_DEFENSE_DOWN_2 = 62,
  ACCURACY_DOWN_2 = 63,
  EVASION_DOWN_2 = 64,
  REFLECT = 65,
  POISON = 66,
  PARALYZE = 67,
  ATTACK_DOWN_HIT = 68,
  DEFENSE_DOWN_HIT = 69,
  SPEED_DOWN_HIT = 70,
  SPECIAL_ATTACK_DOWN_HIT = 71,
  SPECIAL_DEFENSE_DOWN_HIT = 72,
  ACCURACY_DOWN_HIT = 73,
  EVASION_DOWN_HIT = 74,
  SKY_ATTACK = 75,
  CONFUSE_HIT = 76,
  TWINEEDLE = 77,
  VITAL_THROW = 78,
  SUBSTITUTE = 79,
  RECHARGE = 80,
  RAGE = 81,
  MIMIC = 82,
  METRONOME = 83,
  LEECH_SEED = 84,
  SPLASH = 85,
  DISABLE = 86,
  LEVEL_DAMAGE = 87,
  PSYWAVE = 88,
  COUNTER = 89,
  ENCORE = 90,
  PAIN_SPLIT = 91,
  SNORE = 92,
  CONVERSION_2 = 93,
  LOCK_ON = 94,
  SKETCH = 95,
  SLEEP_TALK = 97,
  DESTINY_BOND = 98,
  FLAIL = 99,
  SPITE = 100,
  FALSE_SWIPE = 101,
  HEAL_BELL = 102,
  QUICK_ATTACK = 103,
  TRIPLE_KICK = 104,
  THIEF = 105,
  MEAN_LOOK = 106,
  NIGHTMARE = 107,
  MINIMIZE = 108,
  CURSE = 109,
  PROTECT = 111,
  SPIKES = 112,
  FORESIGHT = 113,
  PERISH_SONG = 114,
  SANDSTORM = 115,
  ENDURE = 116,
  ROLLOUT = 117,
  SWAGGER = 118,
  FURY_CUTTER = 119,
  ATTRACT = 120,
  RETURN = 121,
  PRESENT = 122,
  FRUSTRATION = 123,
  SAFEGUARD = 124,
  THAW_HIT = 125,
  MAGNITUDE = 126,
  BATON_PASS = 127,
  PURSUIT = 128,
  RAPID_SPIN = 129,
  SONICBOOM = 130,
  MORNING_SUN = 132,
  SYNTHESIS = 133,
  MOONLIGHT = 134,
  HIDDEN_POWER = 135,
  RAIN_DANCE = 136,
  SUNNY_DAY = 137,
  DEFENSE_UP_HIT = 138,
  ATTACK_UP_HIT = 139,
  ALL_STATS_UP_HIT = 140,
  BELLY_DRUM = 142,
  PSYCH_UP = 143,
  MIRROR_COAT = 144,
  SKULL_BASH = 145,
  TWISTER = 146,
  EARTHQUAKE = 147,
  FUTURE_SIGHT = 148,
  GUST = 149,
  FLINCH_MINIMIZE_HIT = 150,
  SOLAR_BEAM = 151,
  THUNDER = 152,
  TELEPORT = 153,
  BEAT_UP = 154,
  SEMI_INVULNERABLE = 155,
  DEFENSE_CURL = 156,
  SOFTBOILED = 157,
  FAKE_OUT = 158,
  UPROAR = 159,
  STOCKPILE = 160,
  SPIT_UP = 161,
  SWALLOW = 162,
  HAIL = 164,
  TORMENT = 165,
  FLATTER = 166,
  WILL_O_WISP = 167,
  MEMENTO = 168,
  FACADE = 169,
  FOCUS_PUNCH = 170,
  SMELLINGSALT = 171,
  FOLLOW_ME = 172,
  NATURE_POWER = 173,
  CHARGE = 174,
  TAUNT = 175,
  HELPING_HAND = 176,
  TRICK = 177,
  ROLE_PLAY = 178,
  WISH = 179,
  ASSIST = 180,
  INGRAIN = 181,
  SUPERPOWER = 182,
  MAGIC_COAT = 183,
  RECYCLE = 184,
  REVENGE = 185,
  BRICK_BREAK = 186,
  YAWN = 187,
  KNOCK_OFF = 188,
  ENDEAVOR = 189,
  ERUPTION = 190,
  SKILL_SWAP = 191,
  IMPRISON = 192,
  REFRESH = 193,
  GRUDGE = 194,
  SNATCH = 195,
  LOW_KICK = 196,
  SECRET_POWER = 197,
  DOUBLE_EDGE = 198,
  TEETER_DANCE = 199,
  BLAZE_KICK = 200,
  MUD_SPORT = 201,
  POISON_FANG = 202,
  WEATHER_BALL = 203,
  OVERHEAT = 204,
  TICKLE = 205,
  COSMIC_POWER = 206,
  SKY_UPPERCUT = 207,
  BULK_UP = 208,
  POISON_TAIL = 209,
  WATER_SPORT = 210,
  CALM_MIND = 211,
  DRAGON_DANCE = 212,
  CAMOUFLAGE = 213,
}

-- Aliases used by older call sites.
EffectIds.RECOVER = EffectIds.RESTORE_HP
EffectIds.THRASH = EffectIds.RAMPAGE
EffectIds.RECOIL_25 = EffectIds.RECOIL
EffectIds.FLY = EffectIds.SEMI_INVULNERABLE

-- After-hit secondary effects keyed by ROM effect byte.
-- pokefirered/data/battle_scripts_1.s:321
EffectIds.SECONDARY = {
  [2] = { eff = "POISON" },
  [4] = { eff = "BURN" },
  [5] = { eff = "FREEZE" },
  [6] = { eff = "PARALYSIS" },
  [31] = { eff = "FLINCH" },
  [34] = { eff = "PAYDAY" },
  [36] = { eff = "TRI_ATTACK" },
  [42] = { eff = "WRAP" },
  [48] = { eff = "RECOIL_25", user = true, certain = true },
  [68] = { eff = "ATK_MINUS_1" },
  [69] = { eff = "DEF_MINUS_1" },
  [70] = { eff = "SPD_MINUS_1" },
  [71] = { eff = "SP_ATK_MINUS_1" },
  [72] = { eff = "SP_DEF_MINUS_1" },
  [73] = { eff = "ACC_MINUS_1" },
  [76] = { eff = "CONFUSION" },
  [77] = { eff = "POISON" },
  [80] = { eff = "RECHARGE", user = true, certain = true },
  [92] = { eff = "FLINCH" },
  [105] = { eff = "STEAL_ITEM" },
  [125] = { eff = "BURN" },
  [129] = { eff = "RAPIDSPIN", user = true, certain = true },
  [138] = { eff = "DEF_PLUS_1", user = true },
  [139] = { eff = "ATK_PLUS_1", user = true },
  [140] = { eff = "ALL_STATS_UP", user = true },
  [146] = { eff = "FLINCH" },
  [150] = { eff = "FLINCH" },
  [152] = { eff = "PARALYSIS" },
  [158] = { eff = "FLINCH", certain = true },
  [159] = { eff = "UPROAR", user = true },
  [171] = { eff = "REMOVE_PARALYSIS", certain = true },
  [182] = { eff = "ATK_DEF_DOWN", user = true, certain = true },
  [188] = { eff = "KNOCK_OFF" },
  [198] = { eff = "RECOIL_33", user = true, certain = true },
  [200] = { eff = "BURN" },
  [202] = { eff = "TOXIC" },
  [204] = { eff = "SP_ATK_TWO_DOWN", user = true, certain = true },
  [209] = { eff = "POISON" },
}
EffectIds.AFTER_HIT = EffectIds.SECONDARY

-- pokefirered/src/battle_script_commands.c:9226
EffectIds.SECRET_POWER_BY_TERRAIN = {
  [0] = "POISON", [1] = "SLEEP", [2] = "ACC_MINUS_1", [3] = "DEF_MINUS_1",
  [4] = "ATK_MINUS_1", [5] = "SPD_MINUS_1", [6] = "CONFUSION", [7] = "FLINCH",
}

-- Status/setup/weather/etc. → registry id. Key = ROM effect byte.
EffectIds.STATUS_SETUP = {
  [1] = "EXP_SLEEP_EFFECT",
  [10] = "EXP_STAT_FROM_EFFECT",
  [11] = "EXP_STAT_FROM_EFFECT",
  [13] = "EXP_STAT_FROM_EFFECT",
  [16] = "EXP_STAT_FROM_EFFECT",
  [18] = "EXP_STAT_FROM_EFFECT",
  [19] = "EXP_STAT_FROM_EFFECT",
  [20] = "EXP_STAT_FROM_EFFECT",
  [23] = "EXP_STAT_FROM_EFFECT",
  [24] = "EXP_STAT_FROM_EFFECT",
  [25] = "EXP_HAZE_EFFECT",
  [28] = "EXP_ROAR_EFFECT",
  [30] = "EXP_CONVERSION_EFFECT",
  [32] = "EXP_RECOVER_EFFECT",
  [33] = "EXP_TOXIC_EFFECT",
  [35] = "EXP_LIGHT_SCREEN_EFFECT",
  [37] = "EXP_REST_EFFECT",
  [46] = "EXP_MIST_EFFECT",
  [47] = "EXP_FOCUS_ENERGY_EFFECT",
  [49] = "EXP_CONFUSE_EFFECT",
  [50] = "EXP_STAT_FROM_EFFECT",
  [51] = "EXP_STAT_FROM_EFFECT",
  [52] = "EXP_STAT_FROM_EFFECT",
  [53] = "EXP_STAT_FROM_EFFECT",
  [54] = "EXP_STAT_FROM_EFFECT",
  [58] = "EXP_STAT_FROM_EFFECT",
  [59] = "EXP_STAT_FROM_EFFECT",
  [60] = "EXP_STAT_FROM_EFFECT",
  [62] = "EXP_STAT_FROM_EFFECT",
  [57] = "EXP_TRANSFORM_EFFECT",
  [65] = "EXP_REFLECT_EFFECT",
  [66] = "EXP_POISON_EFFECT",
  [67] = "EXP_PARALYZE_EFFECT",
  [79] = "EXP_SUBSTITUTE_EFFECT",
  [82] = "EXP_MIMIC_EFFECT",
  [84] = "EXP_LEECH_SEED_EFFECT",
  [85] = "EXP_SPLASH_EFFECT",
  [86] = "EXP_DISABLE_EFFECT",
  [90] = "EXP_ENCORE_EFFECT",
  [91] = "EXP_PAIN_SPLIT_EFFECT",
  [93] = "EXP_CONVERSION_2_EFFECT",
  [94] = "EXP_LOCK_ON_EFFECT",
  [95] = "EXP_SKETCH_EFFECT",
  [98] = "EXP_DESTINY_BOND_EFFECT",
  [100] = "EXP_SPITE_EFFECT",
  [102] = "EXP_HEAL_BELL_EFFECT",
  [106] = "EXP_MEAN_LOOK_EFFECT",
  [107] = "EXP_NIGHTMARE_EFFECT",
  [108] = "EXP_MINIMIZE_EFFECT",
  [109] = "EXP_CURSE_EFFECT",
  [111] = "EXP_PROTECT_EFFECT",
  [112] = "EXP_SPIKES_EFFECT",
  [113] = "EXP_FORESIGHT_EFFECT",
  [114] = "EXP_PERISH_SONG_EFFECT",
  [115] = "EXP_WEATHER_SANDSTORM",
  [116] = "EXP_ENDURE_EFFECT",
  [118] = "EXP_SWAGGER_EFFECT",
  [120] = "EXP_ATTRACT_EFFECT",
  [124] = "EXP_SAFEGUARD_EFFECT",
  [132] = "EXP_MORNING_SUN_EFFECT",
  [133] = "EXP_MORNING_SUN_EFFECT",
  [134] = "EXP_MORNING_SUN_EFFECT",
  [127] = "EXP_BATON_PASS_EFFECT",
  [136] = "EXP_WEATHER_RAINY",
  [137] = "EXP_WEATHER_SUNNY",
  [142] = "EXP_BELLY_DRUM_EFFECT",
  [143] = "EXP_PSYCH_UP_EFFECT",
  [148] = "EXP_FUTURE_SIGHT_EFFECT",
  [153] = "EXP_TELEPORT_EFFECT",
  [156] = "EXP_DEFENSE_CURL_EFFECT",
  [157] = "EXP_SOFTBOILED_EFFECT",
  [160] = "EXP_STOCKPILE_EFFECT",
  [162] = "EXP_SWALLOW_EFFECT",
  [164] = "EXP_WEATHER_HAIL",
  [165] = "EXP_TORMENT_EFFECT",
  [166] = "EXP_FLATTER_EFFECT",
  [167] = "EXP_BURN_EFFECT",
  [168] = "EXP_MEMENTO_EFFECT",
  [172] = "EXP_FOLLOW_ME_EFFECT",
  [174] = "EXP_CHARGE_EFFECT",
  [175] = "EXP_TAUNT_EFFECT",
  [176] = "EXP_HELPING_HAND_EFFECT",
  [177] = "EXP_TRICK_EFFECT",
  [178] = "EXP_ROLE_PLAY_EFFECT",
  [179] = "EXP_WISH_EFFECT",
  [181] = "EXP_INGRAIN_EFFECT",
  [183] = "EXP_MAGIC_COAT_EFFECT",
  [184] = "EXP_RECYCLE_EFFECT",
  [187] = "EXP_YAWN_EFFECT",
  [191] = "EXP_SKILL_SWAP_EFFECT",
  [192] = "EXP_IMPRISON_EFFECT",
  [193] = "EXP_REFRESH_EFFECT",
  [194] = "EXP_GRUDGE_EFFECT",
  [195] = "EXP_SNATCH_EFFECT",
  [199] = "EXP_TEETER_DANCE",
  [201] = "EXP_MUD_SPORT_EFFECT",
  [205] = "EXP_TICKLE_EFFECT",
  [206] = "EXP_COSMIC_POWER_EFFECT",
  [208] = "EXP_BULK_UP",
  [210] = "EXP_WATER_SPORT_EFFECT",
  [211] = "EXP_CALM_MIND",
  [212] = "EXP_DRAGON_DANCE",
  [213] = "EXP_CAMOUFLAGE_EFFECT",
}

-- Stage specs for EXP_STAT_FROM_EFFECT (self=true → user, else target).
EffectIds.STAT_CHANGES = {
  [10] = { self = true, stages = { attack = 1 } },
  [11] = { self = true, stages = { defense = 1 } },
  [13] = { self = true, stages = { spAtk = 1 } },
  [16] = { self = true, stages = { evasion = 1 } },
  [18] = { self = false, stages = { attack = -1 } },
  [19] = { self = false, stages = { defense = -1 } },
  [20] = { self = false, stages = { speed = -1 } },
  [23] = { self = false, stages = { accuracy = -1 } },
  [24] = { self = false, stages = { evasion = -1 } },
  [50] = { self = true, stages = { attack = 2 } },
  [51] = { self = true, stages = { defense = 2 } },
  [52] = { self = true, stages = { speed = 2 } },
  [53] = { self = true, stages = { spAtk = 2 } },
  [54] = { self = true, stages = { spDef = 2 } },
  [58] = { self = false, stages = { attack = -2 } },
  [59] = { self = false, stages = { defense = -2 } },
  [60] = { self = false, stages = { speed = -2 } },
  [62] = { self = false, stages = { spDef = -2 } },
  [108] = { self = true, stages = { evasion = 1 } },
  [156] = { self = true, stages = { defense = 1 } },
}

return EffectIds
