return {
  id = "frlg",

  tasks = {
    { id = "gba", run = "gba", weight = 0.20 },
    { id = "scripts_ow", run = "scripts_ow", weight = 0.20 },
    { id = "pokemon", run = "pokemon", weight = 0.20 },
    { id = "pokemon_gfx", run = "pokemon_gfx", weight = 0.15 },
    { id = "aux", run = "aux", weight = 0.15 },
    { id = "intro_audio", run = "intro_audio", weight = 0.10 },
  },

  speciesSplit = 200,

  sequential = { "gba", "pokemon", "aux", "intro_audio" },

  pokemonAfter = {
    "src.import.gba.seagallop_extract",
    "src.import.gba.cave_transition_extract",
    "src.import.gba.weather_extract",
    "src.import.gba.ingame_trades_extract",
    "src.import.gba.union_room_classes_extract",
  },

  auxSteps = 20,
  aux = {
    { name = "region_map_extract", key = "regionMap", label = "Town Map", mode = "raise" },
    { name = "map_sections_extract", key = "mapSections", label = "Map Sections", mode = "sections" },
    { name = "multichoice_extract", key = "multichoice", label = "Dialog Menus", mode = "raise" },
    { name = "heal_locations_extract", key = "healLocations", label = "Heal Locations", mode = "result",
      tag = "heal_locations" },
    { name = "door_anim_extract", key = "doors", label = "Door Animations", mode = "warn", tag = "door_extract" },
    { name = "slot_machine_extract", key = "slotMachine", label = "Slot Machines", mode = "warn" },
    { name = "trade_extract", key = "trade", label = "Link Trade", mode = "warn" },
    { name = "link_art_extract", key = "linkArt", label = "Wireless Union", mode = "warn" },
    { name = "fame_checker_extract", key = "fameChecker", label = "Fame Checker", mode = "warn" },
    { name = "teachy_tv_extract", key = "teachyTv", label = "Teachy TV", mode = "warn" },
    { name = "mystery_gift_extract", key = "mysteryGift", label = "Mystery Gift", mode = "warn" },
    { name = "trainer_tower_extract", key = "trainerTower", label = "Trainer Tower", mode = "warn" },
    { name = "tutor_extract", key = "tutor", label = "Move Tutors", mode = "warn" },
    { name = "museum_extract", key = "museum", label = "Museum Exhibits", mode = "warn" },
    { name = "move_relearner_extract", key = "moveRelearner", label = "Move Relearner", mode = "warn" },
    { name = "egg_extract", key = "egg", label = "Egg & Hatching", mode = "warn" },
    { name = "battle_anim_extract", key = "battleAnims", label = "Battle Animations", mode = "warn",
      opts = { force = false } },
    { name = "battle_ai_extract", key = "battleAi", label = "Battle AI Scripts", mode = "raise" },
    { name = "map_preview_extract", key = "mapPreview", label = "Location Previews", mode = "warn",
      tag = "map_preview" },
    { name = "credits_extract", key = "credits", label = "Staff Credits", mode = "raise" },
    { name = "league_extract", key = "league", label = "League Lighting & Diploma", mode = "raise" },
  },

  dirs = {
    "",
    "/pokemon",
    "/pokemon/front",
    "/pokemon/back",
    "/pokemon/front_shiny",
    "/pokemon/back_shiny",
    "/pokemon/icons",
    "/pokemon/party",
    "/pokemon/storage",
    "/pokemon/battle",
    "/pokemon/pokedex",
    "/region_map",
    "/map_preview",
    "/items",
    "/items/bag",
    "/items/shop",
    "/items/tm_case",
    "/items/berry_pouch",
    "/battle_ai",
    "/intro",
    "/audio",
    "/chrome",
    "/chrome/fonts",
    "/ow",
    "/native",
    "/rse",
    "/rse/trainer_card",
  },
}
