#!/usr/bin/env python3
"""Bake FRLG FONT_SMALL (latin_small.hwlatfont) into CHARMAP-ordered sheets.

FireRed USA 1.0:
  sFontSmallLatinGlyphs @ 0x1EAF00 — 32 bytes/glyph (two 8×8 2bpp tiles)
  sFontSmallLatinGlyphWidths @ 0x1EEF00

Bit packing matches gbagfx ConvertFromLatinFont / our latin_normal bake:
  each tile row is a little-endian u16; MSB-first 2bpp within each byte.

Usage:
  python3 extract_latin_small.py baseroms/firered.gba
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]  # sevii/gba
FONT_DIR = ROOT / "chrome" / "fonts"
FONT_BASE = 0x1EAF00
WIDTH_BASE = 0x1EEF00
GLYPH_BYTES = 32
# CHAR_EXTRA_SYMBOL (0xF9) ids are ORed with 0x100 in the text printer
# (e.g. LV_2 → glyph 0x105). Include those extra latin_small glyphs.
GLYPH_COUNT = 0x120  # 0x00..0x11F


def unpack_tile(data16: bytes) -> list[list[int]]:
    pix = [[0] * 8 for _ in range(8)]
    for y in range(8):
        for x in range(8):
            byte_i = y * 2 + (1 - (x // 4))
            shift = (3 - (x % 4)) * 2
            pix[y][x] = (data16[byte_i] >> shift) & 3
    return pix


def bake(rom: bytes) -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    cols = 16
    rows = (GLYPH_COUNT + cols - 1) // cols
    sheet_w, sheet_h = cols * 16, rows * 16
    fg = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
    sh = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
    indexed = Image.new("P", (sheet_w, sheet_h))
    indexed.putpalette(
        [0, 0, 0, 56, 56, 56, 216, 216, 216, 255, 255, 255] + [0] * (252 * 3)
    )

    widths: dict[int, int] = {}
    for gid in range(GLYPH_COUNT):
        blob = rom[FONT_BASE + gid * GLYPH_BYTES : FONT_BASE + (gid + 1) * GLYPH_BYTES]
        tiles = (unpack_tile(blob[:16]), unpack_tile(blob[16:]))
        ox, oy = (gid % cols) * 16, (gid // cols) * 16
        for ti, tile in enumerate(tiles):
            for y in range(8):
                for x in range(8):
                    v = tile[y][x]
                    px, py = ox + x, oy + y + ti * 8
                    indexed.putpixel((px, py), v)
                    if v == 1:
                        fg.putpixel((px, py), (255, 255, 255, 255))
                    elif v == 2:
                        sh.putpixel((px, py), (255, 255, 255, 255))
        # Width table is 256 entries in ROM; EXTRA glyphs read the trailing
        # bytes pret indexes the same way (LV_2 width = 8).
        widths[gid] = rom[WIDTH_BASE + gid]

    fg.save(FONT_DIR / "latin_small_fg.png")
    sh.save(FONT_DIR / "latin_small_shadow.png")
    indexed.save(FONT_DIR / "latin_small.png")

    lines = [
        "-- sFontSmallLatinGlyphWidths (FireRed @ 0x1EEF00) + EXTRA (0x100+)",
        "-- Generated by extract_latin_small.py — do not hand-edit.",
        "return {",
    ]
    last = GLYPH_COUNT - 1
    for i in range(GLYPH_COUNT):
        comma = "," if i < last else ""
        lines.append(f"  [{i}] = {widths[i]}{comma}")
    lines.append("}")
    (FONT_DIR / "latin_small_widths.lua").write_text("\n".join(lines) + "\n")
    print(
        f"wrote {FONT_DIR}/latin_small_{{fg,shadow,}}.png + widths "
        f"({GLYPH_COUNT} glyphs, LV_2={widths[0x105]}, slash={widths[0xBA]})"
    )


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    path = Path(sys.argv[1])
    if not path.is_file():
        print(f"missing ROM: {path}", file=sys.stderr)
        return 1
    bake(path.read_bytes())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
