#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/assets/otrlog.txt"
ASSETS_ZIP="$GAMEDIR/assets/extractor.zip"
ASSETS_DIR="$GAMEDIR/assets"

# Redirect output and error to the log file
exec > >(tee "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export LD_LIBRARY_PATH="$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"

# Check if we need to unzip the assets archive
unzip_assets() {
    # Define 7zzs binary
    SEVENZIP="$controlfolder/7zzs.${DEVICE_ARCH}"
    if [ ! -x "$SEVENZIP" ]; then
        echo "7zzs binary not found at $SEVENZIP"
        return 1
    fi

    if [ -f "$ASSETS_ZIP" ]; then
        echo "Extracting assets.zip..."
        if "$SEVENZIP" x -y "$ASSETS_ZIP" -o"$ASSETS_DIR" >/dev/null; then
            rm -f "$ASSETS_ZIP"
        else
            echo "[OTRGEN] Unable to extract assets.zip."
            return 1
        fi
    fi
}

process_rom() {
    local romfile=$1

    # Compute SHA-1 hash of the file
    ROMHASH=$(sha1sum -b "$romfile" 2>> "$LOGFILE" | awk '{ print $1 }') || { echo "Error: Failed to compute SHA-1 hash" >> "$LOGFILE"; return 1; }

    # Remap v64 and n64 hashes to their z64 hash equivalent
    case "$ROMHASH" in
    ef6d7273a7bc1cbf778f9021753db5efddfe495e) ROMHASH=7f5630dbc4d5d61d6276213210c4d5cdd83a47d6 ;; # v64
    991460c32f53c7bb0bc650baf5a40ffde6165840) ROMHASH=7f5630dbc4d5d61d6276213210c4d5cdd83a47d6 ;; # n64
    22f8bfa1ab6c763013a3c2a568bb014395b12499) ROMHASH=d6133ace5afaa0882cf214cf88daba39e266c078 ;; # v64
    1a26735c63cb3bdf5eb32d21acf774ee6724f227) ROMHASH=d6133ace5afaa0882cf214cf88daba39e266c078 ;; # n64
    8c378b87c83b3f4de20b14accf91e7590399f5dc) ROMHASH=9743aa026e9269b339eb0e3044cd5830a440c1fd ;; # v64
    8b0436e540b95a5353969d4ee360273cf33fb659) ROMHASH=9743aa026e9269b339eb0e3044cd5830a440c1fd ;; # n64
    esac

    case "$ROMHASH" in
    7f5630dbc4d5d61d6276213210c4d5cdd83a47d6) ROM=N64_US;;
    d6133ace5afaa0882cf214cf88daba39e266c078) ROM=N64_US;;
    9743aa026e9269b339eb0e3044cd5830a440c1fd) ROM=GC_US;;
    *)
        echo "[OTRGEN] Unsupported ROM hash: $ROMHASH" | tee -a "$LOGFILE"
        return 1
        ;;
    esac

    OTRNAME="mm.o2r"
    if [ ! -e "$GAMEDIR/$OTRNAME" ]; then
        echo "Generating $OTRNAME from $romfile..." | tee -a $LOGFILE
        if "$GAMEDIR/assets/extractor/ZAPD.out.${DEVICE_ARCH}" ed -eh -i "$GAMEDIR/assets/xml/$ROM" -b "$romfile" -fl "$GAMEDIR/assets/extractor/filelists/" -o placeholder -osf placeholder -gsf 1 -rconf "$GAMEDIR/assets/extractor/Config_$ROM.xml" -se OTR --otrfile "$OTRNAME" --portVer "4.0.2" >> "$LOGFILE" 2>&1; then
            echo "[OTRGEN] Successfully generated $OTRNAME"
        else
            echo "[OTRGEN] Failed to generate $OTRNAME."
            return 1
        fi
    fi
}

# Main logic
rom_file=$(find "$GAMEDIR/baseroms" -maxdepth 1 \( -name "*.z64" -o -name "*.n64" \) -print -quit)

# Test if regenerating o2r
if [ -n "$REGEN" ] && [ ! -f "$ASSETS_ZIP" ]; then
    echo "[OTRGEN] Attempt to regenerate o2r with old assets!"
    echo "[OTRGEN] Copy tools/assets.zip and remove the old tools/assets directory!"
    echo "Patching process failed!"
    exit 1
fi

if [ -z "$rom_file" ]; then
    echo "[OTRGEN] No ROM file found in baseroms!"
    exit 1
fi

if [ -f "$ASSETS_ZIP" ]; then
    unzip_assets
fi

echo "Processing $rom_file..."

if [ -n "$rom_file" ]; then
    process_rom "$rom_file"  || { echo "Patching process failed!"; exit 1; }
fi

# Cleanup
rm -rf "$GAMEDIR/placeholder"
echo "Patching process complete!"