-- tools/gen_gba_constants.py from pokefirered/include/constants/easy_chat.h
return {
  byId = {
    EC_GROUP_ = {
      [0] = "EC_GROUP_POKEMON_2",
      [1] = "EC_GROUP_TRAINER",
      [2] = "EC_GROUP_STATUS",
      [3] = "EC_GROUP_BATTLE",
      [4] = "EC_GROUP_GREETINGS",
      [5] = "EC_GROUP_PEOPLE",
      [6] = "EC_GROUP_VOICES",
      [7] = "EC_GROUP_SPEECH",
      [8] = "EC_GROUP_ENDINGS",
      [9] = "EC_GROUP_FEELINGS",
      [10] = "EC_GROUP_CONDITIONS",
      [11] = "EC_GROUP_ACTIONS",
      [12] = "EC_GROUP_LIFESTYLE",
      [13] = "EC_GROUP_HOBBIES",
      [14] = "EC_GROUP_TIME",
      [15] = "EC_GROUP_MISC",
      [16] = "EC_GROUP_ADJECTIVES",
      [17] = "EC_GROUP_EVENTS",
      [18] = "EC_GROUP_MOVE_1",
      [19] = "EC_GROUP_MOVE_2",
      [20] = "EC_GROUP_TRENDY_SAYING",
      [21] = "EC_GROUP_POKEMON",
    },
  },
  byName = {
    EC_GROUP_ACTIONS = 11,
    EC_GROUP_ADJECTIVES = 16,
    EC_GROUP_BATTLE = 3,
    EC_GROUP_CONDITIONS = 10,
    EC_GROUP_ENDINGS = 8,
    EC_GROUP_EVENTS = 17,
    EC_GROUP_FEELINGS = 9,
    EC_GROUP_GREETINGS = 4,
    EC_GROUP_HOBBIES = 13,
    EC_GROUP_LIFESTYLE = 12,
    EC_GROUP_MISC = 15,
    EC_GROUP_MOVE_1 = 18,
    EC_GROUP_MOVE_2 = 19,
    EC_GROUP_PEOPLE = 5,
    EC_GROUP_POKEMON = 21,
    EC_GROUP_POKEMON_2 = 0,
    EC_GROUP_SPEECH = 7,
    EC_GROUP_STATUS = 2,
    EC_GROUP_TIME = 14,
    EC_GROUP_TRAINER = 1,
    EC_GROUP_TRENDY_SAYING = 20,
    EC_GROUP_VOICES = 6,
    EC_NUM_GROUPS = 22,
    EC_WORD_UNDEFINED = 65535,
  },
}
