-- tools/gen_gba_constants.py from pokefirered/data/maps/map_groups.json
return {
  byName = {
    MAP_BATTLE_COLOSSEUM_2P = { group = 0, name = "BattleColosseum_2P", num = 0 },
    MAP_BATTLE_COLOSSEUM_4P = { group = 0, name = "BattleColosseum_4P", num = 3 },
    MAP_BIRTH_ISLAND_EXTERIOR = { group = 2, name = "BirthIsland_Exterior", num = 56 },
    MAP_BIRTH_ISLAND_HARBOR = { group = 2, name = "BirthIsland_Harbor", num = 58 },
    MAP_CELADON_CITY = { group = 3, name = "CeladonCity", num = 6 },
    MAP_CELADON_CITY_CONDOMINIUMS_1F = { group = 10, name = "CeladonCity_Condominiums_1F", num = 7 },
    MAP_CELADON_CITY_CONDOMINIUMS_2F = { group = 10, name = "CeladonCity_Condominiums_2F", num = 8 },
    MAP_CELADON_CITY_CONDOMINIUMS_3F = { group = 10, name = "CeladonCity_Condominiums_3F", num = 9 },
    MAP_CELADON_CITY_CONDOMINIUMS_ROOF = { group = 10, name = "CeladonCity_Condominiums_Roof", num = 10 },
    MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM = { group = 10, name = "CeladonCity_Condominiums_RoofRoom", num = 11 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_1F = { group = 10, name = "CeladonCity_DepartmentStore_1F", num = 0 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_2F = { group = 10, name = "CeladonCity_DepartmentStore_2F", num = 1 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_3F = { group = 10, name = "CeladonCity_DepartmentStore_3F", num = 2 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_4F = { group = 10, name = "CeladonCity_DepartmentStore_4F", num = 3 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_5F = { group = 10, name = "CeladonCity_DepartmentStore_5F", num = 4 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR = { group = 10, name = "CeladonCity_DepartmentStore_Elevator", num = 6 },
    MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF = { group = 10, name = "CeladonCity_DepartmentStore_Roof", num = 5 },
    MAP_CELADON_CITY_GAME_CORNER = { group = 10, name = "CeladonCity_GameCorner", num = 14 },
    MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM = { group = 10, name = "CeladonCity_GameCorner_PrizeRoom", num = 15 },
    MAP_CELADON_CITY_GYM = { group = 10, name = "CeladonCity_Gym", num = 16 },
    MAP_CELADON_CITY_HOTEL = { group = 10, name = "CeladonCity_Hotel", num = 19 },
    MAP_CELADON_CITY_HOUSE1 = { group = 10, name = "CeladonCity_House1", num = 18 },
    MAP_CELADON_CITY_POKEMON_CENTER_1F = { group = 10, name = "CeladonCity_PokemonCenter_1F", num = 12 },
    MAP_CELADON_CITY_POKEMON_CENTER_2F = { group = 10, name = "CeladonCity_PokemonCenter_2F", num = 13 },
    MAP_CELADON_CITY_RESTAURANT = { group = 10, name = "CeladonCity_Restaurant", num = 17 },
    MAP_CERULEAN_CAVE_1F = { group = 1, name = "CeruleanCave_1F", num = 72 },
    MAP_CERULEAN_CAVE_2F = { group = 1, name = "CeruleanCave_2F", num = 73 },
    MAP_CERULEAN_CAVE_B1F = { group = 1, name = "CeruleanCave_B1F", num = 74 },
    MAP_CERULEAN_CITY = { group = 3, name = "CeruleanCity", num = 3 },
    MAP_CERULEAN_CITY_BIKE_SHOP = { group = 7, name = "CeruleanCity_BikeShop", num = 6 },
    MAP_CERULEAN_CITY_GYM = { group = 7, name = "CeruleanCity_Gym", num = 5 },
    MAP_CERULEAN_CITY_HOUSE1 = { group = 7, name = "CeruleanCity_House1", num = 0 },
    MAP_CERULEAN_CITY_HOUSE2 = { group = 7, name = "CeruleanCity_House2", num = 1 },
    MAP_CERULEAN_CITY_HOUSE3 = { group = 7, name = "CeruleanCity_House3", num = 2 },
    MAP_CERULEAN_CITY_HOUSE4 = { group = 7, name = "CeruleanCity_House4", num = 8 },
    MAP_CERULEAN_CITY_HOUSE5 = { group = 7, name = "CeruleanCity_House5", num = 9 },
    MAP_CERULEAN_CITY_MART = { group = 7, name = "CeruleanCity_Mart", num = 7 },
    MAP_CERULEAN_CITY_POKEMON_CENTER_1F = { group = 7, name = "CeruleanCity_PokemonCenter_1F", num = 3 },
    MAP_CERULEAN_CITY_POKEMON_CENTER_2F = { group = 7, name = "CeruleanCity_PokemonCenter_2F", num = 4 },
    MAP_CINNABAR_ISLAND = { group = 3, name = "CinnabarIsland", num = 8 },
    MAP_CINNABAR_ISLAND_GYM = { group = 12, name = "CinnabarIsland_Gym", num = 0 },
    MAP_CINNABAR_ISLAND_MART = { group = 12, name = "CinnabarIsland_Mart", num = 7 },
    MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F = { group = 12, name = "CinnabarIsland_PokemonCenter_1F", num = 5 },
    MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F = { group = 12, name = "CinnabarIsland_PokemonCenter_2F", num = 6 },
    MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE = { group = 12, name = "CinnabarIsland_PokemonLab_Entrance", num = 1 },
    MAP_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM = { group = 12, name = "CinnabarIsland_PokemonLab_ExperimentRoom", num = 4 },
    MAP_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE = { group = 12, name = "CinnabarIsland_PokemonLab_Lounge", num = 2 },
    MAP_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM = { group = 12, name = "CinnabarIsland_PokemonLab_ResearchRoom", num = 3 },
    MAP_DIGLETTS_CAVE_B1F = { group = 1, name = "DiglettsCave_B1F", num = 37 },
    MAP_DIGLETTS_CAVE_NORTH_ENTRANCE = { group = 1, name = "DiglettsCave_NorthEntrance", num = 36 },
    MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE = { group = 1, name = "DiglettsCave_SouthEntrance", num = 38 },
    MAP_FIVE_ISLAND = { group = 3, name = "FiveIsland", num = 16 },
    MAP_FIVE_ISLAND_HARBOR = { group = 36, name = "FiveIsland_Harbor", num = 2 },
    MAP_FIVE_ISLAND_HOUSE1 = { group = 36, name = "FiveIsland_House1", num = 3 },
    MAP_FIVE_ISLAND_HOUSE2 = { group = 36, name = "FiveIsland_House2", num = 4 },
    MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE = { group = 2, name = "FiveIsland_LostCave_Entrance", num = 12 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM1 = { group = 2, name = "FiveIsland_LostCave_Room1", num = 13 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM10 = { group = 2, name = "FiveIsland_LostCave_Room10", num = 22 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM11 = { group = 2, name = "FiveIsland_LostCave_Room11", num = 23 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM12 = { group = 2, name = "FiveIsland_LostCave_Room12", num = 24 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM13 = { group = 2, name = "FiveIsland_LostCave_Room13", num = 25 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM14 = { group = 2, name = "FiveIsland_LostCave_Room14", num = 26 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM2 = { group = 2, name = "FiveIsland_LostCave_Room2", num = 14 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM3 = { group = 2, name = "FiveIsland_LostCave_Room3", num = 15 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM4 = { group = 2, name = "FiveIsland_LostCave_Room4", num = 16 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM5 = { group = 2, name = "FiveIsland_LostCave_Room5", num = 17 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM6 = { group = 2, name = "FiveIsland_LostCave_Room6", num = 18 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM7 = { group = 2, name = "FiveIsland_LostCave_Room7", num = 19 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM8 = { group = 2, name = "FiveIsland_LostCave_Room8", num = 20 },
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM9 = { group = 2, name = "FiveIsland_LostCave_Room9", num = 21 },
    MAP_FIVE_ISLAND_MEADOW = { group = 3, name = "FiveIsland_Meadow", num = 56 },
    MAP_FIVE_ISLAND_MEMORIAL_PILLAR = { group = 3, name = "FiveIsland_MemorialPillar", num = 57 },
    MAP_FIVE_ISLAND_POKEMON_CENTER_1F = { group = 36, name = "FiveIsland_PokemonCenter_1F", num = 0 },
    MAP_FIVE_ISLAND_POKEMON_CENTER_2F = { group = 36, name = "FiveIsland_PokemonCenter_2F", num = 1 },
    MAP_FIVE_ISLAND_RESORT_GORGEOUS = { group = 3, name = "FiveIsland_ResortGorgeous", num = 54 },
    MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE = { group = 39, name = "FiveIsland_ResortGorgeous_House", num = 0 },
    MAP_FIVE_ISLAND_ROCKET_WAREHOUSE = { group = 1, name = "FiveIsland_RocketWarehouse", num = 114 },
    MAP_FIVE_ISLAND_WATER_LABYRINTH = { group = 3, name = "FiveIsland_WaterLabyrinth", num = 55 },
    MAP_FOUR_ISLAND = { group = 3, name = "FourIsland", num = 15 },
    MAP_FOUR_ISLAND_HARBOR = { group = 35, name = "FourIsland_Harbor", num = 5 },
    MAP_FOUR_ISLAND_HOUSE1 = { group = 35, name = "FourIsland_House1", num = 3 },
    MAP_FOUR_ISLAND_HOUSE2 = { group = 35, name = "FourIsland_House2", num = 6 },
    MAP_FOUR_ISLAND_ICEFALL_CAVE_1F = { group = 1, name = "FourIsland_IcefallCave_1F", num = 111 },
    MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F = { group = 1, name = "FourIsland_IcefallCave_B1F", num = 112 },
    MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK = { group = 1, name = "FourIsland_IcefallCave_Back", num = 113 },
    MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE = { group = 1, name = "FourIsland_IcefallCave_Entrance", num = 110 },
    MAP_FOUR_ISLAND_LORELEIS_HOUSE = { group = 35, name = "FourIsland_LoreleisHouse", num = 4 },
    MAP_FOUR_ISLAND_MART = { group = 35, name = "FourIsland_Mart", num = 7 },
    MAP_FOUR_ISLAND_POKEMON_CENTER_1F = { group = 35, name = "FourIsland_PokemonCenter_1F", num = 1 },
    MAP_FOUR_ISLAND_POKEMON_CENTER_2F = { group = 35, name = "FourIsland_PokemonCenter_2F", num = 2 },
    MAP_FOUR_ISLAND_POKEMON_DAY_CARE = { group = 35, name = "FourIsland_PokemonDayCare", num = 0 },
    MAP_FUCHSIA_CITY = { group = 3, name = "FuchsiaCity", num = 7 },
    MAP_FUCHSIA_CITY_GYM = { group = 11, name = "FuchsiaCity_Gym", num = 3 },
    MAP_FUCHSIA_CITY_HOUSE1 = { group = 11, name = "FuchsiaCity_House1", num = 4 },
    MAP_FUCHSIA_CITY_HOUSE2 = { group = 11, name = "FuchsiaCity_House2", num = 8 },
    MAP_FUCHSIA_CITY_HOUSE3 = { group = 11, name = "FuchsiaCity_House3", num = 9 },
    MAP_FUCHSIA_CITY_MART = { group = 11, name = "FuchsiaCity_Mart", num = 1 },
    MAP_FUCHSIA_CITY_POKEMON_CENTER_1F = { group = 11, name = "FuchsiaCity_PokemonCenter_1F", num = 5 },
    MAP_FUCHSIA_CITY_POKEMON_CENTER_2F = { group = 11, name = "FuchsiaCity_PokemonCenter_2F", num = 6 },
    MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE = { group = 11, name = "FuchsiaCity_SafariZone_Entrance", num = 0 },
    MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE = { group = 11, name = "FuchsiaCity_SafariZone_Office", num = 2 },
    MAP_FUCHSIA_CITY_WARDENS_HOUSE = { group = 11, name = "FuchsiaCity_WardensHouse", num = 7 },
    MAP_INDIGO_PLATEAU_EXTERIOR = { group = 3, name = "IndigoPlateau_Exterior", num = 9 },
    MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F = { group = 13, name = "IndigoPlateau_PokemonCenter_1F", num = 0 },
    MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F = { group = 13, name = "IndigoPlateau_PokemonCenter_2F", num = 1 },
    MAP_LAVENDER_TOWN = { group = 3, name = "LavenderTown", num = 4 },
    MAP_LAVENDER_TOWN_HOUSE1 = { group = 8, name = "LavenderTown_House1", num = 3 },
    MAP_LAVENDER_TOWN_HOUSE2 = { group = 8, name = "LavenderTown_House2", num = 4 },
    MAP_LAVENDER_TOWN_MART = { group = 8, name = "LavenderTown_Mart", num = 5 },
    MAP_LAVENDER_TOWN_POKEMON_CENTER_1F = { group = 8, name = "LavenderTown_PokemonCenter_1F", num = 0 },
    MAP_LAVENDER_TOWN_POKEMON_CENTER_2F = { group = 8, name = "LavenderTown_PokemonCenter_2F", num = 1 },
    MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE = { group = 8, name = "LavenderTown_VolunteerPokemonHouse", num = 2 },
    MAP_MT_EMBER_EXTERIOR = { group = 1, name = "MtEmber_Exterior", num = 97 },
    MAP_MT_EMBER_RUBY_PATH_1F = { group = 1, name = "MtEmber_RubyPath_1F", num = 103 },
    MAP_MT_EMBER_RUBY_PATH_B1F = { group = 1, name = "MtEmber_RubyPath_B1F", num = 104 },
    MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS = { group = 1, name = "MtEmber_RubyPath_B1F_Stairs", num = 107 },
    MAP_MT_EMBER_RUBY_PATH_B2F = { group = 1, name = "MtEmber_RubyPath_B2F", num = 105 },
    MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS = { group = 1, name = "MtEmber_RubyPath_B2F_Stairs", num = 108 },
    MAP_MT_EMBER_RUBY_PATH_B3F = { group = 1, name = "MtEmber_RubyPath_B3F", num = 106 },
    MAP_MT_EMBER_RUBY_PATH_B4F = { group = 1, name = "MtEmber_RubyPath_B4F", num = 96 },
    MAP_MT_EMBER_RUBY_PATH_B5F = { group = 1, name = "MtEmber_RubyPath_B5F", num = 102 },
    MAP_MT_EMBER_SUMMIT = { group = 1, name = "MtEmber_Summit", num = 101 },
    MAP_MT_EMBER_SUMMIT_PATH_1F = { group = 1, name = "MtEmber_SummitPath_1F", num = 98 },
    MAP_MT_EMBER_SUMMIT_PATH_2F = { group = 1, name = "MtEmber_SummitPath_2F", num = 99 },
    MAP_MT_EMBER_SUMMIT_PATH_3F = { group = 1, name = "MtEmber_SummitPath_3F", num = 100 },
    MAP_MT_MOON_1F = { group = 1, name = "MtMoon_1F", num = 1 },
    MAP_MT_MOON_B1F = { group = 1, name = "MtMoon_B1F", num = 2 },
    MAP_MT_MOON_B2F = { group = 1, name = "MtMoon_B2F", num = 3 },
    MAP_NAVEL_ROCK_1F = { group = 2, name = "NavelRock_1F", num = 36 },
    MAP_NAVEL_ROCK_B1F = { group = 2, name = "NavelRock_B1F", num = 54 },
    MAP_NAVEL_ROCK_BASE = { group = 2, name = "NavelRock_Base", num = 38 },
    MAP_NAVEL_ROCK_BASE_PATH_B10F = { group = 2, name = "NavelRock_BasePath_B10F", num = 52 },
    MAP_NAVEL_ROCK_BASE_PATH_B11F = { group = 2, name = "NavelRock_BasePath_B11F", num = 53 },
    MAP_NAVEL_ROCK_BASE_PATH_B1F = { group = 2, name = "NavelRock_BasePath_B1F", num = 43 },
    MAP_NAVEL_ROCK_BASE_PATH_B2F = { group = 2, name = "NavelRock_BasePath_B2F", num = 44 },
    MAP_NAVEL_ROCK_BASE_PATH_B3F = { group = 2, name = "NavelRock_BasePath_B3F", num = 45 },
    MAP_NAVEL_ROCK_BASE_PATH_B4F = { group = 2, name = "NavelRock_BasePath_B4F", num = 46 },
    MAP_NAVEL_ROCK_BASE_PATH_B5F = { group = 2, name = "NavelRock_BasePath_B5F", num = 47 },
    MAP_NAVEL_ROCK_BASE_PATH_B6F = { group = 2, name = "NavelRock_BasePath_B6F", num = 48 },
    MAP_NAVEL_ROCK_BASE_PATH_B7F = { group = 2, name = "NavelRock_BasePath_B7F", num = 49 },
    MAP_NAVEL_ROCK_BASE_PATH_B8F = { group = 2, name = "NavelRock_BasePath_B8F", num = 50 },
    MAP_NAVEL_ROCK_BASE_PATH_B9F = { group = 2, name = "NavelRock_BasePath_B9F", num = 51 },
    MAP_NAVEL_ROCK_EXTERIOR = { group = 2, name = "NavelRock_Exterior", num = 0 },
    MAP_NAVEL_ROCK_FORK = { group = 2, name = "NavelRock_Fork", num = 55 },
    MAP_NAVEL_ROCK_HARBOR = { group = 2, name = "NavelRock_Harbor", num = 59 },
    MAP_NAVEL_ROCK_SUMMIT = { group = 2, name = "NavelRock_Summit", num = 37 },
    MAP_NAVEL_ROCK_SUMMIT_PATH_2F = { group = 2, name = "NavelRock_SummitPath_2F", num = 39 },
    MAP_NAVEL_ROCK_SUMMIT_PATH_3F = { group = 2, name = "NavelRock_SummitPath_3F", num = 40 },
    MAP_NAVEL_ROCK_SUMMIT_PATH_4F = { group = 2, name = "NavelRock_SummitPath_4F", num = 41 },
    MAP_NAVEL_ROCK_SUMMIT_PATH_5F = { group = 2, name = "NavelRock_SummitPath_5F", num = 42 },
    MAP_ONE_ISLAND = { group = 3, name = "OneIsland", num = 12 },
    MAP_ONE_ISLAND_HARBOR = { group = 32, name = "OneIsland_Harbor", num = 4 },
    MAP_ONE_ISLAND_HOUSE1 = { group = 32, name = "OneIsland_House1", num = 2 },
    MAP_ONE_ISLAND_HOUSE2 = { group = 32, name = "OneIsland_House2", num = 3 },
    MAP_ONE_ISLAND_KINDLE_ROAD = { group = 3, name = "OneIsland_KindleRoad", num = 45 },
    MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA = { group = 2, name = "OneIsland_KindleRoad_EmberSpa", num = 57 },
    MAP_ONE_ISLAND_POKEMON_CENTER_1F = { group = 32, name = "OneIsland_PokemonCenter_1F", num = 0 },
    MAP_ONE_ISLAND_POKEMON_CENTER_2F = { group = 32, name = "OneIsland_PokemonCenter_2F", num = 1 },
    MAP_ONE_ISLAND_TREASURE_BEACH = { group = 3, name = "OneIsland_TreasureBeach", num = 46 },
    MAP_PALLET_TOWN = { group = 3, name = "PalletTown", num = 0 },
    MAP_PALLET_TOWN_PLAYERS_HOUSE_1F = { group = 4, name = "PalletTown_PlayersHouse_1F", num = 0 },
    MAP_PALLET_TOWN_PLAYERS_HOUSE_2F = { group = 4, name = "PalletTown_PlayersHouse_2F", num = 1 },
    MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB = { group = 4, name = "PalletTown_ProfessorOaksLab", num = 3 },
    MAP_PALLET_TOWN_RIVALS_HOUSE = { group = 4, name = "PalletTown_RivalsHouse", num = 2 },
    MAP_PEWTER_CITY = { group = 3, name = "PewterCity", num = 2 },
    MAP_PEWTER_CITY_GYM = { group = 6, name = "PewterCity_Gym", num = 2 },
    MAP_PEWTER_CITY_HOUSE1 = { group = 6, name = "PewterCity_House1", num = 4 },
    MAP_PEWTER_CITY_HOUSE2 = { group = 6, name = "PewterCity_House2", num = 7 },
    MAP_PEWTER_CITY_MART = { group = 6, name = "PewterCity_Mart", num = 3 },
    MAP_PEWTER_CITY_MUSEUM_1F = { group = 6, name = "PewterCity_Museum_1F", num = 0 },
    MAP_PEWTER_CITY_MUSEUM_2F = { group = 6, name = "PewterCity_Museum_2F", num = 1 },
    MAP_PEWTER_CITY_POKEMON_CENTER_1F = { group = 6, name = "PewterCity_PokemonCenter_1F", num = 5 },
    MAP_PEWTER_CITY_POKEMON_CENTER_2F = { group = 6, name = "PewterCity_PokemonCenter_2F", num = 6 },
    MAP_POKEMON_LEAGUE_AGATHAS_ROOM = { group = 1, name = "PokemonLeague_AgathasRoom", num = 77 },
    MAP_POKEMON_LEAGUE_BRUNOS_ROOM = { group = 1, name = "PokemonLeague_BrunosRoom", num = 76 },
    MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM = { group = 1, name = "PokemonLeague_ChampionsRoom", num = 79 },
    MAP_POKEMON_LEAGUE_HALL_OF_FAME = { group = 1, name = "PokemonLeague_HallOfFame", num = 80 },
    MAP_POKEMON_LEAGUE_LANCES_ROOM = { group = 1, name = "PokemonLeague_LancesRoom", num = 78 },
    MAP_POKEMON_LEAGUE_LORELEIS_ROOM = { group = 1, name = "PokemonLeague_LoreleisRoom", num = 75 },
    MAP_POKEMON_MANSION_1F = { group = 1, name = "PokemonMansion_1F", num = 59 },
    MAP_POKEMON_MANSION_2F = { group = 1, name = "PokemonMansion_2F", num = 60 },
    MAP_POKEMON_MANSION_3F = { group = 1, name = "PokemonMansion_3F", num = 61 },
    MAP_POKEMON_MANSION_B1F = { group = 1, name = "PokemonMansion_B1F", num = 62 },
    MAP_POKEMON_TOWER_1F = { group = 1, name = "PokemonTower_1F", num = 88 },
    MAP_POKEMON_TOWER_2F = { group = 1, name = "PokemonTower_2F", num = 89 },
    MAP_POKEMON_TOWER_3F = { group = 1, name = "PokemonTower_3F", num = 90 },
    MAP_POKEMON_TOWER_4F = { group = 1, name = "PokemonTower_4F", num = 91 },
    MAP_POKEMON_TOWER_5F = { group = 1, name = "PokemonTower_5F", num = 92 },
    MAP_POKEMON_TOWER_6F = { group = 1, name = "PokemonTower_6F", num = 93 },
    MAP_POKEMON_TOWER_7F = { group = 1, name = "PokemonTower_7F", num = 94 },
    MAP_POWER_PLANT = { group = 1, name = "PowerPlant", num = 95 },
    MAP_PROTOTYPE_SEVII_ISLE_6 = { group = 3, name = "Prototype_SeviiIsle_6", num = 50 },
    MAP_PROTOTYPE_SEVII_ISLE_7 = { group = 3, name = "Prototype_SeviiIsle_7", num = 51 },
    MAP_PROTOTYPE_SEVII_ISLE_8 = { group = 3, name = "Prototype_SeviiIsle_8", num = 52 },
    MAP_PROTOTYPE_SEVII_ISLE_9 = { group = 3, name = "Prototype_SeviiIsle_9", num = 53 },
    MAP_RECORD_CORNER = { group = 0, name = "RecordCorner", num = 2 },
    MAP_ROCKET_HIDEOUT_B1F = { group = 1, name = "RocketHideout_B1F", num = 42 },
    MAP_ROCKET_HIDEOUT_B2F = { group = 1, name = "RocketHideout_B2F", num = 43 },
    MAP_ROCKET_HIDEOUT_B3F = { group = 1, name = "RocketHideout_B3F", num = 44 },
    MAP_ROCKET_HIDEOUT_B4F = { group = 1, name = "RocketHideout_B4F", num = 45 },
    MAP_ROCKET_HIDEOUT_ELEVATOR = { group = 1, name = "RocketHideout_Elevator", num = 46 },
    MAP_ROCK_TUNNEL_1F = { group = 1, name = "RockTunnel_1F", num = 81 },
    MAP_ROCK_TUNNEL_B1F = { group = 1, name = "RockTunnel_B1F", num = 82 },
    MAP_ROUTE1 = { group = 3, name = "Route1", num = 19 },
    MAP_ROUTE10 = { group = 3, name = "Route10", num = 28 },
    MAP_ROUTE10_POKEMON_CENTER_1F = { group = 21, name = "Route10_PokemonCenter_1F", num = 0 },
    MAP_ROUTE10_POKEMON_CENTER_2F = { group = 21, name = "Route10_PokemonCenter_2F", num = 1 },
    MAP_ROUTE11 = { group = 3, name = "Route11", num = 29 },
    MAP_ROUTE11_EAST_ENTRANCE_1F = { group = 22, name = "Route11_EastEntrance_1F", num = 0 },
    MAP_ROUTE11_EAST_ENTRANCE_2F = { group = 22, name = "Route11_EastEntrance_2F", num = 1 },
    MAP_ROUTE12 = { group = 3, name = "Route12", num = 30 },
    MAP_ROUTE12_FISHING_HOUSE = { group = 23, name = "Route12_FishingHouse", num = 2 },
    MAP_ROUTE12_NORTH_ENTRANCE_1F = { group = 23, name = "Route12_NorthEntrance_1F", num = 0 },
    MAP_ROUTE12_NORTH_ENTRANCE_2F = { group = 23, name = "Route12_NorthEntrance_2F", num = 1 },
    MAP_ROUTE13 = { group = 3, name = "Route13", num = 31 },
    MAP_ROUTE14 = { group = 3, name = "Route14", num = 32 },
    MAP_ROUTE15 = { group = 3, name = "Route15", num = 33 },
    MAP_ROUTE15_WEST_ENTRANCE_1F = { group = 24, name = "Route15_WestEntrance_1F", num = 0 },
    MAP_ROUTE15_WEST_ENTRANCE_2F = { group = 24, name = "Route15_WestEntrance_2F", num = 1 },
    MAP_ROUTE16 = { group = 3, name = "Route16", num = 34 },
    MAP_ROUTE16_HOUSE = { group = 25, name = "Route16_House", num = 0 },
    MAP_ROUTE16_NORTH_ENTRANCE_1F = { group = 25, name = "Route16_NorthEntrance_1F", num = 1 },
    MAP_ROUTE16_NORTH_ENTRANCE_2F = { group = 25, name = "Route16_NorthEntrance_2F", num = 2 },
    MAP_ROUTE17 = { group = 3, name = "Route17", num = 35 },
    MAP_ROUTE18 = { group = 3, name = "Route18", num = 36 },
    MAP_ROUTE18_EAST_ENTRANCE_1F = { group = 26, name = "Route18_EastEntrance_1F", num = 0 },
    MAP_ROUTE18_EAST_ENTRANCE_2F = { group = 26, name = "Route18_EastEntrance_2F", num = 1 },
    MAP_ROUTE19 = { group = 3, name = "Route19", num = 37 },
    MAP_ROUTE19_UNUSED_HOUSE = { group = 27, name = "Route19_UnusedHouse", num = 0 },
    MAP_ROUTE2 = { group = 3, name = "Route2", num = 20 },
    MAP_ROUTE20 = { group = 3, name = "Route20", num = 38 },
    MAP_ROUTE21_NORTH = { group = 3, name = "Route21_North", num = 39 },
    MAP_ROUTE21_SOUTH = { group = 3, name = "Route21_South", num = 40 },
    MAP_ROUTE22 = { group = 3, name = "Route22", num = 41 },
    MAP_ROUTE22_NORTH_ENTRANCE = { group = 28, name = "Route22_NorthEntrance", num = 0 },
    MAP_ROUTE23 = { group = 3, name = "Route23", num = 42 },
    MAP_ROUTE23_UNUSED_HOUSE = { group = 29, name = "Route23_UnusedHouse", num = 0 },
    MAP_ROUTE24 = { group = 3, name = "Route24", num = 43 },
    MAP_ROUTE25 = { group = 3, name = "Route25", num = 44 },
    MAP_ROUTE25_SEA_COTTAGE = { group = 30, name = "Route25_SeaCottage", num = 0 },
    MAP_ROUTE2_EAST_BUILDING = { group = 15, name = "Route2_EastBuilding", num = 2 },
    MAP_ROUTE2_HOUSE = { group = 15, name = "Route2_House", num = 1 },
    MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE = { group = 15, name = "Route2_ViridianForest_NorthEntrance", num = 3 },
    MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE = { group = 15, name = "Route2_ViridianForest_SouthEntrance", num = 0 },
    MAP_ROUTE3 = { group = 3, name = "Route3", num = 21 },
    MAP_ROUTE4 = { group = 3, name = "Route4", num = 22 },
    MAP_ROUTE4_POKEMON_CENTER_1F = { group = 16, name = "Route4_PokemonCenter_1F", num = 0 },
    MAP_ROUTE4_POKEMON_CENTER_2F = { group = 16, name = "Route4_PokemonCenter_2F", num = 1 },
    MAP_ROUTE5 = { group = 3, name = "Route5", num = 23 },
    MAP_ROUTE5_POKEMON_DAY_CARE = { group = 17, name = "Route5_PokemonDayCare", num = 0 },
    MAP_ROUTE5_SOUTH_ENTRANCE = { group = 17, name = "Route5_SouthEntrance", num = 1 },
    MAP_ROUTE6 = { group = 3, name = "Route6", num = 24 },
    MAP_ROUTE6_NORTH_ENTRANCE = { group = 18, name = "Route6_NorthEntrance", num = 0 },
    MAP_ROUTE6_UNUSED_HOUSE = { group = 18, name = "Route6_UnusedHouse", num = 1 },
    MAP_ROUTE7 = { group = 3, name = "Route7", num = 25 },
    MAP_ROUTE7_EAST_ENTRANCE = { group = 19, name = "Route7_EastEntrance", num = 0 },
    MAP_ROUTE8 = { group = 3, name = "Route8", num = 26 },
    MAP_ROUTE8_WEST_ENTRANCE = { group = 20, name = "Route8_WestEntrance", num = 0 },
    MAP_ROUTE9 = { group = 3, name = "Route9", num = 27 },
    MAP_SAFARI_ZONE_CENTER = { group = 1, name = "SafariZone_Center", num = 63 },
    MAP_SAFARI_ZONE_CENTER_REST_HOUSE = { group = 1, name = "SafariZone_Center_RestHouse", num = 67 },
    MAP_SAFARI_ZONE_EAST = { group = 1, name = "SafariZone_East", num = 64 },
    MAP_SAFARI_ZONE_EAST_REST_HOUSE = { group = 1, name = "SafariZone_East_RestHouse", num = 68 },
    MAP_SAFARI_ZONE_NORTH = { group = 1, name = "SafariZone_North", num = 65 },
    MAP_SAFARI_ZONE_NORTH_REST_HOUSE = { group = 1, name = "SafariZone_North_RestHouse", num = 69 },
    MAP_SAFARI_ZONE_SECRET_HOUSE = { group = 1, name = "SafariZone_SecretHouse", num = 71 },
    MAP_SAFARI_ZONE_WEST = { group = 1, name = "SafariZone_West", num = 66 },
    MAP_SAFARI_ZONE_WEST_REST_HOUSE = { group = 1, name = "SafariZone_West_RestHouse", num = 70 },
    MAP_SAFFRON_CITY = { group = 3, name = "SaffronCity", num = 10 },
    MAP_SAFFRON_CITY_CONNECTION = { group = 3, name = "SaffronCity_Connection", num = 11 },
    MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F = { group = 14, name = "SaffronCity_CopycatsHouse_1F", num = 0 },
    MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F = { group = 14, name = "SaffronCity_CopycatsHouse_2F", num = 1 },
    MAP_SAFFRON_CITY_DOJO = { group = 14, name = "SaffronCity_Dojo", num = 2 },
    MAP_SAFFRON_CITY_GYM = { group = 14, name = "SaffronCity_Gym", num = 3 },
    MAP_SAFFRON_CITY_HOUSE = { group = 14, name = "SaffronCity_House", num = 4 },
    MAP_SAFFRON_CITY_MART = { group = 14, name = "SaffronCity_Mart", num = 5 },
    MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE = { group = 14, name = "SaffronCity_MrPsychicsHouse", num = 8 },
    MAP_SAFFRON_CITY_POKEMON_CENTER_1F = { group = 14, name = "SaffronCity_PokemonCenter_1F", num = 6 },
    MAP_SAFFRON_CITY_POKEMON_CENTER_2F = { group = 14, name = "SaffronCity_PokemonCenter_2F", num = 7 },
    MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB = { group = 14, name = "SaffronCity_PokemonTrainerFanClub", num = 9 },
    MAP_SEAFOAM_ISLANDS_1F = { group = 1, name = "SeafoamIslands_1F", num = 83 },
    MAP_SEAFOAM_ISLANDS_B1F = { group = 1, name = "SeafoamIslands_B1F", num = 84 },
    MAP_SEAFOAM_ISLANDS_B2F = { group = 1, name = "SeafoamIslands_B2F", num = 85 },
    MAP_SEAFOAM_ISLANDS_B3F = { group = 1, name = "SeafoamIslands_B3F", num = 86 },
    MAP_SEAFOAM_ISLANDS_B4F = { group = 1, name = "SeafoamIslands_B4F", num = 87 },
    MAP_SEVEN_ISLAND = { group = 3, name = "SevenIsland", num = 17 },
    MAP_SEVEN_ISLAND_HARBOR = { group = 31, name = "SevenIsland_Harbor", num = 6 },
    MAP_SEVEN_ISLAND_HOUSE_ROOM1 = { group = 31, name = "SevenIsland_House_Room1", num = 0 },
    MAP_SEVEN_ISLAND_HOUSE_ROOM2 = { group = 31, name = "SevenIsland_House_Room2", num = 1 },
    MAP_SEVEN_ISLAND_MART = { group = 31, name = "SevenIsland_Mart", num = 2 },
    MAP_SEVEN_ISLAND_POKEMON_CENTER_1F = { group = 31, name = "SevenIsland_PokemonCenter_1F", num = 3 },
    MAP_SEVEN_ISLAND_POKEMON_CENTER_2F = { group = 31, name = "SevenIsland_PokemonCenter_2F", num = 4 },
    MAP_SEVEN_ISLAND_SEVAULT_CANYON = { group = 3, name = "SevenIsland_SevaultCanyon", num = 64 },
    MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE = { group = 3, name = "SevenIsland_SevaultCanyon_Entrance", num = 63 },
    MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE = { group = 42, name = "SevenIsland_SevaultCanyon_House", num = 0 },
    MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY = { group = 2, name = "SevenIsland_SevaultCanyon_TanobyKey", num = 35 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS = { group = 3, name = "SevenIsland_TanobyRuins", num = 65 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_DilfordChamber", num = 30 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_LiptooChamber", num = 28 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_MoneanChamber", num = 27 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_RixyChamber", num = 32 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_ScufibChamber", num = 31 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_ViapoisChamber", num = 33 },
    MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER = { group = 2, name = "SevenIsland_TanobyRuins_WeepthChamber", num = 29 },
    MAP_SEVEN_ISLAND_TRAINER_TOWER = { group = 3, name = "SevenIsland_TrainerTower", num = 62 },
    MAP_SEVEN_ISLAND_UNUSED_HOUSE = { group = 31, name = "SevenIsland_UnusedHouse", num = 5 },
    MAP_SILPH_CO_10F = { group = 1, name = "SilphCo_10F", num = 56 },
    MAP_SILPH_CO_11F = { group = 1, name = "SilphCo_11F", num = 57 },
    MAP_SILPH_CO_1F = { group = 1, name = "SilphCo_1F", num = 47 },
    MAP_SILPH_CO_2F = { group = 1, name = "SilphCo_2F", num = 48 },
    MAP_SILPH_CO_3F = { group = 1, name = "SilphCo_3F", num = 49 },
    MAP_SILPH_CO_4F = { group = 1, name = "SilphCo_4F", num = 50 },
    MAP_SILPH_CO_5F = { group = 1, name = "SilphCo_5F", num = 51 },
    MAP_SILPH_CO_6F = { group = 1, name = "SilphCo_6F", num = 52 },
    MAP_SILPH_CO_7F = { group = 1, name = "SilphCo_7F", num = 53 },
    MAP_SILPH_CO_8F = { group = 1, name = "SilphCo_8F", num = 54 },
    MAP_SILPH_CO_9F = { group = 1, name = "SilphCo_9F", num = 55 },
    MAP_SILPH_CO_ELEVATOR = { group = 1, name = "SilphCo_Elevator", num = 58 },
    MAP_SIX_ISLAND = { group = 3, name = "SixIsland", num = 18 },
    MAP_SIX_ISLAND_ALTERING_CAVE = { group = 1, name = "SixIsland_AlteringCave", num = 122 },
    MAP_SIX_ISLAND_DOTTED_HOLE_1F = { group = 1, name = "SixIsland_DottedHole_1F", num = 115 },
    MAP_SIX_ISLAND_DOTTED_HOLE_B1F = { group = 1, name = "SixIsland_DottedHole_B1F", num = 116 },
    MAP_SIX_ISLAND_DOTTED_HOLE_B2F = { group = 1, name = "SixIsland_DottedHole_B2F", num = 117 },
    MAP_SIX_ISLAND_DOTTED_HOLE_B3F = { group = 1, name = "SixIsland_DottedHole_B3F", num = 118 },
    MAP_SIX_ISLAND_DOTTED_HOLE_B4F = { group = 1, name = "SixIsland_DottedHole_B4F", num = 119 },
    MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM = { group = 1, name = "SixIsland_DottedHole_SapphireRoom", num = 120 },
    MAP_SIX_ISLAND_GREEN_PATH = { group = 3, name = "SixIsland_GreenPath", num = 59 },
    MAP_SIX_ISLAND_HARBOR = { group = 37, name = "SixIsland_Harbor", num = 2 },
    MAP_SIX_ISLAND_HOUSE = { group = 37, name = "SixIsland_House", num = 3 },
    MAP_SIX_ISLAND_MART = { group = 37, name = "SixIsland_Mart", num = 4 },
    MAP_SIX_ISLAND_OUTCAST_ISLAND = { group = 3, name = "SixIsland_OutcastIsland", num = 58 },
    MAP_SIX_ISLAND_PATTERN_BUSH = { group = 1, name = "SixIsland_PatternBush", num = 121 },
    MAP_SIX_ISLAND_POKEMON_CENTER_1F = { group = 37, name = "SixIsland_PokemonCenter_1F", num = 0 },
    MAP_SIX_ISLAND_POKEMON_CENTER_2F = { group = 37, name = "SixIsland_PokemonCenter_2F", num = 1 },
    MAP_SIX_ISLAND_RUIN_VALLEY = { group = 3, name = "SixIsland_RuinValley", num = 61 },
    MAP_SIX_ISLAND_WATER_PATH = { group = 3, name = "SixIsland_WaterPath", num = 60 },
    MAP_SIX_ISLAND_WATER_PATH_HOUSE1 = { group = 41, name = "SixIsland_WaterPath_House1", num = 0 },
    MAP_SIX_ISLAND_WATER_PATH_HOUSE2 = { group = 41, name = "SixIsland_WaterPath_House2", num = 1 },
    MAP_SSANNE_1F_CORRIDOR = { group = 1, name = "SSAnne_1F_Corridor", num = 5 },
    MAP_SSANNE_1F_ROOM1 = { group = 1, name = "SSAnne_1F_Room1", num = 12 },
    MAP_SSANNE_1F_ROOM2 = { group = 1, name = "SSAnne_1F_Room2", num = 13 },
    MAP_SSANNE_1F_ROOM3 = { group = 1, name = "SSAnne_1F_Room3", num = 14 },
    MAP_SSANNE_1F_ROOM4 = { group = 1, name = "SSAnne_1F_Room4", num = 15 },
    MAP_SSANNE_1F_ROOM5 = { group = 1, name = "SSAnne_1F_Room5", num = 16 },
    MAP_SSANNE_1F_ROOM6 = { group = 1, name = "SSAnne_1F_Room6", num = 29 },
    MAP_SSANNE_1F_ROOM7 = { group = 1, name = "SSAnne_1F_Room7", num = 17 },
    MAP_SSANNE_2F_CORRIDOR = { group = 1, name = "SSAnne_2F_Corridor", num = 6 },
    MAP_SSANNE_2F_ROOM1 = { group = 1, name = "SSAnne_2F_Room1", num = 18 },
    MAP_SSANNE_2F_ROOM2 = { group = 1, name = "SSAnne_2F_Room2", num = 19 },
    MAP_SSANNE_2F_ROOM3 = { group = 1, name = "SSAnne_2F_Room3", num = 20 },
    MAP_SSANNE_2F_ROOM4 = { group = 1, name = "SSAnne_2F_Room4", num = 21 },
    MAP_SSANNE_2F_ROOM5 = { group = 1, name = "SSAnne_2F_Room5", num = 22 },
    MAP_SSANNE_2F_ROOM6 = { group = 1, name = "SSAnne_2F_Room6", num = 23 },
    MAP_SSANNE_3F_CORRIDOR = { group = 1, name = "SSAnne_3F_Corridor", num = 7 },
    MAP_SSANNE_B1F_CORRIDOR = { group = 1, name = "SSAnne_B1F_Corridor", num = 8 },
    MAP_SSANNE_B1F_ROOM1 = { group = 1, name = "SSAnne_B1F_Room1", num = 24 },
    MAP_SSANNE_B1F_ROOM2 = { group = 1, name = "SSAnne_B1F_Room2", num = 25 },
    MAP_SSANNE_B1F_ROOM3 = { group = 1, name = "SSAnne_B1F_Room3", num = 26 },
    MAP_SSANNE_B1F_ROOM4 = { group = 1, name = "SSAnne_B1F_Room4", num = 27 },
    MAP_SSANNE_B1F_ROOM5 = { group = 1, name = "SSAnne_B1F_Room5", num = 28 },
    MAP_SSANNE_CAPTAINS_OFFICE = { group = 1, name = "SSAnne_CaptainsOffice", num = 11 },
    MAP_SSANNE_DECK = { group = 1, name = "SSAnne_Deck", num = 9 },
    MAP_SSANNE_EXTERIOR = { group = 1, name = "SSAnne_Exterior", num = 4 },
    MAP_SSANNE_KITCHEN = { group = 1, name = "SSAnne_Kitchen", num = 10 },
    MAP_THREE_ISLAND = { group = 3, name = "ThreeIsland", num = 14 },
    MAP_THREE_ISLAND_BERRY_FOREST = { group = 1, name = "ThreeIsland_BerryForest", num = 109 },
    MAP_THREE_ISLAND_BOND_BRIDGE = { group = 3, name = "ThreeIsland_BondBridge", num = 48 },
    MAP_THREE_ISLAND_DUNSPARCE_TUNNEL = { group = 2, name = "ThreeIsland_DunsparceTunnel", num = 34 },
    MAP_THREE_ISLAND_HARBOR = { group = 38, name = "ThreeIsland_Harbor", num = 0 },
    MAP_THREE_ISLAND_HOUSE1 = { group = 34, name = "ThreeIsland_House1", num = 0 },
    MAP_THREE_ISLAND_HOUSE2 = { group = 34, name = "ThreeIsland_House2", num = 4 },
    MAP_THREE_ISLAND_HOUSE3 = { group = 34, name = "ThreeIsland_House3", num = 5 },
    MAP_THREE_ISLAND_HOUSE4 = { group = 34, name = "ThreeIsland_House4", num = 6 },
    MAP_THREE_ISLAND_HOUSE5 = { group = 34, name = "ThreeIsland_House5", num = 7 },
    MAP_THREE_ISLAND_MART = { group = 34, name = "ThreeIsland_Mart", num = 3 },
    MAP_THREE_ISLAND_POKEMON_CENTER_1F = { group = 34, name = "ThreeIsland_PokemonCenter_1F", num = 1 },
    MAP_THREE_ISLAND_POKEMON_CENTER_2F = { group = 34, name = "ThreeIsland_PokemonCenter_2F", num = 2 },
    MAP_THREE_ISLAND_PORT = { group = 3, name = "ThreeIsland_Port", num = 49 },
    MAP_TRADE_CENTER = { group = 0, name = "TradeCenter", num = 1 },
    MAP_TRAINER_TOWER_1F = { group = 2, name = "TrainerTower_1F", num = 1 },
    MAP_TRAINER_TOWER_2F = { group = 2, name = "TrainerTower_2F", num = 2 },
    MAP_TRAINER_TOWER_3F = { group = 2, name = "TrainerTower_3F", num = 3 },
    MAP_TRAINER_TOWER_4F = { group = 2, name = "TrainerTower_4F", num = 4 },
    MAP_TRAINER_TOWER_5F = { group = 2, name = "TrainerTower_5F", num = 5 },
    MAP_TRAINER_TOWER_6F = { group = 2, name = "TrainerTower_6F", num = 6 },
    MAP_TRAINER_TOWER_7F = { group = 2, name = "TrainerTower_7F", num = 7 },
    MAP_TRAINER_TOWER_8F = { group = 2, name = "TrainerTower_8F", num = 8 },
    MAP_TRAINER_TOWER_ELEVATOR = { group = 2, name = "TrainerTower_Elevator", num = 11 },
    MAP_TRAINER_TOWER_LOBBY = { group = 2, name = "TrainerTower_Lobby", num = 10 },
    MAP_TRAINER_TOWER_ROOF = { group = 2, name = "TrainerTower_Roof", num = 9 },
    MAP_TWO_ISLAND = { group = 3, name = "TwoIsland", num = 13 },
    MAP_TWO_ISLAND_CAPE_BRINK = { group = 3, name = "TwoIsland_CapeBrink", num = 47 },
    MAP_TWO_ISLAND_CAPE_BRINK_HOUSE = { group = 40, name = "TwoIsland_CapeBrink_House", num = 0 },
    MAP_TWO_ISLAND_HARBOR = { group = 33, name = "TwoIsland_Harbor", num = 4 },
    MAP_TWO_ISLAND_HOUSE = { group = 33, name = "TwoIsland_House", num = 1 },
    MAP_TWO_ISLAND_JOYFUL_GAME_CORNER = { group = 33, name = "TwoIsland_JoyfulGameCorner", num = 0 },
    MAP_TWO_ISLAND_POKEMON_CENTER_1F = { group = 33, name = "TwoIsland_PokemonCenter_1F", num = 2 },
    MAP_TWO_ISLAND_POKEMON_CENTER_2F = { group = 33, name = "TwoIsland_PokemonCenter_2F", num = 3 },
    MAP_UNDERGROUND_PATH_EAST_ENTRANCE = { group = 1, name = "UndergroundPath_EastEntrance", num = 35 },
    MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL = { group = 1, name = "UndergroundPath_EastWestTunnel", num = 34 },
    MAP_UNDERGROUND_PATH_NORTH_ENTRANCE = { group = 1, name = "UndergroundPath_NorthEntrance", num = 30 },
    MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL = { group = 1, name = "UndergroundPath_NorthSouthTunnel", num = 31 },
    MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE = { group = 1, name = "UndergroundPath_SouthEntrance", num = 32 },
    MAP_UNDERGROUND_PATH_WEST_ENTRANCE = { group = 1, name = "UndergroundPath_WestEntrance", num = 33 },
    MAP_UNION_ROOM = { group = 0, name = "UnionRoom", num = 4 },
    MAP_VERMILION_CITY = { group = 3, name = "VermilionCity", num = 5 },
    MAP_VERMILION_CITY_GYM = { group = 9, name = "VermilionCity_Gym", num = 6 },
    MAP_VERMILION_CITY_HOUSE1 = { group = 9, name = "VermilionCity_House1", num = 0 },
    MAP_VERMILION_CITY_HOUSE2 = { group = 9, name = "VermilionCity_House2", num = 4 },
    MAP_VERMILION_CITY_HOUSE3 = { group = 9, name = "VermilionCity_House3", num = 7 },
    MAP_VERMILION_CITY_MART = { group = 9, name = "VermilionCity_Mart", num = 5 },
    MAP_VERMILION_CITY_POKEMON_CENTER_1F = { group = 9, name = "VermilionCity_PokemonCenter_1F", num = 1 },
    MAP_VERMILION_CITY_POKEMON_CENTER_2F = { group = 9, name = "VermilionCity_PokemonCenter_2F", num = 2 },
    MAP_VERMILION_CITY_POKEMON_FAN_CLUB = { group = 9, name = "VermilionCity_PokemonFanClub", num = 3 },
    MAP_VICTORY_ROAD_1F = { group = 1, name = "VictoryRoad_1F", num = 39 },
    MAP_VICTORY_ROAD_2F = { group = 1, name = "VictoryRoad_2F", num = 40 },
    MAP_VICTORY_ROAD_3F = { group = 1, name = "VictoryRoad_3F", num = 41 },
    MAP_VIRIDIAN_CITY = { group = 3, name = "ViridianCity", num = 1 },
    MAP_VIRIDIAN_CITY_GYM = { group = 5, name = "ViridianCity_Gym", num = 1 },
    MAP_VIRIDIAN_CITY_HOUSE = { group = 5, name = "ViridianCity_House", num = 0 },
    MAP_VIRIDIAN_CITY_MART = { group = 5, name = "ViridianCity_Mart", num = 3 },
    MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F = { group = 5, name = "ViridianCity_PokemonCenter_1F", num = 4 },
    MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F = { group = 5, name = "ViridianCity_PokemonCenter_2F", num = 5 },
    MAP_VIRIDIAN_CITY_SCHOOL = { group = 5, name = "ViridianCity_School", num = 2 },
    MAP_VIRIDIAN_FOREST = { group = 1, name = "ViridianForest", num = 0 },
  },
  groups = {
    { count = 5, name = "gMapGroup_Link" },
    { count = 123, name = "gMapGroup_Dungeons" },
    { count = 60, name = "gMapGroup_SpecialArea" },
    { count = 66, name = "gMapGroup_TownsAndRoutes" },
    { count = 4, name = "gMapGroup_IndoorPallet" },
    { count = 6, name = "gMapGroup_IndoorViridian" },
    { count = 8, name = "gMapGroup_IndoorPewter" },
    { count = 10, name = "gMapGroup_IndoorCerulean" },
    { count = 6, name = "gMapGroup_IndoorLavender" },
    { count = 8, name = "gMapGroup_IndoorVermilion" },
    { count = 20, name = "gMapGroup_IndoorCeladon" },
    { count = 10, name = "gMapGroup_IndoorFuchsia" },
    { count = 8, name = "gMapGroup_IndoorCinnabar" },
    { count = 2, name = "gMapGroup_IndoorIndigoPlateau" },
    { count = 10, name = "gMapGroup_IndoorSaffron" },
    { count = 4, name = "gMapGroup_IndoorRoute2" },
    { count = 2, name = "gMapGroup_IndoorRoute4" },
    { count = 2, name = "gMapGroup_IndoorRoute5" },
    { count = 2, name = "gMapGroup_IndoorRoute6" },
    { count = 1, name = "gMapGroup_IndoorRoute7" },
    { count = 1, name = "gMapGroup_IndoorRoute8" },
    { count = 2, name = "gMapGroup_IndoorRoute10" },
    { count = 2, name = "gMapGroup_IndoorRoute11" },
    { count = 3, name = "gMapGroup_IndoorRoute12" },
    { count = 2, name = "gMapGroup_IndoorRoute15" },
    { count = 3, name = "gMapGroup_IndoorRoute16" },
    { count = 2, name = "gMapGroup_IndoorRoute18" },
    { count = 1, name = "gMapGroup_IndoorRoute19" },
    { count = 1, name = "gMapGroup_IndoorRoute22" },
    { count = 1, name = "gMapGroup_IndoorRoute23" },
    { count = 1, name = "gMapGroup_IndoorRoute25" },
    { count = 7, name = "gMapGroup_IndoorSevenIsland" },
    { count = 5, name = "gMapGroup_IndoorOneIsland" },
    { count = 5, name = "gMapGroup_IndoorTwoIsland" },
    { count = 8, name = "gMapGroup_IndoorThreeIsland" },
    { count = 8, name = "gMapGroup_IndoorFourIsland" },
    { count = 5, name = "gMapGroup_IndoorFiveIsland" },
    { count = 5, name = "gMapGroup_IndoorSixIsland" },
    { count = 1, name = "gMapGroup_IndoorThreeIslandRoute" },
    { count = 1, name = "gMapGroup_IndoorFiveIslandRoute" },
    { count = 1, name = "gMapGroup_IndoorTwoIslandRoute" },
    { count = 2, name = "gMapGroup_IndoorSixIslandRoute" },
    { count = 1, name = "gMapGroup_IndoorSevenIslandRoute" },
  },
}
