-- Auto-generated from pret data/maps/map_groups.json (FireRed). Do not edit by hand.
return {
  group_order = {
    "gMapGroup_Link",
    "gMapGroup_Dungeons",
    "gMapGroup_SpecialArea",
    "gMapGroup_TownsAndRoutes",
    "gMapGroup_IndoorPallet",
    "gMapGroup_IndoorViridian",
    "gMapGroup_IndoorPewter",
    "gMapGroup_IndoorCerulean",
    "gMapGroup_IndoorLavender",
    "gMapGroup_IndoorVermilion",
    "gMapGroup_IndoorCeladon",
    "gMapGroup_IndoorFuchsia",
    "gMapGroup_IndoorCinnabar",
    "gMapGroup_IndoorIndigoPlateau",
    "gMapGroup_IndoorSaffron",
    "gMapGroup_IndoorRoute2",
    "gMapGroup_IndoorRoute4",
    "gMapGroup_IndoorRoute5",
    "gMapGroup_IndoorRoute6",
    "gMapGroup_IndoorRoute7",
    "gMapGroup_IndoorRoute8",
    "gMapGroup_IndoorRoute10",
    "gMapGroup_IndoorRoute11",
    "gMapGroup_IndoorRoute12",
    "gMapGroup_IndoorRoute15",
    "gMapGroup_IndoorRoute16",
    "gMapGroup_IndoorRoute18",
    "gMapGroup_IndoorRoute19",
    "gMapGroup_IndoorRoute22",
    "gMapGroup_IndoorRoute23",
    "gMapGroup_IndoorRoute25",
    "gMapGroup_IndoorSevenIsland",
    "gMapGroup_IndoorOneIsland",
    "gMapGroup_IndoorTwoIsland",
    "gMapGroup_IndoorThreeIsland",
    "gMapGroup_IndoorFourIsland",
    "gMapGroup_IndoorFiveIsland",
    "gMapGroup_IndoorSixIsland",
    "gMapGroup_IndoorThreeIslandRoute",
    "gMapGroup_IndoorFiveIslandRoute",
    "gMapGroup_IndoorTwoIslandRoute",
    "gMapGroup_IndoorSixIslandRoute",
    "gMapGroup_IndoorSevenIslandRoute",
  },
  groups = {
    [0] = {
      name = "gMapGroup_Link",
      maps = {
        "BattleColosseum_2P",
        "TradeCenter",
        "RecordCorner",
        "BattleColosseum_4P",
        "UnionRoom",
      },
    },
    [1] = {
      name = "gMapGroup_Dungeons",
      maps = {
        "ViridianForest",
        "MtMoon_1F",
        "MtMoon_B1F",
        "MtMoon_B2F",
        "SSAnne_Exterior",
        "SSAnne_1F_Corridor",
        "SSAnne_2F_Corridor",
        "SSAnne_3F_Corridor",
        "SSAnne_B1F_Corridor",
        "SSAnne_Deck",
        "SSAnne_Kitchen",
        "SSAnne_CaptainsOffice",
        "SSAnne_1F_Room1",
        "SSAnne_1F_Room2",
        "SSAnne_1F_Room3",
        "SSAnne_1F_Room4",
        "SSAnne_1F_Room5",
        "SSAnne_1F_Room7",
        "SSAnne_2F_Room1",
        "SSAnne_2F_Room2",
        "SSAnne_2F_Room3",
        "SSAnne_2F_Room4",
        "SSAnne_2F_Room5",
        "SSAnne_2F_Room6",
        "SSAnne_B1F_Room1",
        "SSAnne_B1F_Room2",
        "SSAnne_B1F_Room3",
        "SSAnne_B1F_Room4",
        "SSAnne_B1F_Room5",
        "SSAnne_1F_Room6",
        "UndergroundPath_NorthEntrance",
        "UndergroundPath_NorthSouthTunnel",
        "UndergroundPath_SouthEntrance",
        "UndergroundPath_WestEntrance",
        "UndergroundPath_EastWestTunnel",
        "UndergroundPath_EastEntrance",
        "DiglettsCave_NorthEntrance",
        "DiglettsCave_B1F",
        "DiglettsCave_SouthEntrance",
        "VictoryRoad_1F",
        "VictoryRoad_2F",
        "VictoryRoad_3F",
        "RocketHideout_B1F",
        "RocketHideout_B2F",
        "RocketHideout_B3F",
        "RocketHideout_B4F",
        "RocketHideout_Elevator",
        "SilphCo_1F",
        "SilphCo_2F",
        "SilphCo_3F",
        "SilphCo_4F",
        "SilphCo_5F",
        "SilphCo_6F",
        "SilphCo_7F",
        "SilphCo_8F",
        "SilphCo_9F",
        "SilphCo_10F",
        "SilphCo_11F",
        "SilphCo_Elevator",
        "PokemonMansion_1F",
        "PokemonMansion_2F",
        "PokemonMansion_3F",
        "PokemonMansion_B1F",
        "SafariZone_Center",
        "SafariZone_East",
        "SafariZone_North",
        "SafariZone_West",
        "SafariZone_Center_RestHouse",
        "SafariZone_East_RestHouse",
        "SafariZone_North_RestHouse",
        "SafariZone_West_RestHouse",
        "SafariZone_SecretHouse",
        "CeruleanCave_1F",
        "CeruleanCave_2F",
        "CeruleanCave_B1F",
        "PokemonLeague_LoreleisRoom",
        "PokemonLeague_BrunosRoom",
        "PokemonLeague_AgathasRoom",
        "PokemonLeague_LancesRoom",
        "PokemonLeague_ChampionsRoom",
        "PokemonLeague_HallOfFame",
        "RockTunnel_1F",
        "RockTunnel_B1F",
        "SeafoamIslands_1F",
        "SeafoamIslands_B1F",
        "SeafoamIslands_B2F",
        "SeafoamIslands_B3F",
        "SeafoamIslands_B4F",
        "PokemonTower_1F",
        "PokemonTower_2F",
        "PokemonTower_3F",
        "PokemonTower_4F",
        "PokemonTower_5F",
        "PokemonTower_6F",
        "PokemonTower_7F",
        "PowerPlant",
        "MtEmber_RubyPath_B4F",
        "MtEmber_Exterior",
        "MtEmber_SummitPath_1F",
        "MtEmber_SummitPath_2F",
        "MtEmber_SummitPath_3F",
        "MtEmber_Summit",
        "MtEmber_RubyPath_B5F",
        "MtEmber_RubyPath_1F",
        "MtEmber_RubyPath_B1F",
        "MtEmber_RubyPath_B2F",
        "MtEmber_RubyPath_B3F",
        "MtEmber_RubyPath_B1F_Stairs",
        "MtEmber_RubyPath_B2F_Stairs",
        "ThreeIsland_BerryForest",
        "FourIsland_IcefallCave_Entrance",
        "FourIsland_IcefallCave_1F",
        "FourIsland_IcefallCave_B1F",
        "FourIsland_IcefallCave_Back",
        "FiveIsland_RocketWarehouse",
        "SixIsland_DottedHole_1F",
        "SixIsland_DottedHole_B1F",
        "SixIsland_DottedHole_B2F",
        "SixIsland_DottedHole_B3F",
        "SixIsland_DottedHole_B4F",
        "SixIsland_DottedHole_SapphireRoom",
        "SixIsland_PatternBush",
        "SixIsland_AlteringCave",
      },
    },
    [2] = {
      name = "gMapGroup_SpecialArea",
      maps = {
        "NavelRock_Exterior",
        "TrainerTower_1F",
        "TrainerTower_2F",
        "TrainerTower_3F",
        "TrainerTower_4F",
        "TrainerTower_5F",
        "TrainerTower_6F",
        "TrainerTower_7F",
        "TrainerTower_8F",
        "TrainerTower_Roof",
        "TrainerTower_Lobby",
        "TrainerTower_Elevator",
        "FiveIsland_LostCave_Entrance",
        "FiveIsland_LostCave_Room1",
        "FiveIsland_LostCave_Room2",
        "FiveIsland_LostCave_Room3",
        "FiveIsland_LostCave_Room4",
        "FiveIsland_LostCave_Room5",
        "FiveIsland_LostCave_Room6",
        "FiveIsland_LostCave_Room7",
        "FiveIsland_LostCave_Room8",
        "FiveIsland_LostCave_Room9",
        "FiveIsland_LostCave_Room10",
        "FiveIsland_LostCave_Room11",
        "FiveIsland_LostCave_Room12",
        "FiveIsland_LostCave_Room13",
        "FiveIsland_LostCave_Room14",
        "SevenIsland_TanobyRuins_MoneanChamber",
        "SevenIsland_TanobyRuins_LiptooChamber",
        "SevenIsland_TanobyRuins_WeepthChamber",
        "SevenIsland_TanobyRuins_DilfordChamber",
        "SevenIsland_TanobyRuins_ScufibChamber",
        "SevenIsland_TanobyRuins_RixyChamber",
        "SevenIsland_TanobyRuins_ViapoisChamber",
        "ThreeIsland_DunsparceTunnel",
        "SevenIsland_SevaultCanyon_TanobyKey",
        "NavelRock_1F",
        "NavelRock_Summit",
        "NavelRock_Base",
        "NavelRock_SummitPath_2F",
        "NavelRock_SummitPath_3F",
        "NavelRock_SummitPath_4F",
        "NavelRock_SummitPath_5F",
        "NavelRock_BasePath_B1F",
        "NavelRock_BasePath_B2F",
        "NavelRock_BasePath_B3F",
        "NavelRock_BasePath_B4F",
        "NavelRock_BasePath_B5F",
        "NavelRock_BasePath_B6F",
        "NavelRock_BasePath_B7F",
        "NavelRock_BasePath_B8F",
        "NavelRock_BasePath_B9F",
        "NavelRock_BasePath_B10F",
        "NavelRock_BasePath_B11F",
        "NavelRock_B1F",
        "NavelRock_Fork",
        "BirthIsland_Exterior",
        "OneIsland_KindleRoad_EmberSpa",
        "BirthIsland_Harbor",
        "NavelRock_Harbor",
      },
    },
    [3] = {
      name = "gMapGroup_TownsAndRoutes",
      maps = {
        "PalletTown",
        "ViridianCity",
        "PewterCity",
        "CeruleanCity",
        "LavenderTown",
        "VermilionCity",
        "CeladonCity",
        "FuchsiaCity",
        "CinnabarIsland",
        "IndigoPlateau_Exterior",
        "SaffronCity",
        "SaffronCity_Connection",
        "OneIsland",
        "TwoIsland",
        "ThreeIsland",
        "FourIsland",
        "FiveIsland",
        "SevenIsland",
        "SixIsland",
        "Route1",
        "Route2",
        "Route3",
        "Route4",
        "Route5",
        "Route6",
        "Route7",
        "Route8",
        "Route9",
        "Route10",
        "Route11",
        "Route12",
        "Route13",
        "Route14",
        "Route15",
        "Route16",
        "Route17",
        "Route18",
        "Route19",
        "Route20",
        "Route21_North",
        "Route21_South",
        "Route22",
        "Route23",
        "Route24",
        "Route25",
        "OneIsland_KindleRoad",
        "OneIsland_TreasureBeach",
        "TwoIsland_CapeBrink",
        "ThreeIsland_BondBridge",
        "ThreeIsland_Port",
        "Prototype_SeviiIsle_6",
        "Prototype_SeviiIsle_7",
        "Prototype_SeviiIsle_8",
        "Prototype_SeviiIsle_9",
        "FiveIsland_ResortGorgeous",
        "FiveIsland_WaterLabyrinth",
        "FiveIsland_Meadow",
        "FiveIsland_MemorialPillar",
        "SixIsland_OutcastIsland",
        "SixIsland_GreenPath",
        "SixIsland_WaterPath",
        "SixIsland_RuinValley",
        "SevenIsland_TrainerTower",
        "SevenIsland_SevaultCanyon_Entrance",
        "SevenIsland_SevaultCanyon",
        "SevenIsland_TanobyRuins",
      },
    },
    [4] = {
      name = "gMapGroup_IndoorPallet",
      maps = {
        "PalletTown_PlayersHouse_1F",
        "PalletTown_PlayersHouse_2F",
        "PalletTown_RivalsHouse",
        "PalletTown_ProfessorOaksLab",
      },
    },
    [5] = {
      name = "gMapGroup_IndoorViridian",
      maps = {
        "ViridianCity_House",
        "ViridianCity_Gym",
        "ViridianCity_School",
        "ViridianCity_Mart",
        "ViridianCity_PokemonCenter_1F",
        "ViridianCity_PokemonCenter_2F",
      },
    },
    [6] = {
      name = "gMapGroup_IndoorPewter",
      maps = {
        "PewterCity_Museum_1F",
        "PewterCity_Museum_2F",
        "PewterCity_Gym",
        "PewterCity_Mart",
        "PewterCity_House1",
        "PewterCity_PokemonCenter_1F",
        "PewterCity_PokemonCenter_2F",
        "PewterCity_House2",
      },
    },
    [7] = {
      name = "gMapGroup_IndoorCerulean",
      maps = {
        "CeruleanCity_House1",
        "CeruleanCity_House2",
        "CeruleanCity_House3",
        "CeruleanCity_PokemonCenter_1F",
        "CeruleanCity_PokemonCenter_2F",
        "CeruleanCity_Gym",
        "CeruleanCity_BikeShop",
        "CeruleanCity_Mart",
        "CeruleanCity_House4",
        "CeruleanCity_House5",
      },
    },
    [8] = {
      name = "gMapGroup_IndoorLavender",
      maps = {
        "LavenderTown_PokemonCenter_1F",
        "LavenderTown_PokemonCenter_2F",
        "LavenderTown_VolunteerPokemonHouse",
        "LavenderTown_House1",
        "LavenderTown_House2",
        "LavenderTown_Mart",
      },
    },
    [9] = {
      name = "gMapGroup_IndoorVermilion",
      maps = {
        "VermilionCity_House1",
        "VermilionCity_PokemonCenter_1F",
        "VermilionCity_PokemonCenter_2F",
        "VermilionCity_PokemonFanClub",
        "VermilionCity_House2",
        "VermilionCity_Mart",
        "VermilionCity_Gym",
        "VermilionCity_House3",
      },
    },
    [10] = {
      name = "gMapGroup_IndoorCeladon",
      maps = {
        "CeladonCity_DepartmentStore_1F",
        "CeladonCity_DepartmentStore_2F",
        "CeladonCity_DepartmentStore_3F",
        "CeladonCity_DepartmentStore_4F",
        "CeladonCity_DepartmentStore_5F",
        "CeladonCity_DepartmentStore_Roof",
        "CeladonCity_DepartmentStore_Elevator",
        "CeladonCity_Condominiums_1F",
        "CeladonCity_Condominiums_2F",
        "CeladonCity_Condominiums_3F",
        "CeladonCity_Condominiums_Roof",
        "CeladonCity_Condominiums_RoofRoom",
        "CeladonCity_PokemonCenter_1F",
        "CeladonCity_PokemonCenter_2F",
        "CeladonCity_GameCorner",
        "CeladonCity_GameCorner_PrizeRoom",
        "CeladonCity_Gym",
        "CeladonCity_Restaurant",
        "CeladonCity_House1",
        "CeladonCity_Hotel",
      },
    },
    [11] = {
      name = "gMapGroup_IndoorFuchsia",
      maps = {
        "FuchsiaCity_SafariZone_Entrance",
        "FuchsiaCity_Mart",
        "FuchsiaCity_SafariZone_Office",
        "FuchsiaCity_Gym",
        "FuchsiaCity_House1",
        "FuchsiaCity_PokemonCenter_1F",
        "FuchsiaCity_PokemonCenter_2F",
        "FuchsiaCity_WardensHouse",
        "FuchsiaCity_House2",
        "FuchsiaCity_House3",
      },
    },
    [12] = {
      name = "gMapGroup_IndoorCinnabar",
      maps = {
        "CinnabarIsland_Gym",
        "CinnabarIsland_PokemonLab_Entrance",
        "CinnabarIsland_PokemonLab_Lounge",
        "CinnabarIsland_PokemonLab_ResearchRoom",
        "CinnabarIsland_PokemonLab_ExperimentRoom",
        "CinnabarIsland_PokemonCenter_1F",
        "CinnabarIsland_PokemonCenter_2F",
        "CinnabarIsland_Mart",
      },
    },
    [13] = {
      name = "gMapGroup_IndoorIndigoPlateau",
      maps = {
        "IndigoPlateau_PokemonCenter_1F",
        "IndigoPlateau_PokemonCenter_2F",
      },
    },
    [14] = {
      name = "gMapGroup_IndoorSaffron",
      maps = {
        "SaffronCity_CopycatsHouse_1F",
        "SaffronCity_CopycatsHouse_2F",
        "SaffronCity_Dojo",
        "SaffronCity_Gym",
        "SaffronCity_House",
        "SaffronCity_Mart",
        "SaffronCity_PokemonCenter_1F",
        "SaffronCity_PokemonCenter_2F",
        "SaffronCity_MrPsychicsHouse",
        "SaffronCity_PokemonTrainerFanClub",
      },
    },
    [15] = {
      name = "gMapGroup_IndoorRoute2",
      maps = {
        "Route2_ViridianForest_SouthEntrance",
        "Route2_House",
        "Route2_EastBuilding",
        "Route2_ViridianForest_NorthEntrance",
      },
    },
    [16] = {
      name = "gMapGroup_IndoorRoute4",
      maps = {
        "Route4_PokemonCenter_1F",
        "Route4_PokemonCenter_2F",
      },
    },
    [17] = {
      name = "gMapGroup_IndoorRoute5",
      maps = {
        "Route5_PokemonDayCare",
        "Route5_SouthEntrance",
      },
    },
    [18] = {
      name = "gMapGroup_IndoorRoute6",
      maps = {
        "Route6_NorthEntrance",
        "Route6_UnusedHouse",
      },
    },
    [19] = {
      name = "gMapGroup_IndoorRoute7",
      maps = {
        "Route7_EastEntrance",
      },
    },
    [20] = {
      name = "gMapGroup_IndoorRoute8",
      maps = {
        "Route8_WestEntrance",
      },
    },
    [21] = {
      name = "gMapGroup_IndoorRoute10",
      maps = {
        "Route10_PokemonCenter_1F",
        "Route10_PokemonCenter_2F",
      },
    },
    [22] = {
      name = "gMapGroup_IndoorRoute11",
      maps = {
        "Route11_EastEntrance_1F",
        "Route11_EastEntrance_2F",
      },
    },
    [23] = {
      name = "gMapGroup_IndoorRoute12",
      maps = {
        "Route12_NorthEntrance_1F",
        "Route12_NorthEntrance_2F",
        "Route12_FishingHouse",
      },
    },
    [24] = {
      name = "gMapGroup_IndoorRoute15",
      maps = {
        "Route15_WestEntrance_1F",
        "Route15_WestEntrance_2F",
      },
    },
    [25] = {
      name = "gMapGroup_IndoorRoute16",
      maps = {
        "Route16_House",
        "Route16_NorthEntrance_1F",
        "Route16_NorthEntrance_2F",
      },
    },
    [26] = {
      name = "gMapGroup_IndoorRoute18",
      maps = {
        "Route18_EastEntrance_1F",
        "Route18_EastEntrance_2F",
      },
    },
    [27] = {
      name = "gMapGroup_IndoorRoute19",
      maps = {
        "Route19_UnusedHouse",
      },
    },
    [28] = {
      name = "gMapGroup_IndoorRoute22",
      maps = {
        "Route22_NorthEntrance",
      },
    },
    [29] = {
      name = "gMapGroup_IndoorRoute23",
      maps = {
        "Route23_UnusedHouse",
      },
    },
    [30] = {
      name = "gMapGroup_IndoorRoute25",
      maps = {
        "Route25_SeaCottage",
      },
    },
    [31] = {
      name = "gMapGroup_IndoorSevenIsland",
      maps = {
        "SevenIsland_House_Room1",
        "SevenIsland_House_Room2",
        "SevenIsland_Mart",
        "SevenIsland_PokemonCenter_1F",
        "SevenIsland_PokemonCenter_2F",
        "SevenIsland_UnusedHouse",
        "SevenIsland_Harbor",
      },
    },
    [32] = {
      name = "gMapGroup_IndoorOneIsland",
      maps = {
        "OneIsland_PokemonCenter_1F",
        "OneIsland_PokemonCenter_2F",
        "OneIsland_House1",
        "OneIsland_House2",
        "OneIsland_Harbor",
      },
    },
    [33] = {
      name = "gMapGroup_IndoorTwoIsland",
      maps = {
        "TwoIsland_JoyfulGameCorner",
        "TwoIsland_House",
        "TwoIsland_PokemonCenter_1F",
        "TwoIsland_PokemonCenter_2F",
        "TwoIsland_Harbor",
      },
    },
    [34] = {
      name = "gMapGroup_IndoorThreeIsland",
      maps = {
        "ThreeIsland_House1",
        "ThreeIsland_PokemonCenter_1F",
        "ThreeIsland_PokemonCenter_2F",
        "ThreeIsland_Mart",
        "ThreeIsland_House2",
        "ThreeIsland_House3",
        "ThreeIsland_House4",
        "ThreeIsland_House5",
      },
    },
    [35] = {
      name = "gMapGroup_IndoorFourIsland",
      maps = {
        "FourIsland_PokemonDayCare",
        "FourIsland_PokemonCenter_1F",
        "FourIsland_PokemonCenter_2F",
        "FourIsland_House1",
        "FourIsland_LoreleisHouse",
        "FourIsland_Harbor",
        "FourIsland_House2",
        "FourIsland_Mart",
      },
    },
    [36] = {
      name = "gMapGroup_IndoorFiveIsland",
      maps = {
        "FiveIsland_PokemonCenter_1F",
        "FiveIsland_PokemonCenter_2F",
        "FiveIsland_Harbor",
        "FiveIsland_House1",
        "FiveIsland_House2",
      },
    },
    [37] = {
      name = "gMapGroup_IndoorSixIsland",
      maps = {
        "SixIsland_PokemonCenter_1F",
        "SixIsland_PokemonCenter_2F",
        "SixIsland_Harbor",
        "SixIsland_House",
        "SixIsland_Mart",
      },
    },
    [38] = {
      name = "gMapGroup_IndoorThreeIslandRoute",
      maps = {
        "ThreeIsland_Harbor",
      },
    },
    [39] = {
      name = "gMapGroup_IndoorFiveIslandRoute",
      maps = {
        "FiveIsland_ResortGorgeous_House",
      },
    },
    [40] = {
      name = "gMapGroup_IndoorTwoIslandRoute",
      maps = {
        "TwoIsland_CapeBrink_House",
      },
    },
    [41] = {
      name = "gMapGroup_IndoorSixIslandRoute",
      maps = {
        "SixIsland_WaterPath_House1",
        "SixIsland_WaterPath_House2",
      },
    },
    [42] = {
      name = "gMapGroup_IndoorSevenIslandRoute",
      maps = {
        "SevenIsland_SevaultCanyon_House",
      },
    },
  },
}
