-- tools/gen_gba_constants.py from pokeemerald/data/script_cmd_table.inc, pokeemerald/asm/macros/event.inc
return {
  byId = {
    [0] = {
      args = {},
      const = "SCR_OP_NOP",
      handler = "ScrCmd_nop",
      name = "nop",
      size = 1,
    },
    [1] = {
      args = {},
      const = "SCR_OP_NOP1",
      handler = "ScrCmd_nop1",
      name = "nop1",
      size = 1,
    },
    [2] = {
      args = {},
      const = "SCR_OP_END",
      handler = "ScrCmd_end",
      name = "end",
      size = 1,
    },
    [3] = {
      args = {},
      const = "SCR_OP_RETURN",
      handler = "ScrCmd_return",
      name = "return",
      size = 1,
    },
    [4] = {
      args = {
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_CALL",
      handler = "ScrCmd_call",
      name = "call",
      size = 5,
    },
    [5] = {
      args = {
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_GOTO",
      handler = "ScrCmd_goto",
      name = "goto",
      size = 5,
    },
    [6] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_GOTO_IF",
      handler = "ScrCmd_goto_if",
      name = "goto_if",
      size = 6,
    },
    [7] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_CALL_IF",
      handler = "ScrCmd_call_if",
      name = "call_if",
      size = 6,
    },
    [8] = {
      args = {
        { kind = "byte", name = "function" },
      },
      const = "SCR_OP_GOTO_STD",
      handler = "ScrCmd_gotostd",
      name = "gotostd",
      size = 2,
    },
    [9] = {
      args = {
        { kind = "byte", name = "function" },
      },
      const = "SCR_OP_CALL_STD",
      handler = "ScrCmd_callstd",
      name = "callstd",
      size = 2,
    },
    [10] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "byte", name = "function" },
      },
      const = "SCR_OP_GOTO_STD_IF",
      handler = "ScrCmd_gotostd_if",
      name = "gotostd_if",
      size = 3,
    },
    [11] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "byte", name = "function" },
      },
      const = "SCR_OP_CALL_STD_IF",
      handler = "ScrCmd_callstd_if",
      name = "callstd_if",
      size = 3,
    },
    [12] = {
      args = {},
      const = "SCR_OP_RETURNRAM",
      handler = "ScrCmd_returnram",
      name = "returnram",
      size = 1,
    },
    [13] = {
      args = {},
      const = "SCR_OP_ENDRAM",
      handler = "ScrCmd_endram",
      name = "endram",
      size = 1,
    },
    [14] = {
      args = {
        { kind = "byte", name = "value" },
      },
      const = "SCR_OP_SETMYSTERYEVENTSTATUS",
      handler = "ScrCmd_setmysteryeventstatus",
      name = "setmysteryeventstatus",
      size = 2,
    },
    [15] = {
      args = {
        { kind = "byte", name = "destIndex" },
        { kind = "word", name = "value" },
      },
      const = "SCR_OP_LOAD_WORD",
      handler = "ScrCmd_loadword",
      name = "loadword",
      size = 6,
    },
    [16] = {
      args = {
        { kind = "byte", name = "destIndex" },
        { kind = "byte", name = "value" },
      },
      const = "SCR_OP_LOAD_BYTE",
      handler = "ScrCmd_loadbyte",
      name = "loadbyte",
      size = 3,
    },
    [17] = {
      args = {
        { kind = "byte", name = "value" },
        { kind = "word", name = "ptr" },
      },
      const = "SCR_OP_SETPTR",
      handler = "ScrCmd_setptr",
      name = "setptr",
      size = 6,
    },
    [18] = {
      args = {
        { kind = "byte", name = "destIndex" },
        { kind = "word", name = "source" },
      },
      const = "SCR_OP_LOADBYTEFROMPTR",
      handler = "ScrCmd_loadbytefromptr",
      name = "loadbytefromptr",
      size = 6,
    },
    [19] = {
      args = {
        { kind = "byte", name = "srcIndex" },
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_SETPTRBYTE",
      handler = "ScrCmd_setptrbyte",
      name = "setptrbyte",
      size = 6,
    },
    [20] = {
      args = {
        { kind = "byte", name = "destIndex" },
        { kind = "byte", name = "srcIndex" },
      },
      const = "SCR_OP_COPYLOCAL",
      handler = "ScrCmd_copylocal",
      name = "copylocal",
      size = 3,
    },
    [21] = {
      args = {
        { kind = "word", name = "destination" },
        { kind = "word", name = "source" },
      },
      const = "SCR_OP_COPYBYTE",
      handler = "ScrCmd_copybyte",
      name = "copybyte",
      size = 9,
    },
    [22] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "value" },
      },
      const = "SCR_OP_SETVAR",
      handler = "ScrCmd_setvar",
      name = "setvar",
      size = 5,
    },
    [23] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "value" },
      },
      const = "SCR_OP_ADDVAR",
      handler = "ScrCmd_addvar",
      name = "addvar",
      size = 5,
    },
    [24] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "value" },
      },
      const = "SCR_OP_SUBVAR",
      handler = "ScrCmd_subvar",
      name = "subvar",
      size = 5,
    },
    [25] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "source" },
      },
      const = "SCR_OP_COPYVAR",
      handler = "ScrCmd_copyvar",
      name = "copyvar",
      size = 5,
    },
    [26] = {
      args = {
        { kind = "half", name = "destination" },
        { kind = "half", name = "source" },
      },
      const = "SCR_OP_SETORCOPYVAR",
      handler = "ScrCmd_setorcopyvar",
      name = "setorcopyvar",
      size = 5,
    },
    [27] = {
      args = {
        { kind = "byte", name = "local1" },
        { kind = "byte", name = "local2" },
      },
      const = "SCR_OP_COMPARE_LOCAL_TO_LOCAL",
      handler = "ScrCmd_compare_local_to_local",
      name = "compare_local_to_local",
      size = 3,
    },
    [28] = {
      args = {
        { kind = "byte", name = "local" },
        { kind = "byte", name = "value" },
      },
      const = "SCR_OP_COMPARE_LOCAL_TO_VALUE",
      handler = "ScrCmd_compare_local_to_value",
      name = "compare_local_to_value",
      size = 3,
    },
    [29] = {
      args = {
        { kind = "byte", name = "local" },
        { kind = "word", name = "ptr" },
      },
      const = "SCR_OP_COMPARE_LOCAL_TO_PTR",
      handler = "ScrCmd_compare_local_to_ptr",
      name = "compare_local_to_ptr",
      size = 6,
    },
    [30] = {
      args = {
        { kind = "word", name = "ptr" },
        { kind = "byte", name = "local" },
      },
      const = "SCR_OP_COMPARE_PTR_TO_LOCAL",
      handler = "ScrCmd_compare_ptr_to_local",
      name = "compare_ptr_to_local",
      size = 6,
    },
    [31] = {
      args = {
        { kind = "word", name = "ptr" },
        { kind = "byte", name = "value" },
      },
      const = "SCR_OP_COMPARE_PTR_TO_VALUE",
      handler = "ScrCmd_compare_ptr_to_value",
      name = "compare_ptr_to_value",
      size = 6,
    },
    [32] = {
      args = {
        { kind = "word", name = "ptr1" },
        { kind = "word", name = "ptr2" },
      },
      const = "SCR_OP_COMPARE_PTR_TO_PTR",
      handler = "ScrCmd_compare_ptr_to_ptr",
      name = "compare_ptr_to_ptr",
      size = 9,
    },
    [33] = {
      args = {
        { kind = "half", name = "var" },
        { kind = "half", name = "value" },
      },
      const = "SCR_OP_COMPARE_VAR_TO_VALUE",
      handler = "ScrCmd_compare_var_to_value",
      name = "compare_var_to_value",
      size = 5,
    },
    [34] = {
      args = {
        { kind = "half", name = "var1" },
        { kind = "half", name = "var2" },
      },
      const = "SCR_OP_COMPARE_VAR_TO_VAR",
      handler = "ScrCmd_compare_var_to_var",
      name = "compare_var_to_var",
      size = 5,
    },
    [35] = {
      args = {
        { kind = "word", name = "func" },
      },
      const = "SCR_OP_CALLNATIVE",
      handler = "ScrCmd_callnative",
      name = "callnative",
      size = 5,
    },
    [36] = {
      args = {
        { kind = "word", name = "func" },
      },
      const = "SCR_OP_GOTONATIVE",
      handler = "ScrCmd_gotonative",
      name = "gotonative",
      size = 5,
    },
    [37] = {
      args = {
        { kind = "half", name = "SPECIAL_\\function" },
      },
      const = "SCR_OP_SPECIAL",
      handler = "ScrCmd_special",
      name = "special",
      size = 3,
    },
    [38] = {
      args = {
        { kind = "half", name = "output" },
        { kind = "half", name = "SPECIAL_\\function" },
      },
      const = "SCR_OP_SPECIALVAR",
      handler = "ScrCmd_specialvar",
      name = "specialvar",
      size = 5,
    },
    [39] = {
      args = {},
      const = "SCR_OP_WAITSTATE",
      handler = "ScrCmd_waitstate",
      name = "waitstate",
      size = 1,
    },
    [40] = {
      args = {
        { kind = "half", name = "frames" },
      },
      const = "SCR_OP_DELAY",
      handler = "ScrCmd_delay",
      name = "delay",
      size = 3,
    },
    [41] = {
      args = {
        { kind = "half", name = "flag" },
      },
      const = "SCR_OP_SETFLAG",
      handler = "ScrCmd_setflag",
      name = "setflag",
      size = 3,
    },
    [42] = {
      args = {
        { kind = "half", name = "flag" },
      },
      const = "SCR_OP_CLEARFLAG",
      handler = "ScrCmd_clearflag",
      name = "clearflag",
      size = 3,
    },
    [43] = {
      args = {
        { kind = "half", name = "flag" },
      },
      const = "SCR_OP_CHECKFLAG",
      handler = "ScrCmd_checkflag",
      name = "checkflag",
      size = 3,
    },
    [44] = {
      args = {
        { kind = "half", name = "hour" },
        { kind = "half", name = "minute" },
      },
      const = "SCR_OP_INITCLOCK",
      handler = "ScrCmd_initclock",
      name = "initclock",
      size = 5,
    },
    [45] = {
      args = {},
      const = "SCR_OP_DOTIMEBASEDEVENTS",
      handler = "ScrCmd_dotimebasedevents",
      name = "dotimebasedevents",
      size = 1,
    },
    [46] = {
      args = {},
      const = "SCR_OP_GETTIME",
      handler = "ScrCmd_gettime",
      name = "gettime",
      size = 1,
    },
    [47] = {
      args = {
        { kind = "half", name = "song" },
      },
      const = "SCR_OP_PLAYSE",
      handler = "ScrCmd_playse",
      name = "playse",
      size = 3,
    },
    [48] = {
      args = {},
      const = "SCR_OP_WAITSE",
      handler = "ScrCmd_waitse",
      name = "waitse",
      size = 1,
    },
    [49] = {
      args = {
        { kind = "half", name = "song" },
      },
      const = "SCR_OP_PLAYFANFARE",
      handler = "ScrCmd_playfanfare",
      name = "playfanfare",
      size = 3,
    },
    [50] = {
      args = {},
      const = "SCR_OP_WAITFANFARE",
      handler = "ScrCmd_waitfanfare",
      name = "waitfanfare",
      size = 1,
    },
    [51] = {
      args = {
        { kind = "half", name = "song" },
        { kind = "byte", name = "save_song" },
      },
      const = "SCR_OP_PLAYBGM",
      handler = "ScrCmd_playbgm",
      name = "playbgm",
      size = 4,
    },
    [52] = {
      args = {
        { kind = "half", name = "song" },
      },
      const = "SCR_OP_SAVEBGM",
      handler = "ScrCmd_savebgm",
      name = "savebgm",
      size = 3,
    },
    [53] = {
      args = {},
      const = "SCR_OP_FADEDEFAULTBGM",
      handler = "ScrCmd_fadedefaultbgm",
      name = "fadedefaultbgm",
      size = 1,
    },
    [54] = {
      args = {
        { kind = "half", name = "song" },
      },
      const = "SCR_OP_FADENEWBGM",
      handler = "ScrCmd_fadenewbgm",
      name = "fadenewbgm",
      size = 3,
    },
    [55] = {
      args = {
        { kind = "byte", name = "speed" },
      },
      const = "SCR_OP_FADEOUTBGM",
      handler = "ScrCmd_fadeoutbgm",
      name = "fadeoutbgm",
      size = 2,
    },
    [56] = {
      args = {
        { kind = "byte", name = "speed" },
      },
      const = "SCR_OP_FADEINBGM",
      handler = "ScrCmd_fadeinbgm",
      name = "fadeinbgm",
      size = 2,
    },
    [57] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARP",
      handler = "ScrCmd_warp",
      name = "warp",
      size = 8,
    },
    [58] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARPSILENT",
      handler = "ScrCmd_warpsilent",
      name = "warpsilent",
      size = 8,
    },
    [59] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARPDOOR",
      handler = "ScrCmd_warpdoor",
      name = "warpdoor",
      size = 8,
    },
    [60] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_WARPHOLE",
      handler = "ScrCmd_warphole",
      name = "warphole",
      size = 3,
    },
    [61] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARPTELEPORT",
      handler = "ScrCmd_warpteleport",
      name = "warpteleport",
      size = 8,
    },
    [62] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_SETWARP",
      handler = "ScrCmd_setwarp",
      name = "setwarp",
      size = 8,
    },
    [63] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_SETDYNAMICWARP",
      handler = "ScrCmd_setdynamicwarp",
      name = "setdynamicwarp",
      size = 8,
    },
    [64] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_SETDIVEWARP",
      handler = "ScrCmd_setdivewarp",
      name = "setdivewarp",
      size = 8,
    },
    [65] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_SETHOLEWARP",
      handler = "ScrCmd_setholewarp",
      name = "setholewarp",
      size = 8,
    },
    [66] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_GETPLAYERXY",
      handler = "ScrCmd_getplayerxy",
      name = "getplayerxy",
      size = 5,
    },
    [67] = {
      args = {},
      const = "SCR_OP_GETPARTYSIZE",
      handler = "ScrCmd_getpartysize",
      name = "getpartysize",
      size = 1,
    },
    [68] = {
      args = {
        { kind = "half", name = "itemId" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_ADDITEM",
      handler = "ScrCmd_additem",
      name = "additem",
      size = 5,
    },
    [69] = {
      args = {
        { kind = "half", name = "itemId" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_REMOVEITEM",
      handler = "ScrCmd_removeitem",
      name = "removeitem",
      size = 5,
    },
    [70] = {
      args = {
        { kind = "half", name = "itemId" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_CHECKITEMSPACE",
      handler = "ScrCmd_checkitemspace",
      name = "checkitemspace",
      size = 5,
    },
    [71] = {
      args = {
        { kind = "half", name = "itemId" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_CHECKITEM",
      handler = "ScrCmd_checkitem",
      name = "checkitem",
      size = 5,
    },
    [72] = {
      args = {
        { kind = "half", name = "itemId" },
      },
      const = "SCR_OP_CHECKITEMTYPE",
      handler = "ScrCmd_checkitemtype",
      name = "checkitemtype",
      size = 3,
    },
    [73] = {
      args = {
        { kind = "half", name = "itemId" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_ADDPCITEM",
      handler = "ScrCmd_addpcitem",
      name = "addpcitem",
      size = 5,
    },
    [74] = {
      args = {
        { kind = "half", name = "itemId" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_CHECKPCITEM",
      handler = "ScrCmd_checkpcitem",
      name = "checkpcitem",
      size = 5,
    },
    [75] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      const = "SCR_OP_ADDDECORATION",
      handler = "ScrCmd_adddecoration",
      name = "adddecoration",
      size = 3,
    },
    [76] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      const = "SCR_OP_REMOVEDECORATION",
      handler = "ScrCmd_removedecoration",
      name = "removedecoration",
      size = 3,
    },
    [77] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      const = "SCR_OP_CHECKDECOR",
      handler = "ScrCmd_checkdecor",
      name = "checkdecor",
      size = 3,
    },
    [78] = {
      args = {
        { kind = "half", name = "decoration" },
      },
      const = "SCR_OP_CHECKDECORSPACE",
      handler = "ScrCmd_checkdecorspace",
      name = "checkdecorspace",
      size = 3,
    },
    [79] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "word", name = "movements" },
      },
      const = "SCR_OP_APPLYMOVEMENT",
      handler = "ScrCmd_applymovement",
      name = "applymovement",
      size = 7,
    },
    [80] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "word", name = "movements" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_APPLYMOVEMENTAT",
      handler = "ScrCmd_applymovementat",
      macro = "applymovement",
      name = "applymovementat",
      size = 9,
    },
    [81] = {
      args = {
        { kind = "half", name = "localId" },
      },
      const = "SCR_OP_WAITMOVEMENT",
      handler = "ScrCmd_waitmovement",
      name = "waitmovement",
      size = 3,
    },
    [82] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_WAITMOVEMENTAT",
      handler = "ScrCmd_waitmovementat",
      macro = "waitmovement",
      name = "waitmovementat",
      size = 5,
    },
    [83] = {
      args = {
        { kind = "half", name = "localId" },
      },
      const = "SCR_OP_REMOVEOBJECT",
      handler = "ScrCmd_removeobject",
      name = "removeobject",
      size = 3,
    },
    [84] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_REMOVEOBJECTAT",
      handler = "ScrCmd_removeobjectat",
      macro = "removeobject",
      name = "removeobjectat",
      size = 5,
    },
    [85] = {
      args = {
        { kind = "half", name = "localId" },
      },
      const = "SCR_OP_ADDOBJECT",
      handler = "ScrCmd_addobject",
      name = "addobject",
      size = 3,
    },
    [86] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_ADDOBJECTAT",
      handler = "ScrCmd_addobjectat",
      macro = "addobject",
      name = "addobjectat",
      size = 5,
    },
    [87] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_SETOBJECTXY",
      handler = "ScrCmd_setobjectxy",
      name = "setobjectxy",
      size = 7,
    },
    [88] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_SHOWOBJECTAT",
      handler = "ScrCmd_showobjectat",
      name = "showobjectat",
      size = 5,
    },
    [89] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_HIDEOBJECTAT",
      handler = "ScrCmd_hideobjectat",
      name = "hideobjectat",
      size = 5,
    },
    [90] = {
      args = {},
      const = "SCR_OP_FACEPLAYER",
      handler = "ScrCmd_faceplayer",
      name = "faceplayer",
      size = 1,
    },
    [91] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "direction" },
      },
      const = "SCR_OP_TURNOBJECT",
      handler = "ScrCmd_turnobject",
      name = "turnobject",
      size = 4,
    },
    [92] = {
      args = {
        { kind = "byte", name = "type" },
        { kind = "half", name = "trainer" },
        { kind = "half", name = "local_id" },
        { kind = "word", name = "pointer1" },
      },
      const = "SCR_OP_TRAINERBATTLE",
      handler = "ScrCmd_trainerbattle",
      name = "trainerbattle",
      prefix = 10,
      variable = true,
    },
    [93] = {
      args = {},
      const = "SCR_OP_DOTRAINERBATTLE",
      handler = "ScrCmd_dotrainerbattle",
      name = "dotrainerbattle",
      size = 1,
    },
    [94] = {
      args = {},
      const = "SCR_OP_GOTOPOSTBATTLESCRIPT",
      handler = "ScrCmd_gotopostbattlescript",
      name = "gotopostbattlescript",
      size = 1,
    },
    [95] = {
      args = {},
      const = "SCR_OP_GOTOBEATENSCRIPT",
      handler = "ScrCmd_gotobeatenscript",
      name = "gotobeatenscript",
      size = 1,
    },
    [96] = {
      args = {
        { kind = "half", name = "trainer" },
      },
      const = "SCR_OP_CHECKTRAINERFLAG",
      handler = "ScrCmd_checktrainerflag",
      name = "checktrainerflag",
      size = 3,
    },
    [97] = {
      args = {
        { kind = "half", name = "trainer" },
      },
      const = "SCR_OP_SETTRAINERFLAG",
      handler = "ScrCmd_settrainerflag",
      name = "settrainerflag",
      size = 3,
    },
    [98] = {
      args = {
        { kind = "half", name = "trainer" },
      },
      const = "SCR_OP_CLEARTRAINERFLAG",
      handler = "ScrCmd_cleartrainerflag",
      name = "cleartrainerflag",
      size = 3,
    },
    [99] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_SETOBJECTXYPERM",
      handler = "ScrCmd_setobjectxyperm",
      name = "setobjectxyperm",
      size = 7,
    },
    [100] = {
      args = {
        { kind = "half", name = "localId" },
      },
      const = "SCR_OP_COPYOBJECTXYTOPERM",
      handler = "ScrCmd_copyobjectxytoperm",
      name = "copyobjectxytoperm",
      size = 3,
    },
    [101] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "movementType" },
      },
      const = "SCR_OP_SETOBJECTMOVEMENTTYPE",
      handler = "ScrCmd_setobjectmovementtype",
      name = "setobjectmovementtype",
      size = 4,
    },
    [102] = {
      args = {},
      const = "SCR_OP_WAITMESSAGE",
      handler = "ScrCmd_waitmessage",
      name = "waitmessage",
      size = 1,
    },
    [103] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_MESSAGE",
      handler = "ScrCmd_message",
      name = "message",
      size = 5,
    },
    [104] = {
      args = {},
      const = "SCR_OP_CLOSEMESSAGE",
      handler = "ScrCmd_closemessage",
      name = "closemessage",
      size = 1,
    },
    [105] = {
      args = {},
      const = "SCR_OP_LOCKALL",
      handler = "ScrCmd_lockall",
      name = "lockall",
      size = 1,
    },
    [106] = {
      args = {},
      const = "SCR_OP_LOCK",
      handler = "ScrCmd_lock",
      name = "lock",
      size = 1,
    },
    [107] = {
      args = {},
      const = "SCR_OP_RELEASEALL",
      handler = "ScrCmd_releaseall",
      name = "releaseall",
      size = 1,
    },
    [108] = {
      args = {},
      const = "SCR_OP_RELEASE",
      handler = "ScrCmd_release",
      name = "release",
      size = 1,
    },
    [109] = {
      args = {},
      const = "SCR_OP_WAITBUTTONPRESS",
      handler = "ScrCmd_waitbuttonpress",
      name = "waitbuttonpress",
      size = 1,
    },
    [110] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      const = "SCR_OP_YESNOBOX",
      handler = "ScrCmd_yesnobox",
      name = "yesnobox",
      size = 3,
    },
    [111] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "multichoiceId" },
        { kind = "byte", name = "ignoreBPress" },
      },
      const = "SCR_OP_MULTICHOICE",
      handler = "ScrCmd_multichoice",
      name = "multichoice",
      size = 5,
    },
    [112] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "multichoiceId" },
        { kind = "byte", name = "default" },
        { kind = "byte", name = "ignoreBPress" },
      },
      const = "SCR_OP_MULTICHOICEDEFAULT",
      handler = "ScrCmd_multichoicedefault",
      name = "multichoicedefault",
      size = 6,
    },
    [113] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "multichoiceId" },
        { kind = "byte", name = "per_row" },
        { kind = "byte", name = "ignoreBPress" },
      },
      const = "SCR_OP_MULTICHOICEGRID",
      handler = "ScrCmd_multichoicegrid",
      name = "multichoicegrid",
      size = 6,
    },
    [114] = {
      args = {},
      const = "SCR_OP_DRAWBOX",
      handler = "ScrCmd_drawbox",
      name = "drawbox",
      size = 1,
    },
    [115] = {
      args = {
        { kind = "byte", name = "left" },
        { kind = "byte", name = "top" },
        { kind = "byte", name = "right" },
        { kind = "byte", name = "bottom" },
      },
      const = "SCR_OP_ERASEBOX",
      handler = "ScrCmd_erasebox",
      name = "erasebox",
      size = 5,
    },
    [116] = {
      args = {
        { kind = "byte", name = "left" },
        { kind = "byte", name = "top" },
        { kind = "byte", name = "multichoiceId" },
        { kind = "byte", name = "ignoreBPress" },
      },
      const = "SCR_OP_DRAWBOXTEXT",
      handler = "ScrCmd_drawboxtext",
      name = "drawboxtext",
      size = 5,
    },
    [117] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      const = "SCR_OP_SHOWMONPIC",
      handler = "ScrCmd_showmonpic",
      name = "showmonpic",
      size = 5,
    },
    [118] = {
      args = {},
      const = "SCR_OP_HIDEMONPIC",
      handler = "ScrCmd_hidemonpic",
      name = "hidemonpic",
      size = 1,
    },
    [119] = {
      args = {
        { kind = "byte", name = "winnerId" },
      },
      const = "SCR_OP_SHOWCONTESTPAINTING",
      handler = "ScrCmd_showcontestpainting",
      name = "showcontestpainting",
      size = 2,
    },
    [120] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_BRAILLEMESSAGE",
      handler = "ScrCmd_braillemessage",
      name = "braillemessage",
      size = 5,
    },
    [121] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "byte", name = "level" },
        { kind = "half", name = "item" },
        { kind = "word", name = "0" },
        { kind = "word", name = "0" },
        { kind = "byte", name = "0" },
      },
      const = "SCR_OP_GIVEMON",
      handler = "ScrCmd_givemon",
      name = "givemon",
      size = 15,
    },
    [122] = {
      args = {
        { kind = "half", name = "species" },
      },
      const = "SCR_OP_GIVEEGG",
      handler = "ScrCmd_giveegg",
      name = "giveegg",
      size = 3,
    },
    [123] = {
      args = {
        { kind = "byte", name = "partyIndex" },
        { kind = "byte", name = "slot" },
        { kind = "half", name = "move" },
      },
      const = "SCR_OP_SETMONMOVE",
      handler = "ScrCmd_setmonmove",
      name = "setmonmove",
      size = 5,
    },
    [124] = {
      args = {
        { kind = "half", name = "move" },
      },
      const = "SCR_OP_CHECKPARTYMOVE",
      handler = "ScrCmd_checkpartymove",
      name = "checkpartymove",
      size = 3,
    },
    [125] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "species" },
      },
      const = "SCR_OP_BUFFERSPECIESNAME",
      handler = "ScrCmd_bufferspeciesname",
      name = "bufferspeciesname",
      size = 4,
    },
    [126] = {
      args = {
        { kind = "byte", name = "id" },
      },
      const = "SCR_OP_BUFFERLEADMONSPECIESNAME",
      handler = "ScrCmd_bufferleadmonspeciesname",
      name = "bufferleadmonspeciesname",
      size = 2,
    },
    [127] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "slot" },
      },
      const = "SCR_OP_BUFFERPARTYMONNICK",
      handler = "ScrCmd_bufferpartymonnick",
      name = "bufferpartymonnick",
      size = 4,
    },
    [128] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "item" },
      },
      const = "SCR_OP_BUFFERITEMNAME",
      handler = "ScrCmd_bufferitemname",
      name = "bufferitemname",
      size = 4,
    },
    [129] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "decoration" },
      },
      const = "SCR_OP_BUFFERDECORATIONNAME",
      handler = "ScrCmd_bufferdecorationname",
      name = "bufferdecorationname",
      size = 4,
    },
    [130] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "move" },
      },
      const = "SCR_OP_BUFFERMOVENAME",
      handler = "ScrCmd_buffermovename",
      name = "buffermovename",
      size = 4,
    },
    [131] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "input" },
      },
      const = "SCR_OP_BUFFERNUMBERSTRING",
      handler = "ScrCmd_buffernumberstring",
      name = "buffernumberstring",
      size = 4,
    },
    [132] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "index" },
      },
      const = "SCR_OP_BUFFERSTDSTRING",
      handler = "ScrCmd_bufferstdstring",
      name = "bufferstdstring",
      size = 4,
    },
    [133] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_BUFFERSTRING",
      handler = "ScrCmd_bufferstring",
      name = "bufferstring",
      size = 6,
    },
    [134] = {
      args = {
        { kind = "word", name = "products" },
      },
      const = "SCR_OP_POKEMART",
      handler = "ScrCmd_pokemart",
      name = "pokemart",
      size = 5,
    },
    [135] = {
      args = {
        { kind = "word", name = "products" },
      },
      const = "SCR_OP_POKEMARTDECORATION",
      handler = "ScrCmd_pokemartdecoration",
      name = "pokemartdecoration",
      size = 5,
    },
    [136] = {
      args = {
        { kind = "word", name = "products" },
      },
      const = "SCR_OP_POKEMARTDECORATION2",
      handler = "ScrCmd_pokemartdecoration2",
      name = "pokemartdecoration2",
      size = 5,
    },
    [137] = {
      args = {
        { kind = "half", name = "id" },
      },
      const = "SCR_OP_PLAYSLOTMACHINE",
      handler = "ScrCmd_playslotmachine",
      name = "playslotmachine",
      size = 3,
    },
    [138] = {
      args = {
        { kind = "byte", name = "treeId" },
        { kind = "byte", name = "berry" },
        { kind = "byte", name = "growthStage" },
      },
      const = "SCR_OP_SETBERRYTREE",
      handler = "ScrCmd_setberrytree",
      name = "setberrytree",
      size = 4,
    },
    [139] = {
      args = {},
      const = "SCR_OP_CHOOSECONTESTMON",
      handler = "ScrCmd_choosecontestmon",
      name = "choosecontestmon",
      size = 1,
    },
    [140] = {
      args = {},
      const = "SCR_OP_STARTCONTEST",
      handler = "ScrCmd_startcontest",
      name = "startcontest",
      size = 1,
    },
    [141] = {
      args = {},
      const = "SCR_OP_SHOWCONTESTRESULTS",
      handler = "ScrCmd_showcontestresults",
      name = "showcontestresults",
      size = 1,
    },
    [142] = {
      args = {},
      const = "SCR_OP_CONTESTLINKTRANSFER",
      handler = "ScrCmd_contestlinktransfer",
      name = "contestlinktransfer",
      size = 1,
    },
    [143] = {
      args = {
        { kind = "half", name = "limit" },
      },
      const = "SCR_OP_RANDOM",
      handler = "ScrCmd_random",
      name = "random",
      size = 3,
    },
    [144] = {
      args = {
        { kind = "word", name = "value" },
        { kind = "byte", name = "disable" },
      },
      const = "SCR_OP_ADDMONEY",
      handler = "ScrCmd_addmoney",
      name = "addmoney",
      size = 6,
    },
    [145] = {
      args = {
        { kind = "word", name = "value" },
        { kind = "byte", name = "disable" },
      },
      const = "SCR_OP_REMOVEMONEY",
      handler = "ScrCmd_removemoney",
      name = "removemoney",
      size = 6,
    },
    [146] = {
      args = {
        { kind = "word", name = "value" },
        { kind = "byte", name = "disable" },
      },
      const = "SCR_OP_CHECKMONEY",
      handler = "ScrCmd_checkmoney",
      name = "checkmoney",
      size = 6,
    },
    [147] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
        { kind = "byte", name = "disable" },
      },
      const = "SCR_OP_SHOWMONEYBOX",
      handler = "ScrCmd_showmoneybox",
      name = "showmoneybox",
      size = 4,
    },
    [148] = {
      args = {
        { kind = "byte", name = "0" },
        { kind = "byte", name = "0" },
      },
      const = "SCR_OP_HIDEMONEYBOX",
      handler = "ScrCmd_hidemoneybox",
      name = "hidemoneybox",
      size = 3,
    },
    [149] = {
      args = {
        { kind = "byte", name = "0" },
        { kind = "byte", name = "0" },
        { kind = "byte", name = "disable" },
      },
      const = "SCR_OP_UPDATEMONEYBOX",
      handler = "ScrCmd_updatemoneybox",
      name = "updatemoneybox",
      size = 4,
    },
    [150] = {
      args = {
        { kind = "half", name = "newsKind" },
      },
      const = "SCR_OP_GETPOKENEWSACTIVE",
      handler = "ScrCmd_getpokenewsactive",
      name = "getpokenewsactive",
      size = 3,
    },
    [151] = {
      args = {
        { kind = "byte", name = "mode" },
      },
      const = "SCR_OP_FADESCREEN",
      handler = "ScrCmd_fadescreen",
      name = "fadescreen",
      size = 2,
    },
    [152] = {
      args = {
        { kind = "byte", name = "mode" },
        { kind = "byte", name = "speed" },
      },
      const = "SCR_OP_FADESCREENSPEED",
      handler = "ScrCmd_fadescreenspeed",
      name = "fadescreenspeed",
      size = 3,
    },
    [153] = {
      args = {
        { kind = "half", name = "level" },
      },
      const = "SCR_OP_SETFLASHLEVEL",
      handler = "ScrCmd_setflashlevel",
      name = "setflashlevel",
      size = 3,
    },
    [154] = {
      args = {
        { kind = "byte", name = "level" },
      },
      const = "SCR_OP_ANIMATEFLASH",
      handler = "ScrCmd_animateflash",
      name = "animateflash",
      size = 2,
    },
    [155] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_MESSAGEAUTOSCROLL",
      handler = "ScrCmd_messageautoscroll",
      name = "messageautoscroll",
      size = 5,
    },
    [156] = {
      args = {
        { kind = "half", name = "animation" },
      },
      const = "SCR_OP_DOFIELDEFFECT",
      handler = "ScrCmd_dofieldeffect",
      name = "dofieldeffect",
      size = 3,
    },
    [157] = {
      args = {
        { kind = "byte", name = "argNum" },
        { kind = "half", name = "value" },
      },
      const = "SCR_OP_SETFIELDEFFECTARGUMENT",
      handler = "ScrCmd_setfieldeffectargument",
      name = "setfieldeffectargument",
      size = 4,
    },
    [158] = {
      args = {
        { kind = "half", name = "animation" },
      },
      const = "SCR_OP_WAITFIELDEFFECT",
      handler = "ScrCmd_waitfieldeffect",
      name = "waitfieldeffect",
      size = 3,
    },
    [159] = {
      args = {
        { kind = "half", name = "heallocation" },
      },
      const = "SCR_OP_SETRESPAWN",
      handler = "ScrCmd_setrespawn",
      name = "setrespawn",
      size = 3,
    },
    [160] = {
      args = {},
      const = "SCR_OP_CHECKPLAYERGENDER",
      handler = "ScrCmd_checkplayergender",
      name = "checkplayergender",
      size = 1,
    },
    [161] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "half", name = "mode" },
      },
      const = "SCR_OP_PLAYMONCRY",
      handler = "ScrCmd_playmoncry",
      name = "playmoncry",
      size = 5,
    },
    [162] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
        { kind = "half", name = "metatileId" },
        { kind = "half", name = "impassable" },
      },
      const = "SCR_OP_SETMETATILE",
      handler = "ScrCmd_setmetatile",
      name = "setmetatile",
      size = 9,
    },
    [163] = {
      args = {},
      const = "SCR_OP_RESETWEATHER",
      handler = "ScrCmd_resetweather",
      name = "resetweather",
      size = 1,
    },
    [164] = {
      args = {
        { kind = "half", name = "type" },
      },
      const = "SCR_OP_SETWEATHER",
      handler = "ScrCmd_setweather",
      name = "setweather",
      size = 3,
    },
    [165] = {
      args = {},
      const = "SCR_OP_DOWEATHER",
      handler = "ScrCmd_doweather",
      name = "doweather",
      size = 1,
    },
    [166] = {
      args = {
        { kind = "byte", name = "stepCbId" },
      },
      const = "SCR_OP_SETSTEPCALLBACK",
      handler = "ScrCmd_setstepcallback",
      name = "setstepcallback",
      size = 2,
    },
    [167] = {
      args = {
        { kind = "half", name = "index" },
      },
      const = "SCR_OP_SETMAPLAYOUTINDEX",
      handler = "ScrCmd_setmaplayoutindex",
      name = "setmaplayoutindex",
      size = 3,
    },
    [168] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "subpriority" },
      },
      const = "SCR_OP_SETOBJECTSUBPRIORITY",
      handler = "ScrCmd_setobjectsubpriority",
      name = "setobjectsubpriority",
      size = 6,
    },
    [169] = {
      args = {
        { kind = "half", name = "localId" },
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
      },
      const = "SCR_OP_RESETOBJECTSUBPRIORITY",
      handler = "ScrCmd_resetobjectsubpriority",
      name = "resetobjectsubpriority",
      size = 5,
    },
    [170] = {
      args = {
        { kind = "byte", name = "graphicsId" },
        { kind = "byte", name = "id" },
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
        { kind = "byte", name = "elevation" },
        { kind = "byte", name = "direction" },
      },
      const = "SCR_OP_CREATEVOBJECT",
      handler = "ScrCmd_createvobject",
      name = "createvobject",
      size = 9,
    },
    [171] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "byte", name = "direction" },
      },
      const = "SCR_OP_TURNVOBJECT",
      handler = "ScrCmd_turnvobject",
      name = "turnvobject",
      size = 3,
    },
    [172] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_OPENDOOR",
      handler = "ScrCmd_opendoor",
      name = "opendoor",
      size = 5,
    },
    [173] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_CLOSEDOOR",
      handler = "ScrCmd_closedoor",
      name = "closedoor",
      size = 5,
    },
    [174] = {
      args = {},
      const = "SCR_OP_WAITDOORANIM",
      handler = "ScrCmd_waitdooranim",
      name = "waitdooranim",
      size = 1,
    },
    [175] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_SETDOOROPEN",
      handler = "ScrCmd_setdooropen",
      name = "setdooropen",
      size = 5,
    },
    [176] = {
      args = {
        { kind = "half", name = "x" },
        { kind = "half", name = "y" },
      },
      const = "SCR_OP_SETDOORCLOSED",
      handler = "ScrCmd_setdoorclosed",
      name = "setdoorclosed",
      size = 5,
    },
    [177] = {
      args = {
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
        { kind = "half", name = "d" },
      },
      const = "SCR_OP_ADDELEVMENUITEM",
      handler = "ScrCmd_addelevmenuitem",
      name = "addelevmenuitem",
      size = 8,
    },
    [178] = {
      args = {},
      const = "SCR_OP_SHOWELEVMENU",
      handler = "ScrCmd_showelevmenu",
      name = "showelevmenu",
      size = 1,
    },
    [179] = {
      args = {
        { kind = "half", name = "out" },
      },
      const = "SCR_OP_CHECKCOINS",
      handler = "ScrCmd_checkcoins",
      name = "checkcoins",
      size = 3,
    },
    [180] = {
      args = {
        { kind = "half", name = "count" },
      },
      const = "SCR_OP_ADDCOINS",
      handler = "ScrCmd_addcoins",
      name = "addcoins",
      size = 3,
    },
    [181] = {
      args = {
        { kind = "half", name = "count" },
      },
      const = "SCR_OP_REMOVECOINS",
      handler = "ScrCmd_removecoins",
      name = "removecoins",
      size = 3,
    },
    [182] = {
      args = {
        { kind = "half", name = "species" },
        { kind = "byte", name = "level" },
        { kind = "half", name = "item" },
      },
      const = "SCR_OP_SETWILDBATTLE",
      handler = "ScrCmd_setwildbattle",
      name = "setwildbattle",
      size = 6,
    },
    [183] = {
      args = {},
      const = "SCR_OP_DOWILDBATTLE",
      handler = "ScrCmd_dowildbattle",
      name = "dowildbattle",
      size = 1,
    },
    [184] = {
      args = {
        { kind = "word", name = "pointer" },
      },
      const = "SCR_OP_SETVADDRESS",
      handler = "ScrCmd_setvaddress",
      name = "setvaddress",
      size = 5,
    },
    [185] = {
      args = {
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_VGOTO",
      handler = "ScrCmd_vgoto",
      name = "vgoto",
      size = 5,
    },
    [186] = {
      args = {
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_VCALL",
      handler = "ScrCmd_vcall",
      name = "vcall",
      size = 5,
    },
    [187] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_VGOTO_IF",
      handler = "ScrCmd_vgoto_if",
      name = "vgoto_if",
      size = 6,
    },
    [188] = {
      args = {
        { kind = "byte", name = "condition" },
        { kind = "word", name = "destination" },
      },
      const = "SCR_OP_VCALL_IF",
      handler = "ScrCmd_vcall_if",
      name = "vcall_if",
      size = 6,
    },
    [189] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_VMESSAGE",
      handler = "ScrCmd_vmessage",
      name = "vmessage",
      size = 5,
    },
    [190] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_VBUFFERMESSAGE",
      handler = "ScrCmd_vbuffermessage",
      name = "vbuffermessage",
      size = 5,
    },
    [191] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_VBUFFERSTRING",
      handler = "ScrCmd_vbufferstring",
      name = "vbufferstring",
      size = 6,
    },
    [192] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      const = "SCR_OP_SHOWCOINSBOX",
      handler = "ScrCmd_showcoinsbox",
      name = "showcoinsbox",
      size = 3,
    },
    [193] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      const = "SCR_OP_HIDECOINSBOX",
      handler = "ScrCmd_hidecoinsbox",
      name = "hidecoinsbox",
      size = 3,
    },
    [194] = {
      args = {
        { kind = "byte", name = "x" },
        { kind = "byte", name = "y" },
      },
      const = "SCR_OP_UPDATECOINSBOX",
      handler = "ScrCmd_updatecoinsbox",
      name = "updatecoinsbox",
      size = 3,
    },
    [195] = {
      args = {
        { kind = "byte", name = "stat" },
      },
      const = "SCR_OP_INCREMENTGAMESTAT",
      handler = "ScrCmd_incrementgamestat",
      name = "incrementgamestat",
      size = 2,
    },
    [196] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_SETESCAPEWARP",
      handler = "ScrCmd_setescapewarp",
      name = "setescapewarp",
      size = 8,
    },
    [197] = {
      args = {},
      const = "SCR_OP_WAITMONCRY",
      handler = "ScrCmd_waitmoncry",
      name = "waitmoncry",
      size = 1,
    },
    [198] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "box" },
      },
      const = "SCR_OP_BUFFERBOXNAME",
      handler = "ScrCmd_bufferboxname",
      name = "bufferboxname",
      size = 4,
    },
    [199] = {
      args = {},
      const = "SCR_OP_TEXTCOLOR",
      handler = "ScrCmd_nop1",
      name = "textcolor",
      size = 1,
      stub = true,
    },
    [200] = {
      args = {},
      const = "SCR_OP_LOADHELP",
      handler = "ScrCmd_nop1",
      name = "loadhelp",
      size = 1,
      stub = true,
    },
    [201] = {
      args = {},
      const = "SCR_OP_UNLOADHELP",
      handler = "ScrCmd_nop1",
      name = "unloadhelp",
      size = 1,
      stub = true,
    },
    [202] = {
      args = {},
      const = "SCR_OP_SIGNMSG",
      handler = "ScrCmd_nop1",
      name = "signmsg",
      size = 1,
      stub = true,
    },
    [203] = {
      args = {},
      const = "SCR_OP_NORMALMSG",
      handler = "ScrCmd_nop1",
      name = "normalmsg",
      size = 1,
      stub = true,
    },
    [204] = {
      args = {},
      const = "SCR_OP_COMPAREHIDDENVAR",
      handler = "ScrCmd_nop1",
      name = "comparehiddenvar",
      size = 1,
      stub = true,
    },
    [205] = {
      args = {
        { kind = "half", name = "slot" },
      },
      const = "SCR_OP_SETMODERNFATEFULENCOUNTER",
      handler = "ScrCmd_setmodernfatefulencounter",
      name = "setmodernfatefulencounter",
      size = 3,
    },
    [206] = {
      args = {
        { kind = "half", name = "slot" },
      },
      const = "SCR_OP_CHECKMODERNFATEFULENCOUNTER",
      handler = "ScrCmd_checkmodernfatefulencounter",
      name = "checkmodernfatefulencounter",
      size = 3,
    },
    [207] = {
      args = {},
      const = "SCR_OP_TRYWONDERCARDSCRIPT",
      handler = "ScrCmd_trywondercardscript",
      name = "trywondercardscript",
      size = 1,
    },
    [208] = {
      args = {},
      const = "SCR_OP_SETWORLDMAPFLAG",
      handler = "ScrCmd_nop1",
      name = "setworldmapflag",
      size = 1,
      stub = true,
    },
    [209] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARPSPINENTER",
      handler = "ScrCmd_warpspinenter",
      name = "warpspinenter",
      size = 8,
    },
    [210] = {
      args = {
        { kind = "half", name = "slot" },
        { kind = "byte", name = "location" },
      },
      const = "SCR_OP_SETMONMETLOCATION",
      handler = "ScrCmd_setmonmetlocation",
      name = "setmonmetlocation",
      size = 4,
    },
    [211] = {
      args = {
        { kind = "half", name = "puzzleNumber" },
      },
      const = "SCR_OP_MOVEROTATINGTILEOBJECTS",
      handler = "ScrCmd_moverotatingtileobjects",
      name = "moverotatingtileobjects",
      size = 3,
    },
    [212] = {
      args = {},
      const = "SCR_OP_TURNROTATINGTILEOBJECTS",
      handler = "ScrCmd_turnrotatingtileobjects",
      name = "turnrotatingtileobjects",
      size = 1,
    },
    [213] = {
      args = {
        { kind = "half", name = "isTrickHouse" },
      },
      const = "SCR_OP_INITROTATINGTILEPUZZLE",
      handler = "ScrCmd_initrotatingtilepuzzle",
      name = "initrotatingtilepuzzle",
      size = 3,
    },
    [214] = {
      args = {},
      const = "SCR_OP_FREEROTATINGTILEPUZZLE",
      handler = "ScrCmd_freerotatingtilepuzzle",
      name = "freerotatingtilepuzzle",
      size = 1,
    },
    [215] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARPMOSSDEEPGYM",
      handler = "ScrCmd_warpmossdeepgym",
      name = "warpmossdeepgym",
      size = 8,
    },
    [216] = {
      args = {},
      const = "SCR_OP_SELECTAPPROACHINGTRAINER",
      handler = "ScrCmd_selectapproachingtrainer",
      name = "selectapproachingtrainer",
      size = 1,
    },
    [217] = {
      args = {},
      const = "SCR_OP_LOCKFORTRAINER",
      handler = "ScrCmd_lockfortrainer",
      name = "lockfortrainer",
      size = 1,
    },
    [218] = {
      args = {},
      const = "SCR_OP_CLOSEBRAILLEMESSAGE",
      handler = "ScrCmd_closebraillemessage",
      name = "closebraillemessage",
      size = 1,
    },
    [219] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_MESSAGEINSTANT",
      handler = "ScrCmd_messageinstant",
      name = "messageinstant",
      size = 5,
    },
    [220] = {
      args = {
        { kind = "byte", name = "mode" },
      },
      const = "SCR_OP_FADESCREENSWAPBUFFERS",
      handler = "ScrCmd_fadescreenswapbuffers",
      name = "fadescreenswapbuffers",
      size = 2,
    },
    [221] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "trainerId" },
      },
      const = "SCR_OP_BUFFERTRAINERCLASSNAME",
      handler = "ScrCmd_buffertrainerclassname",
      name = "buffertrainerclassname",
      size = 4,
    },
    [222] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "trainerId" },
      },
      const = "SCR_OP_BUFFERTRAINERNAME",
      handler = "ScrCmd_buffertrainername",
      name = "buffertrainername",
      size = 4,
    },
    [223] = {
      args = {
        { kind = "word", name = "text" },
      },
      const = "SCR_OP_POKENAVCALL",
      handler = "ScrCmd_pokenavcall",
      name = "pokenavcall",
      size = 5,
    },
    [224] = {
      args = {
        { kind = "byte", name = "\\map_id >> 8" },
        { kind = "byte", name = "\\map_id & 0xFF" },
        { kind = "byte", name = "a" },
        { kind = "half", name = "b" },
        { kind = "half", name = "c" },
      },
      const = "SCR_OP_WARPWHITEFADE",
      handler = "ScrCmd_warpwhitefade",
      name = "warpwhitefade",
      size = 8,
    },
    [225] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "category" },
      },
      const = "SCR_OP_BUFFERCONTESTNAME",
      handler = "ScrCmd_buffercontestname",
      name = "buffercontestname",
      size = 4,
    },
    [226] = {
      args = {
        { kind = "byte", name = "id" },
        { kind = "half", name = "item" },
        { kind = "half", name = "quantity" },
      },
      const = "SCR_OP_BUFFERITEMNAMEPLURAL",
      handler = "ScrCmd_bufferitemnameplural",
      name = "bufferitemnameplural",
      size = 6,
    },
  },
  byName = {
    addcoins = 180,
    adddecoration = 75,
    addelevmenuitem = 177,
    additem = 68,
    addmoney = 144,
    addobject = 85,
    addobjectat = 86,
    addpcitem = 73,
    addvar = 23,
    animateflash = 154,
    applymovement = 79,
    applymovementat = 80,
    braillemessage = 120,
    bufferboxname = 198,
    buffercontestname = 225,
    bufferdecorationname = 129,
    bufferitemname = 128,
    bufferitemnameplural = 226,
    bufferleadmonspeciesname = 126,
    buffermovename = 130,
    buffernumberstring = 131,
    bufferpartymonnick = 127,
    bufferspeciesname = 125,
    bufferstdstring = 132,
    bufferstring = 133,
    buffertrainerclassname = 221,
    buffertrainername = 222,
    call = 4,
    call_if = 7,
    callnative = 35,
    callstd = 9,
    callstd_if = 11,
    checkcoins = 179,
    checkdecor = 77,
    checkdecorspace = 78,
    checkflag = 43,
    checkitem = 71,
    checkitemspace = 70,
    checkitemtype = 72,
    checkmodernfatefulencounter = 206,
    checkmoney = 146,
    checkpartymove = 124,
    checkpcitem = 74,
    checkplayergender = 160,
    checktrainerflag = 96,
    choosecontestmon = 139,
    clearflag = 42,
    cleartrainerflag = 98,
    closebraillemessage = 218,
    closedoor = 173,
    closemessage = 104,
    compare_local_to_local = 27,
    compare_local_to_ptr = 29,
    compare_local_to_value = 28,
    compare_ptr_to_local = 30,
    compare_ptr_to_ptr = 32,
    compare_ptr_to_value = 31,
    compare_var_to_value = 33,
    compare_var_to_var = 34,
    comparehiddenvar = 204,
    contestlinktransfer = 142,
    copybyte = 21,
    copylocal = 20,
    copyobjectxytoperm = 100,
    copyvar = 25,
    createvobject = 170,
    delay = 40,
    dofieldeffect = 156,
    dotimebasedevents = 45,
    dotrainerbattle = 93,
    doweather = 165,
    dowildbattle = 183,
    drawbox = 114,
    drawboxtext = 116,
    ["end"] = 2,
    endram = 13,
    erasebox = 115,
    faceplayer = 90,
    fadedefaultbgm = 53,
    fadeinbgm = 56,
    fadenewbgm = 54,
    fadeoutbgm = 55,
    fadescreen = 151,
    fadescreenspeed = 152,
    fadescreenswapbuffers = 220,
    freerotatingtilepuzzle = 214,
    getpartysize = 67,
    getplayerxy = 66,
    getpokenewsactive = 150,
    gettime = 46,
    giveegg = 122,
    givemon = 121,
    ["goto"] = 5,
    goto_if = 6,
    gotobeatenscript = 95,
    gotonative = 36,
    gotopostbattlescript = 94,
    gotostd = 8,
    gotostd_if = 10,
    hidecoinsbox = 193,
    hidemoneybox = 148,
    hidemonpic = 118,
    hideobjectat = 89,
    incrementgamestat = 195,
    initclock = 44,
    initrotatingtilepuzzle = 213,
    loadbyte = 16,
    loadbytefromptr = 18,
    loadhelp = 200,
    loadword = 15,
    lock = 106,
    lockall = 105,
    lockfortrainer = 217,
    message = 103,
    messageautoscroll = 155,
    messageinstant = 219,
    moverotatingtileobjects = 211,
    multichoice = 111,
    multichoicedefault = 112,
    multichoicegrid = 113,
    nop = 0,
    nop1 = 1,
    normalmsg = 203,
    opendoor = 172,
    playbgm = 51,
    playfanfare = 49,
    playmoncry = 161,
    playse = 47,
    playslotmachine = 137,
    pokemart = 134,
    pokemartdecoration = 135,
    pokemartdecoration2 = 136,
    pokenavcall = 223,
    random = 143,
    release = 108,
    releaseall = 107,
    removecoins = 181,
    removedecoration = 76,
    removeitem = 69,
    removemoney = 145,
    removeobject = 83,
    removeobjectat = 84,
    resetobjectsubpriority = 169,
    resetweather = 163,
    ["return"] = 3,
    returnram = 12,
    savebgm = 52,
    selectapproachingtrainer = 216,
    setberrytree = 138,
    setdivewarp = 64,
    setdoorclosed = 176,
    setdooropen = 175,
    setdynamicwarp = 63,
    setescapewarp = 196,
    setfieldeffectargument = 157,
    setflag = 41,
    setflashlevel = 153,
    setholewarp = 65,
    setmaplayoutindex = 167,
    setmetatile = 162,
    setmodernfatefulencounter = 205,
    setmonmetlocation = 210,
    setmonmove = 123,
    setmysteryeventstatus = 14,
    setobjectmovementtype = 101,
    setobjectsubpriority = 168,
    setobjectxy = 87,
    setobjectxyperm = 99,
    setorcopyvar = 26,
    setptr = 17,
    setptrbyte = 19,
    setrespawn = 159,
    setstepcallback = 166,
    settrainerflag = 97,
    setvaddress = 184,
    setvar = 22,
    setwarp = 62,
    setweather = 164,
    setwildbattle = 182,
    setworldmapflag = 208,
    showcoinsbox = 192,
    showcontestpainting = 119,
    showcontestresults = 141,
    showelevmenu = 178,
    showmoneybox = 147,
    showmonpic = 117,
    showobjectat = 88,
    signmsg = 202,
    special = 37,
    specialvar = 38,
    startcontest = 140,
    subvar = 24,
    textcolor = 199,
    trainerbattle = 92,
    trywondercardscript = 207,
    turnobject = 91,
    turnrotatingtileobjects = 212,
    turnvobject = 171,
    unloadhelp = 201,
    updatecoinsbox = 194,
    updatemoneybox = 149,
    vbuffermessage = 190,
    vbufferstring = 191,
    vcall = 186,
    vcall_if = 188,
    vgoto = 185,
    vgoto_if = 187,
    vmessage = 189,
    waitbuttonpress = 109,
    waitdooranim = 174,
    waitfanfare = 50,
    waitfieldeffect = 158,
    waitmessage = 102,
    waitmoncry = 197,
    waitmovement = 81,
    waitmovementat = 82,
    waitse = 48,
    waitstate = 39,
    warp = 57,
    warpdoor = 59,
    warphole = 60,
    warpmossdeepgym = 215,
    warpsilent = 58,
    warpspinenter = 209,
    warpteleport = 61,
    warpwhitefade = 224,
    yesnobox = 110,
  },
  count = 227,
}
