#-------------#
# Import Vars #
#-------------#
Import('*')

#---------------------------------#
# Distribute to src_dir & bin_dir #
#---------------------------------#
env.Distribute (src_dir, ['SConscript'])

#----------------#
# Subdirectories #
#----------------#
Export(['env', 'src_dir', 'bin_dir'])

if env['minimal']:
    SConscript(dirs = ['TL2', 'XS', 'GT', '360', 'AX2'])
else:
    import glob

    for path in glob.glob('*/SConscript'):
        SConscript(path)

